### ISSUE TITLE
Windows 7 problem?

### ISSUE THREAD

**Issue by bitbeans** [bitbeans/SimpleDnsCrypt#106]
- Install: .NET 4.6.x Framework
- Install: Visual C++ Redistributable for Visual Studio 2015
- Install: Update for Universal C Runtime in Windows https://support.microsoft.com/en-us/kb/2999226

**Comment by ellephantz** [comment]
my windows update error since i use ancile 1.8,
so i cannot install https://support.microsoft.com/en-us/kb/2999226 into my pc

**Comment by bitbeans** [comment]
Please update to 0.4.1, i included the files

**Comment by ellephantz** [comment]
using installer 0.4.1 still showing the same message error
