### ISSUE TITLE
Uninstall is Incomplete

### ISSUE THREAD

**Issue by HJLBX** [bitbeans/SimpleDnsCrypt#107]
Most recent version on Windows 10 1607.

1.  When uninstall, the DNS remains at 127.0.0.1 instead of being removed and set to automatically detect.

2.  The uninstaller fails and program remains in Programs and Features list - and cannot be removed.

* * * * *

Also, the prior issue of inaccessible DNS remains.  When restart system the network tray icon triangle with exclamation mark always appears with SDNSC installed; when uninstalled there is no problem.

My test system networking is fine with SDNSC uninstalled.  The problems begin once it is installed.

I've tried just about all the DNS servers to eliminate any doubt that the DNS server was the issue.  They are not.

**Comment by gleamland** [comment]
Same problem here. The update fails and i can't install or uninstall it.
- Windows 7 Ultimate 64bit -
![image 1](https://cloud.githubusercontent.com/assets/14210961/22079757/83e77244-ddef-11e6-98b8-2e0d6e943afd.jpg)

**Comment by bitbeans** [comment]
Please update to the new version 0.4.1
