### ISSUE TITLE
unavailable loggin path cuase startup failure for the service [Plugin]

### ISSUE THREAD

**Issue by ZIEXED** [bitbeans/SimpleDnsCrypt#108]
Service fail to start if logging plugin enabled and the drive where logs are saved is unavailable
The drive where dns logs are saved take a few seconds every startup to be available
it would be great if u can change the behavior to not save dns queries if the drive is unreachable

_Should I report this to [dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy/issues)?_

**Comment by bitbeans** [comment]
@ZIEXED i don`t know. but the service will start on windows boot. Simple DNSCrypt does not control the auto start.

> Should I report this to dnscrypt-proxy?

maybe its the better place
