### ISSUE TITLE
does not work on windows 8.1 32bit

### ISSUE THREAD

**Issue by mailinglists35** [bitbeans/SimpleDnsCrypt#111]
![image](https://cloud.githubusercontent.com/assets/2054302/22088020/5aa8f580-ddf2-11e6-8663-e2d8fa65c76f.png)

**Comment by bitbeans** [comment]
Install: Update for Universal C Runtime in Windows https://support.microsoft.com/en-us/kb/2999226

does this work for you?

**Comment by mailinglists35** [comment]
thank you, after installing the update the app no longer shows that message, however it still does not work, it shows this message now:


![image](https://cloud.githubusercontent.com/assets/2054302/22144417/b63fe0b2-df0e-11e6-9454-a6595892a843.png)


I will try as instructed, will deinstall and reinstall

**Comment by mailinglists35** [comment]
it worked after uninstall, reboot and reinstall
