### ISSUE TITLE
Plugin libdcplugin_ldns_blocking: support of "logfile" parameter

### ISSUE THREAD

**Issue by TroudhuK** [bitbeans/SimpleDnsCrypt#112]
I just updated to 0.4.1, with auto-update to see if it works well, and if I don't loose my settings. I have lost at least one of them: the "logfile" parameter of the libdcplugin_ldns_blocking plugin, very useful to see what is overblock when something doesn't work well. In registry, for example: 

> libdcplugin_ldns_blocking.dll,--ips=C:\Program Files (x86)\bitbeans\Simple DNSCrypt\data\W10Privacy_IPs_edited.txt,--domains=C:\Program Files (x86)\bitbeans\Simple DNSCrypt\data\domains-blacklist.txt,**--logfile=C:\Program Files (x86)\bitbeans\Simple DNSCrypt\data\blocked.log**

**Comment by bitbeans** [comment]
@TroudhuK please update to 0.4.3
