### ISSUE TITLE
[Feature Request] Support for multiple wildcards  

### ISSUE THREAD

**Issue by MacgyverJohnson** [bitbeans/SimpleDnsCrypt#113]
Hello there @bitbeans 
It would be great to have support for multiple wildcard support(with wildcard in between words) for libdcplugin_ldns_blocking 
like 
` *.zeroredirect*.com` which could block entries like

```

zc1.zeroredirect11.com
zeroredirect10.com
zeroredirect11.com
zeroredirect12.com
zeroredirect1.com
zeroredirect2.com
zeroredirect3.com
zeroredirect4.com
zeroredirect5.com
zeroredirect6.com
zeroredirect7.com
zeroredirect8.com
zeroredirect9.com
zeroredirect.com
a.zeroredirect.com
a.zeroredirect1.com
a.zeroredirect2.com
b.zeroredirect.com
b.zeroredirect1.com
b.zeroredirect2.com
c.zeroredirect.com
c.zeroredirect1.com
c.zeroredirect2.com
d.zeroredirect.com
d.zeroredirect2.com
e.zeroredirect.com
e.zeroredirect2.com
f.zeroredirect.com
f.zeroredirect2.com
g.zeroredirect.com
h.zeroredirect.com
i.zeroredirect.com
j.zeroredirect.com
k.zeroredirect.com
l.zeroredirect.com
m.zeroredirect.com
n.zeroredirect.com
o.zeroredirect.com
p.zeroredirect.com
q.zeroredirect.com
r.zeroredirect.com
s.zeroredirect.com
t.zeroredirect.com
u.zeroredirect.com
v.zeroredirect.com
w.zeroredirect.com
www.zeroredirect2.com
x.zeroredirect.com
y.zeroredirect.com
z.zeroredirect.com
za.zeroredirect1.com
zb.zeroredirect1.com
zc.zeroredirect1.com
zd.zeroredirect1.com
zd.zeroredirect2.com
zd1.zeroredirect1.com
ze.zeroredirect1.com
ze.zeroredirect2.com
ze1.zeroredirect1.com
zf.zeroredirect1.com
zj.zeroredirect1.com
zj1.zeroredirect1.com
zk.zeroredirect1.com
zm1.zeroredirect5.com
zr1.zeroredirect11.com
zs1.zeroredirect1.com
```
(taken from StevenBlacks Unified Host file https://github.com/StevenBlack/hosts)
Best Regards

**Comment by bitbeans** [comment]
I think SimpleDnsCrypt already support this format (you can add it the Block and Blacklist tab).
If it is not working you need to check the https://github.com/jedisct1/dnscrypt-proxy project.

**Comment by jedisct1** [comment]
Wildcards can only be at the beginning and/or at the end. This allows efficient indexing and lookups are very fast even with very large lists.

Matching patterns with inner wildcards would either require quadratic time or a lot of memory. Both are really bad for routers and embedded systems that are common platforms for dnscrypt-proxy.

But wait. There is a way better alternative, that will also block way more related domains.

The proxy (thus SimpleDNSCrypt) can also block IP addresses and subnets. All the names from your set actually resolve to a small set of IP addresses:

```
34.193.22.16
34.194.10.180
52.0.196.40
52.2.182.44
52.201.27.33
52.203.224.169
52.204.54.103
52.22.103.37
52.3.15.211
52.55.215.125
52.6.135.234
54.165.187.250
54.172.123.81
54.173.81.97
54.208.53.86
54.82.151.120
54.84.0.18
54.85.183.119
54.86.136.167
54.88.117.14
```

Many more DNS names with the same pattern, likely to be used for the same purpose, map to these IPs.

**Comment by jedisct1** [comment]
Alternatively, you can just block `*zerodirect*`. The probability to hit a false positive is likely to be very small.

**Comment by MacgyverJohnson** [comment]
Thanks for the swift reply!!!!
