### ISSUE TITLE
DNSCrypt 1.9.4

### ISSUE THREAD

**Issue by HJLBX** [bitbeans/SimpleDnsCrypt#115]
There are multiple issues with DNSCrypt 1.9.4:

- The test command will not always recognize the .conf file and return ERRORs
- During install, the .conf file will not set the DNS to 127.0.0.1
- Upon every system reboot, the Windows network tray icon will be an exclamation mark within a yellow triangle for quite some time
- The Windows Networking Troubleshooter will return "The network is configured with an invalid IP address" or "The DNS Server is not responding" or "The default gateway is not available"
- Sometimes, inexplicably, the DNS Server IP address will revert to the ISP's DNS

I can reproduce these issues, at will with DNSCrypt, on WIndows 10 1607 14393.693 and prior - on a clean install of Windows with no other software installed except DNSCrypt.

Sorry that I have reported these previously as Simple DNSCrypt problems.  They are not.  They are DNSCrypt problems.

Until the underlying DNSCrypt problems get a complete fix, then whatever GUI a person uses is pointless.

**Comment by bitbeans** [comment]
So you are on the wrong project? :) https://github.com/jedisct1/dnscrypt-proxy/issues

**Comment by zymase** [comment]
@HJLBX this is indeed not the right place but since we're at it all I can say is that I'm running DNSCrypt 1.9.4 (x64) on Windows 7 (x64) without the slightest issue.

Perhaps we'll carry on at https://github.com/jedisct1/dnscrypt-proxy/issues ?

**Comment by HJLBX** [comment]
@bitbeans - just to inform you if others report issues that are DNSCrypt problems - and not Simple DNSCrypt problems here - as some have done in the past

@zymase - Isn't that wonderful for you

**Comment by zymase** [comment]
@HJLBX no point in being sarcastic when I wouldn't have had to infirm your statement implicitly accusing DNSCrypt of being buggy when the only bug in this scenario is Windows 10.
