### ISSUE TITLE
Forwarding

### ISSUE THREAD

**Issue by tadev** [bitbeans/SimpleDnsCrypt#121]
Since SimpleDNSCrypt is not using dnscrypt-proxy's configuration file [dnscrypt-proxy.conf](https://raw.githubusercontent.com/jedisct1/dnscrypt-proxy/master/dnscrypt-proxy.conf) it does not seem possible to use the forwarding feature of dnscrypt-proxy, even though the required library ldns_blocking comes with Simple DNSCrypt's version of dnscrypt-proxy.

Usage of dnscrypt-proxy's configuration file would be ideal, since it allows using features that do not yet have GUI support. 
However it would be amazing if you can add the forwarding feature under the "Block and Blacklist" section. It is very useful to forward dns requests for local domains to the local router.

More info:
```
## Forward queries for specific zones to one or more non-DNSCrypt resolvers.
## For instance, this can be used to redirect queries for local domains to
## the router, or queries for an internal domain to an internal DNS server.
## Multiple whitespace-delimited zones and IP addresses can be specified.
## Do not enable this unless you absolutely know you need it.
## If you see useless queries to these zones, you'd better block them with
## the BlackList feature instead of sending them in clear text to the router.
## This uses a plugin that requires dnscrypt-proxy to be compiled with
## the ldns library.

# Forward domains:"test private localdomain lan" to:"192.168.100.254"
```

**Comment by CHEF-KOCH** [comment]
Dublicate of #77.
