### ISSUE TITLE
Malwarebytes

### ISSUE THREAD

**Issue by AlphaCzerwinski** [bitbeans/SimpleDnsCrypt#123]
I don't think this is a problem, just an information item.

Recently, I installed a product called [MalwareBytes ](https://www.malwarebytes.com/) on my Windows 7 machine.

That program popped up an alert and blocked the resolver IP addresses when SimpleDnsCrypt reached out on the internet.

So, within MalwareBytes settings I "excluded" (whitelisted) these three  .EXE files:
SimpleDnsCrypt.exe
dnscrypt-proxy-secondary.exe
dnscrypt-proxy.exe

and so I no longer get those alerts.  Hopefully, I have not introduced a security hole!!!
Alternatively, I could have whitelisted just the resolver IP addresses, but since I am traveling frequently, I may change my selected resolvers.  So, I thought to just whitelist those EXE files.

This story is mentioned here just as an FYI to others who may be using these two programs.

**Comment by jedisct1** [comment]
Maybe the amazing @hasherezade could help have this fixed?

**Comment by fr33tux** [comment]
Which resolver were you using?
The detections should not occur anymore.

**Comment by AlphaCzerwinski** [comment]
Well, I am in a different location now, and of course using a different ISP (here it is a wireless ISP through a shortwave radio on a 50 foot antenna mast).
But I have not yet changed the resolvers.   Therefore, I believe I was using
1. D0wn Resolver US 107.181.187.219
2. Secondary OpenNIC Anycast 185.121.177.53

So later today I will go into Malwarebytes and clear the whitelist.  Then I will report back here.

**Comment by fr33tux** [comment]
Thanks - I've checked again and those IP are not detected.
--
fr33tux
https://fr33tux.org - https://toolslib.net
GPG : 8E7F 8550 9FBD 9ED8 E68F ACB9 18E8 99E6 80C4 FF62
XMPP: fr33tux@jabber.otr.im

**Comment by AlphaCzerwinski** [comment]
Thank you Jerome.  I have not seen any alarms since I removed the whitelist in Malwarebytes.  I will try a few different resolvers but I believe you have fixed it.
