### ISSUE TITLE
Feature request - Add "Minimize to System Tray" option

### ISSUE THREAD

**Issue by MKaveh** [bitbeans/SimpleDnsCrypt#125]
Minimize to system tray when either "Close" or "Minimize" button on title bar is pressed.
It can be useful when switching between DNS and temporarily checking them while browsing or in case we want to have a visual hint that DNS proxy is active and running, without having the main window icon displayed in Task bar (it will be nice to optionally display currently active DNS name when mouse is moved over system tray icon).

**Comment by evilvibes** [comment]
This would be nice

**Comment by monstertruckpa** [comment]
Me too, would be nice the simplednscrypt on tray.

**Comment by bitbeans** [comment]
as it`s a WPF application ... i need to think about it :)

**Comment by bugcon** [comment]
Would Hardcodet's 'NotifyIcon' work here?

http://www.hardcodet.net/wpf-notifyicon
https://www.nuget.org/packages/Hardcodet.NotifyIcon.Wpf/
https://bitbucket.org/hardcodet/notifyicon-wpf/src

**Comment by Rictusempra** [comment]
It has been a year since this issue dropped.
Do you need any help for this here? @bitbeans
