### ISSUE TITLE
SimpleDnsCrypt service needs to be manually restarted after startup.

### ISSUE THREAD

**Issue by liubomirwm** [bitbeans/SimpleDnsCrypt#129]
Although dnscrypt-proxy works in task manager and has a green on "Primary DNS service", it still needs to be manually restarted after startup.

SimpleDnsCrypt 0.4.2 on Windows 10 Pro 64 bit version 1607 (OS build 14393.953). I am going to 15063 today and will see if it works after the upgrade. Please see the screenshots.
![screenshot_20170406095435](https://cloud.githubusercontent.com/assets/16529989/24742687/f8aa7422-1ab3-11e7-8f44-a5cabf7dddb9.png)
![screenshot_20170406095619](https://cloud.githubusercontent.com/assets/16529989/24742686/f8a952cc-1ab3-11e7-878f-0459780a976c.png)

**Comment by cerberii** [comment]
I also have this problem, I can confirm on creators update it does not work either.  Please fix this.

**Comment by bitbeans** [comment]
duplicate #134
