### ISSUE TITLE
My VPN connection is grayed out

### ISSUE THREAD

**Issue by garlicgmailmanager** [bitbeans/SimpleDnsCrypt#131]
Hello. I am using Simple DNSCrypt. I have Ethernet and WiFi connections toggled on, however the VPN connection remains greyed out. When I am using the VPN connection I get Google DNS results and not the results i get when just using wife off vpn. IS DNSCrypt still working for me effectively?

**Comment by garlicgmailmanager** [comment]
okay, after restarting it now shows the old OPENdns ips i have set as well as Total Server Solutions (DNScrypts set DNS) and like 1 or 2 DNS for Google. This all look kosher?

**Comment by CHEF-KOCH** [comment]
When you use e.g. OpenVPN ensure you use (2.4.0.0 or higher) and add to your .openvpn config file the `pull-filter ignore "dhcp-option DNS"` line to ensure it uses DnsCrypt DNS instead of own DNS server.
