### ISSUE TITLE
I must restart services manually!

### ISSUE THREAD

**Issue by robin98** [bitbeans/SimpleDnsCrypt#134]
Hi,
I **must** restart services manually every time i'm restart my computer or sleep windows.
I have this problem since i have windows 10 build 1607 while now on windows 10 build 1703!
I create a Issues ticket right here about 6 months ago and it's still persist!

**Comment by zticky** [comment]
I experience the same problem. Service doesn't start when windows boot

**Comment by bitbeans** [comment]
@robin98 @zticky can you test this with the latest release please. thank you! :)

**Comment by bitbeans** [comment]
Tested on: 1709 with the newest Simple DNSCrypt build: 0.4.3 x64

**Comment by zticky** [comment]
Installed Simple DNSCrypt build: 0.4.3 x64 on 1709
Get error: Missing Universal C Runtime

**Comment by bitbeans** [comment]
@zticky Did you install Microsoft Visual C++ Redistributable for Visual Studio 2017 https://go.microsoft.com/fwlink/?LinkId=746572 ?

**Comment by zticky** [comment]
Thanx, successfully installed

**Comment by liubomirwm** [comment]
@bitbeans Do you have an idea what might cause the issue?

**Comment by simoncpu** [comment]
The temporary fix is to turn off fast boot. Fast boot causes a lot of problems in other services such as WSL and OpenVPN as well. However, DNSCrypt still needs to be restarted if your PC goes into sleep mode.
