### ISSUE TITLE
Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by Scorpio479** [bitbeans/SimpleDnsCrypt#135]
I just downloaded and installed Simple DNSCrypt and when I click on a network card I get "Exception has been thrown by the target of an invocation
" message and the program shuts down. Any help on resolving this issue would be helpful. Thanks

Windows 7 Home Premium Service Pack 1
Comcast Xfinity ISP
Private Internet Access VPN

![capture 2](https://cloud.githubusercontent.com/assets/28404282/25719273/805ca3a6-30ce-11e7-9cd3-f9fe009daa01.JPG)
![capture](https://cloud.githubusercontent.com/assets/28404282/25719275/80784af2-30ce-11e7-9a48-96af3e56de79.JPG)

**Comment by bitbeans** [comment]
@Scorpio479 please try the latest version
