### ISSUE TITLE
Enabling Logging disables Primary DNSCrypt Serivice

### ISSUE THREAD

**Issue by iCodeHead** [bitbeans/SimpleDnsCrypt#136]
I'm on Windows 10 (x64). I just installed DNSCrypt 0.4.2 (with dnscrypt-proxy 1.9.4) without issues and it is working fine except I am not able to enable Logging Plugin. When I go into Advanced Settings/ Plugins/ Logging and no matter where I select a folder for the log file then Enable Logging, it always disables the Primary DNSCrypt Serivice. The Event Error log shows "The dnscrypt-proxy service terminated unexpectedly". Any suggestion would be greatly appreciated.

**Comment by bitbeans** [comment]
Please test the newest version
