### ISSUE TITLE
Update to dnscrypt-proxy 1.9.5

### ISSUE THREAD

**Issue by bitbeans** [bitbeans/SimpleDnsCrypt#138]

**Comment by monstertruckpa** [comment]
Hey Bitbeans your list dns selectable for example D0wn Resolver Costa Rica 01 (in whois the information say) ISP DATA MINERS S.A ( Racknation.cr )  It seems that those DNSCRYPT with DNSSEC are not very sincere. I have felt some huge slowness conecctions in google with this dns, the other   D0wn Resolver Mexico 01. check please.
