### ISSUE TITLE
How to work with blacklists

### ISSUE THREAD

**Issue by rdbox** [bitbeans/SimpleDnsCrypt#139]
I specify the domains I need
example
```
* .example.com
* Malware *
```

does not work

**Comment by TroudhuK** [comment]
You have to remove spaces, it is taken account.

**Comment by rdbox** [comment]
excellent! Worked
Tell me please how to use the whitelist?
Which team should I dial?

**Comment by TroudhuK** [comment]
SimpleDnsCrypt doesn't offer a whitelist functionality yet. You should see directly with the dnscrypt-proxy project. https://github.com/jedisct1/dnscrypt-proxy/tree/master/contrib => Here is all you need, with a python script to generate the domain black list from black and white ones. Then you overwrite the files you generated from SimpleDnsCrypt and restart dnscrypt-proxy.

**Comment by benyaminl** [comment]
@TroudhuK I've question about blacklisting, I'm use the SDC i mean simple dns crypt that portable via zip, and I tried to do a blacklisting, but It doesn't work anyway, I've tick the option, but when I quit the program, the tick got disabled, is there anything to fix this or something else I need to do fixing it? Thanks

**Comment by TroudhuK** [comment]
Sorry, I don't know about the portable version, but the installed one use Windows registry.

**Comment by benyaminl** [comment]
Ah maybe that's the problem. So I found it. Thanks



Benyamin Limanto

sent from my ASUS FonePad 8



Pada tanggal 31 Jul 2017 16.38, "TroudhuK" <notifications@github.com>
menulis:
