### ISSUE TITLE
win 10 creators update - does not start on boot

### ISSUE THREAD

**Issue by cerberii** [bitbeans/SimpleDnsCrypt#143]
I have to open the app and toggle primary dnscrypt service off/on.  It is still on from previous boot.  Please fix this to make sure it comes on at reboot.

**Comment by CHEF-KOCH** [comment]
Temp workaround (for me) was to set `Advanced Settings - transport Settings` to TCP instead of UDP. Well it's slower (a bit) but at last it works from the beginning.

**Comment by bitbeans** [comment]
@cerberii please test the newest release
