### ISSUE TITLE
Ability to Bypass DNSCrypt for Certain Domains?

### ISSUE THREAD

**Issue by jonathanou** [bitbeans/SimpleDnsCrypt#144]
Is there a way to bypass DNSCrypt and fallback to the original DNS server for certain domains?  Similar to what [dnscrypt-osxclient](https://github.com/alterstep/dnscrypt-osxclient) provides (in the Advanced tab)?  

This is useful in situations where there are local private servers in the local network.

**Comment by benyaminl** [comment]
@jonathanou For now seems nothing is towrads that idea, but you could edit your hosts file so it will fallback to some domain for a certain IP.

**Comment by jonathanou** [comment]
Ah yes I can try that.  The problem is if I want to use it at work, there are many private servers, and every coworker's machine would have to be listed if I wanted to access their machines.

But this is still a good workaround to know about!  I can use it at home where there are not that many local servers.  Thanks!

**Comment by benyaminl** [comment]
@jonathanou yeah at least for now. Because I don't think native dnscrypt support bypassing that kind of thing.. Or maybe you could make a piece of software before it queries to dnscrypt server. Hoping the developer develop such feature to bypassing, because at work I also havr many server that doesn't work with dnscrypt, and for now I just bypass it using hosts file.

**Comment by jedisct1** [comment]
The proxy does support this: https://github.com/jedisct1/dnscrypt-proxy/wiki/Exceptions

**Comment by bitbeans** [comment]
coming: https://github.com/bitbeans/SimpleDnsCrypt/pull/152

**Comment by chstdu** [comment]
Windows 10 tells me that I have no internet access although I am on GitHub now. I guess I can fix it if I bypass my primary DNS suffix (this internal site is the only one which I cannot access any more with simple DnsCrypt). How can I activate "forwarding" which was included in #152 ? Thank you in advance!

**Comment by begundal** [comment]
Is this feature implemented in simplednscrypt I have yet found Exceptions rule.

**Comment by the91end** [comment]
For those looking for this, it's called "Forwarding"
