### ISSUE TITLE
[QUESTION] Block And BlackList isn't working

### ISSUE THREAD

**Issue by benyaminl** [bitbeans/SimpleDnsCrypt#148]
Hello, I've question, why when I tried to enable the DNS blocking domain block it's just ticked on the status but never working? When I quit the app, it turned off again. Need help, Thanks

**Comment by CHEF-KOCH** [comment]
It's on your end it's working fine.

**Comment by benyaminl** [comment]
Anyway how to debug it? Why only mine the bug or problem occurs.



Benyamin Limanto

sent from my ASUS FonePad 8



Pada tanggal 27 Jul 2017 07.25, "CHEF-KOCH" <notifications@github.com>
menulis:

**Comment by iWARR** [comment]
Hi

I've use 'Simlpe DNSCrypt' during several builds and everything is OK, exept blocking. It **never worked** for me (Win8.1, x64).

In some unknown cases I can't make it work as expected (brilliant and unique feature, especially, masks!). I've read all known info about this subject I can: here and at many other forums over Internet, but with no luck... My blocking domains list is ready and turning-on well, but blocking doesn't work at all (even for one simple test-input). Tested on two chromium browsers (Opera and Vivaldi) and TOR...

Or I have some DNS leak (but dnsleaktest is OK), or 'libdcplugin_ldns_blocking' plugin doesn't work on my system. I've even globally reset TCP/IP protocol, Winsock, clear some registry settings for network adapters and network connections, but nothing was helped.

Did you think about problem of internal Async DNS Configuration in the modern chromium browsers and redirecting / prefetch technologies that using own DNS calls? Google DNS are completely blocked and under logs in my system, so I can see this kind of redirecting is really existing. For example: Google search -> MS TechNet -> (inside redirecting with Google DNS, not DNSCrypt) -> login.live.com, but expected: Google search -> MS TechNet (DNS Crypt only). This is one of the many dengerous unsafe things causing huge DNS leaks. Anyway, after all secure settings I can made, I have: 'Internal DNS client enabled: false' in my browsers hidden settings, but "Simlpe DNSCrypt" still can't blocking domains...

I don't know what to think... May be, until next OS installation (some day, in the future).
I clearly understand, that you can't see and troubleshoot someone unknown network. Just reporting, you look at this blocking plugin one more time... I wish it work as solid as main functions.

(Sorry for my English)

**Comment by bitbeans** [comment]
@iWARR did you try it without Simple DNSCrypt? https://dnscrypt.org/ https://github.com/jedisct1/dnscrypt-proxy

**Comment by iWARR** [comment]
No, I didn't. (It was fast :) I will try. Of course, it will take some time to reinstall and test... Simple is very "simple", that means - handy :+1: I started my discovery from DNSCrypt long time ago, hope I will remember.

**Comment by jedisct1** [comment]
Also try resolving `resolver.dnscrypt.org` and check that the IP matches the IP of the resolver you chose.

Just to confirm that your DNS queries are actually going through the dnscrypt proxy.

**Comment by iWARR** [comment]
Yes, of course, IP matches in overall using and tests, as DNSCrypt was programmed. Except hidden DNS redirecting by Google during cross-link browsing, meaning - inside the browser itself. (But this is other subject to discuss).

**Comment by iWARR** [comment]
I'm happy you read my decent feedback notes. So I should write here one more thing.

I observed some difference in Log system behaviour. In the v0.4.3 domain names doesn't appear in Log window immediately after page refresh. May be it happens because it coming from the DNS cache? May be I'm wrong, but as I remember, in previous versions I saw log-input every time I refresh the page.

**Comment by iWARR** [comment]
And onr more thing. After fresh install of v0.4.3 I had the same trouble as described here:
**Simple DNSCrypt 0.4.3 (x64): info about the resolvers issue** https://github.com/bitbeans/SimpleDnsCrypt/issues/159
But after some time the problem was gone and now I can see ping time in the both resolver lists without any issues. Everything now is OK. As I remember, at this time I updated my .NET Framework installation to v4.7.2, nothing more. (And not for fixing this bug exactly). May be, it's just coincidence. So...

**Comment by iWARR** [comment]
Hi

Original "DNSCrypt" blocking works in my system. I've done setup with *.conf files and two services (Primary & Secondary) running successfully. Options, plugins and logs are working. I don't know why "Simple DNSCript" blocking fails...

Besides, I have an idea how to improve other experience of your great "Simple DNSCript" GUI.

	1) Lack of super-handy separate file "Restricted.log" (ON/OFF - if I want to collect info during the some period or to be sure my blocking rules works)

	2) Would be much more handy to have only one option for turning-on Logging instead two places (Plugins Tab + Log slider in another Tab). Too long and too much unwanted clicks.
	    Logging plug-in have to turn-on/off automatically, when Log slider turning ON/OFF in the Logging Tab (I want this place be the only one to operate within logs)

	3) Why *.yaml files have different format `- Rule: '...'` ? All this extra letters make blocking rules editing longer and may cause slips. Original format is simple and more handy.

-----------------------------------
Globally about "DNSCrypt":

It's unclear for me, why "DNSCrypt" uses 127.0.0.1 (by default), but not any other local address (127.0.0.11 + 127.0.0.12, for example; they working good for me) and mixes proxy with system "localhost" entry?
Some people reported that they have leaks of the blocked addresses from the hosts file. Don't know is it really true... But I've read about this. May be this "mix" has made leaks and also made useless my blocking rules before?

Furthermore, there may existing another blocking trick in the system with Network adapter, when Static route entries are in use for blocking some unwanted IPs with localhost address.

And OS or programs widely use "localhost" for their needs in the different places. 

Firewall logs also more informative, when you see what goes to Internet through the DNSCrypt (127.0.0.11, 127.0.0.12) and what goes to block (127.0.0.1 or 0.0.0.0).

It's just a question, I want to understand better.
