### ISSUE TITLE
There is no change

### ISSUE THREAD

**Issue by stonedreamforest** [bitbeans/SimpleDnsCrypt#149]
![2017-07-09_11-50-30](https://user-images.githubusercontent.com/16742566/27991048-fe722b88-649c-11e7-8100-ddee09e3723d.gif)

**Comment by benyaminl** [comment]
@stonedreamforest You should click the one above, the grey button, so I will be green and have check mark for it. Like this. 
![image](https://user-images.githubusercontent.com/2817332/28048856-d7b9bf1a-661d-11e7-9f59-37cfcf8b995c.png)
to this 
![image](https://user-images.githubusercontent.com/2817332/28048861-df14f4b4-661d-11e7-9710-2714d9f5c3bd.png)
You could try that. Please read the documentation first before opening any tickets here. Thanks

**Comment by stonedreamforest** [comment]
:+1:
