### ISSUE TITLE
Refresh resolver list

### ISSUE THREAD

**Issue by ganch0** [bitbeans/SimpleDnsCrypt#15]
Nice job you are doing!

I can't wait for the Secondary resolver support and IPv6 support features!

Also is it possible the resolver list do be automatically downloaded everytime Simple DNSCrypt is run, because right now, when I download it, I need to restart the program so that the new resolvers appear in the dropdown menu
.
Thank you for your efforts!

**Comment by bitbeans** [comment]
as soon @jedisct1 updates the main app (https://github.com/jedisct1/dnscrypt-proxy) i will add the support for the secondary resolver.

So you need to re-download the resolver list every time?

**Comment by ganch0** [comment]
Thanks, that's great!

When I startup Simple DNSCrypt I do have the list of resolvers loaded, however they are outdated. When I go to Advanced Settings an hit "download list" and then close the application and open it up again, then the list is updated with the latest list. It would be nice if the program loads up the updated list automatically on startup.

Thank you again!
