### ISSUE TITLE
Continued compliance with the HSTS preload requirements.

### ISSUE THREAD

**Issue by bardiharborow** [bitbeans/SimpleDnsCrypt#150]
Hey! `simplednscrypt.org` is currently HSTS preloaded, but has not continued to remain compliant with the [preload requirements](https://hstspreload.org/). If you are able to remedy this, it would be highly appreciated. This will ensure that if Chrome begins delisting non-compliant domains that yours will not be affected. Over at [EFForg/https-everywhere](https://github.com/EFForg/https-everywhere), we can't remove rewrite rules for domains that are non-compliant because that would present a security risk if Chrome then also removes them. Your domain is one of hundreds of non-compliant domains which add unnecessary maintenance and file size to our rulesets. Any assistance you can provide is appreciated.

**Comment by bitbeans** [comment]
Thanks!

> max-age=31536000; includeSubdomains; preload
