### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by D0ve** [bitbeans/SimpleDnsCrypt#151]
Please! I hope that an Android version of SDC will be very useful !
thank you so much in advance!

**Comment by CHEF-KOCH** [comment]
There is already an official [Android flashable .zip file](https://download.dnscrypt.org/dnscrypt-proxy/dnscrypt-proxy-android-armv7-a-1.9.4.zip).

**Comment by D0ve** [comment]
Your'e a bit wrong((( , that's a server only...It needs other Android apps((
My request is about a client ,SDC for Android!!!
So with that proxy it will be the ONE!

**Comment by bitbeans** [comment]
@D0ve sorry but Simple DNSCrypt is only for Windows. :)

**Comment by D0ve** [comment]
@bitbeans
But isn't really exist any/some .NET compillers for Android?
