### ISSUE TITLE
S-DNS stops working after antivirus uninstall

### ISSUE THREAD

**Issue by WalkerTXR** [bitbeans/SimpleDnsCrypt#153]
I installed Simple DNS on my new W10 laptop and it worked flawlessly. At the end of last month, the trial period for the antivirus software that came with the computer (McAfee) ran out. I uninstalled it as I planned on installing a different antivirus of my own. Ever since that day, Simple DNS will not work properly. It will connect, and can download updates; but if I have it turned on (green check lit up) then Firefox will not find/connect to any site. As soon as I click the green box to turn it off it will instantly be able to find sites again. I've added the SimpleDnsCrypt exe to my firewall just in case that was the issue, but no joy. Today I did an uninstall and reinstall and it still has the same issue. Any suggestions or setting I'm overlooking? Thanks in advance for any help you can provide to get it working again :)

**Comment by CHEF-KOCH** [comment]
Which av?
Did you tried certmgr.msc and checked that there is no special certificate which got installed by the AV is removed?
Did you checked (manually) that 127.0.0.1 is set?
