### ISSUE TITLE
[Feature Request] Option to export/import rules

### ISSUE THREAD

**Issue by CHEF-KOCH** [bitbeans/SimpleDnsCrypt#154]
I'm looking for an easy option to import/export the blocklist domains/IP's for the case you re-install Simple DNSCrypt. 

Perfect would be .cve or/and .txt format to integrate it with/from uBlock/HOSTS which means one entry per line.

**Comment by rddim** [comment]
Look in `C:\Program Files (x86)\bitbeans\Simple DNSCrypt\data` or `C:\Program Files\bitbeans\Simple DNSCrypt\data`

**Comment by CHEF-KOCH** [comment]
Actually I backup the entire bitbeans folder, but that's an workaround. Anyway thanks, I hope this helps others too.

**Comment by alexeytcherniak** [comment]
Why in the latest release (0.4.8) the "Domain Blacklist" feature is completely disabled? It seems now there is no way to define blacklists at all? Is it by design? It was very useful feature!

**Comment by CHEF-KOCH** [comment]
@alexeytcherniak 

Some features are disabled or non-functional because it's still in beta even if it says 'release'. The new domain blacklist feature can also now manually added by simple opening the blacklist.txt and add the domains you want into it, there is also the possibilities to do this with IP's only.

On the right side of this issue ticket you also see a 'Milestone' it's on the list for v0.5.0. Just give it time till all changes are merged into SimpleDNSCrypt.

**Comment by bitbeans** [comment]
will be implemented in 0.4.9
