### ISSUE TITLE
Save local address settings

### ISSUE THREAD

**Issue by ZIEXED** [bitbeans/SimpleDnsCrypt#155]
Every time you change the resolver from the list the local address port reset to 53
Every time I have to test a server or change the server!

also don't make the app apply changes to the server inistantly when u change the server from the list
instead add "apply" button
this is a simple request but it's very important as the current behavior is very annoying

**Comment by bitbeans** [comment]
![save](https://user-images.githubusercontent.com/1482102/31863618-1cb88df2-b750-11e7-97cc-3d7ba88b65bf.PNG)
