### ISSUE TITLE
There is a problem with this Windows Installer package.

### ISSUE THREAD

**Issue by 4DEATH** [bitbeans/SimpleDnsCrypt#157]
https://i.imgur.com/Thvgpmg.png

```
Product: Simple DNSCrypt -- Error 1721. There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor. Action: Uninstall.exe, location: C:\Program Files (x86)\bitbeans\Simple 
DNSCrypt\Uninstall.exe, command: C:\Program Files (x86)\bitbeans\Simple DNSCrypt\Uninstall.exe 

```

Windows 10 ver 1511 10586.1106
.NET 4.6 and Visual C++ Redistributable for Visual Studio 2015 x86 installed.

I had a previous version installed that had same error when trying to uninstall, so i uninstalled it manually.

**Comment by bitbeans** [comment]
@4DEATH  Please try the newest installer, thank you
