### ISSUE TITLE
FreeTSA Missing

### ISSUE THREAD

**Issue by war59312** [bitbeans/SimpleDnsCrypt#158]
Hi,

Not sure when it happened, but FreeTSA is now missing in the official release.

I see it's added back like 20 days ago here:

https://github.com/bitbeans/SimpleDnsCrypt/commit/5a6d7cfc1d32a69180900cbbafa0cb91b8ba7d24

New release to fix this?

Edit: Guess because no longer listed @ https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv

Edit 2: I see now: https://github.com/jedisct1/dnscrypt-proxy/commit/302860b2cbc5441bf749ab366c880307037b019f#diff-bc41fce4beb60b51d3b36a920e4b3a9a

But seems it's back up and working fine again.

Thanks,

Will

**Comment by bitbeans** [comment]
@war59312 dnscrypt-resolvers.csv is not maintained in this project :)
