### ISSUE TITLE
Simple DNSCrypt 0.4.3 (x64): info about the resolvers issue

### ISSUE THREAD

**Issue by ballios** [bitbeans/SimpleDnsCrypt#159]
In a new Simple DNSCrypt 0.4.3 (x64) pushing on a button "Get some extra info about the resolvers" makes any actions - Resolver list starts to be empty and any Resolver's servers can't be selected. This issue continues until I manually refresh the public resolver list...

And even after that - the problem continues!

Please fix this issue as soon as possible.

**Comment by bitbeans** [comment]
@ballios what windows version are you using? I can`t reproduce this on 2 windows 10 machines.

**Comment by ballios** [comment]
@bitbeans I use Windows 10 (x64) 1703 build 15063.674

**Comment by bitbeans** [comment]
@ballios can you try to deinstall and then reinstall? Maybe try the x86 version, but i don`t think there is a difference.

All other features are working like expected?

**Comment by ballios** [comment]
@bitbeans I did it. And x86 - the same situation. Yes, all other features are working like expected.

**Comment by ballios** [comment]
@bitbeans I've tested this situation on other computer with Win 10 - the same bug.

**Comment by bitbeans** [comment]
@ballios i found a old test project: https://github.com/bitbeans/dnscrypt-measurement can you test it?

**Comment by ballios** [comment]
@bitbeans I just installed the all new Windows 10 (Fall Creators) and was surprised to find that Simple DNSCrypt 0.4.3 (x64) is working without any visible bugs...
I don't know what does it all mean... Sorry.

**Comment by bitbeans** [comment]
@ballios nice to hear, it`s fixed.
Maybe somebody else can reproduce this behavior on Windows 10 1703?

**Comment by oferz** [comment]
I have the same issue on Windows 10 1703 x64. Would you like me to test something?
