### ISSUE TITLE
Fix "The Windows 10 Universal CRT" message on Windows 10

### ISSUE THREAD

**Issue by bitbeans** [bitbeans/SimpleDnsCrypt#160]

**Comment by jushur** [comment]
I solved this by installing following (seems one needs the x86 also on a 64bit system).

https://www.visualstudio.com/downloads/#microsoft-visual-c-redistributable-for-visual-studio-2017
https://go.microsoft.com/fwlink/?LinkId=746572 x64
https://go.microsoft.com/fwlink/?LinkId=746571 x86

I belive this should be considered a bug in Windows10, as this support should be present in a default install of Windows 10.
But that is not the case.

**Comment by bitbeans** [comment]
Fixed in: https://github.com/bitbeans/SimpleDnsCrypt/commit/fa48e33e64ccdea6bb36f39033388ff0f916ae04
