### ISSUE TITLE
Pressing clock icon depopulates resolver lists

### ISSUE THREAD

**Issue by rmcohen3** [bitbeans/SimpleDnsCrypt#167]
Since upgrading to version 0.43, I noticed this issue. I tried both the x86 and x64 versions .

**Comment by bitbeans** [comment]
ref: https://github.com/bitbeans/SimpleDnsCrypt/issues/159

**Comment by bitbeans** [comment]
@rmcohen3 can you test this: https://github.com/bitbeans/dnscrypt-measurement please?
Any special Antivirus software or something installed?

**Comment by nikw92** [comment]
I am facing the same issue on Windows 7 64-Bit.

**Comment by nikw92** [comment]
Output of test as mentioned. I have Symantec Endpoint Protection 12.1.6 installed and it did block `dnscrypt-measurement.exe` when first executed but after whitelisting the file, everything went fine. However, the issue still persists in SimpleDnsCrypt. Note that the resolvers list used is the latest one from [here](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv)

```C:\> dnscrypt-measurement.exe -n -d -l=dnscrypt-resolvers.csv
=====================================
36 Resolvers (fastest first)
Only DNSSEC: True
Only NoLogs: True
Only IPv4: true
=====================================
18 ms, Anatomical DNS, NoLogs: True, DNSSEC: True
18 ms, D0wn Resolver United States of America 02, NoLogs: True, DNSSEC: True
74 ms, D0wn Resolver Mexico 01, NoLogs: True, DNSSEC: True
82 ms, D0wn Resolver United States of America 04, NoLogs: True, DNSSEC: True
92 ms, D0wn Resolver Netherlands 04, NoLogs: True, DNSSEC: True
96 ms, D0wn Resolver France 02, NoLogs: True, DNSSEC: True
99 ms, DNSCrypt.eu Holland, NoLogs: True, DNSSEC: True
100 ms, D0wn Resolver Netherlands Random 02, NoLogs: True, DNSSEC: True
101 ms, DNSCrypt.nl The Netherlands (NL), NoLogs: True, DNSSEC: True
106 ms, D0wn Resolver Greece 01, NoLogs: True, DNSSEC: True
107 ms, DNSCrypt.org France, NoLogs: True, DNSSEC: True
109 ms, DNSCrypt.eu Denmark, NoLogs: True, DNSSEC: True
110 ms, Ipredator.se Server, NoLogs: True, DNSSEC: True
115 ms, D0wn Resolver Sweden 02, NoLogs: True, DNSSEC: True
121 ms, D0wn Resolver Latvia 02, NoLogs: True, DNSSEC: True
124 ms, D0wn Resolver Iceland 01, NoLogs: True, DNSSEC: True
128 ms, D0wn Resolver Sweden 01, NoLogs: True, DNSSEC: True
131 ms, D0wn Resolver Russia 01, NoLogs: True, DNSSEC: True
131 ms, D0wn Resolver Latvia 01, NoLogs: True, DNSSEC: True
137 ms, ns0.dnscrypt.is in Reykjavík, Iceland, NoLogs: True, DNSSEC: True
139 ms, D0wn Resolver Iceland 02, NoLogs: True, DNSSEC: True
148 ms, D0wn Resolver Spain 01, NoLogs: True, DNSSEC: True
150 ms, D0wn Resolver Austria 01, NoLogs: True, DNSSEC: True
231 ms, D0wn Resolver Tanzania 01, NoLogs: True, DNSSEC: True
251 ms, D0wn Resolver Indonesia 01, NoLogs: True, DNSSEC: True
259 ms, D0wn Resolver Singapore 01, NoLogs: True, DNSSEC: True
266 ms, D0wn Resolver South Africa 01, NoLogs: True, DNSSEC: True

**Comment by rmcohen3** [comment]
I am running Comodo Internet Security Premium 10.0.1.6294. It did not complain when I first ran the resolvers utility. Here is the output I received:

D:\dnscrypt-measurement>dnscrypt-measurement.exe -l=dnscrypt-resolvers.csv
=====================================
56 Resolvers (fastest first)
Only DNSSEC: False
Only NoLogs: False
Only IPv4: true
=====================================
25 ms, Cisco OpenDNS with FamilyShield, NoLogs: False, DNSSEC: False
27 ms, CS Chicago IL US DNSCrypt server, NoLogs: True, DNSSEC: False
31 ms, Anatomical DNS, NoLogs: True, DNSSEC: True
35 ms, Cisco OpenDNS, NoLogs: False, DNSSEC: False
43 ms, CS New York City NY US DNSCrypt server, NoLogs: True, DNSSEC: False
44 ms, CS Atlanta GA US DNSCrypt server, NoLogs: True, DNSSEC: False
67 ms, CS Dallas TX US DNSCrypt server, NoLogs: True, DNSSEC: False
99 ms, D0wn Resolver France 02, NoLogs: True, DNSSEC: False
99 ms, okTurtles, NoLogs: True, DNSSEC: False
119 ms, D0wn Resolver Netherlands 02, NoLogs: True, DNSSEC: False
120 ms, CS secondary France DNSCrypt server, NoLogs: True, DNSSEC: False
120 ms, DNSCrypt.eu Holland, NoLogs: True, DNSSEC: True
125 ms, CS Switzerland DNSCrypt server, NoLogs: True, DNSSEC: False
134 ms, DNSCrypt.org France, NoLogs: True, DNSSEC: True
135 ms, CS cryptofree France DNSCrypt server, NoLogs: True, DNSSEC: False
150 ms, DNSCrypt.eu Denmark, NoLogs: True, DNSSEC: True
154 ms, D0wn Resolver Iceland 01, NoLogs: True, DNSSEC: False
158 ms, Ipredator.se Server, NoLogs: True, DNSSEC: True
158 ms, D0wn Resolver Sweden 01, NoLogs: True, DNSSEC: False
159 ms, ns0.dnscrypt.is in Reykjavík, Iceland, NoLogs: True, DNSSEC: True
162 ms, D0wn Resolver Latvia 02, NoLogs: True, DNSSEC: False
171 ms, D0wn Resolver Latvia 01, NoLogs: True, DNSSEC: False
174 ms, D0wn Resolver Russia 01, NoLogs: True, DNSSEC: False
196 ms, D0wn Resolver Spain 01- d0wn, NoLogs: True, DNSSEC: False
253 ms, D0wn Resolver Tanzania 01, NoLogs: True, DNSSEC: False
270 ms, D0wn Resolver Singapore 01, NoLogs: True, DNSSEC: False
302 ms, D0wn Resolver Indonesia 01, NoLogs: True, DNSSEC: False

**Comment by bitbeans** [comment]
I currently can`t reproduce the problem on my systems. But there is definitly a problem, as 4 people reported this to me now. I will check this :)

**Comment by oferz** [comment]
I ran it through VS 2017 and found it causes an exception in AnalyseProxy.cs on line 58 (var response = await request.Resolve();).
The exception thrown is: 
`System.MissingMethodException: Method not found: 'System.Reflection.FieldInfo[] System.Reflection.TypeExtensions.GetFields(System.Type, System.Reflection.BindingFlags)'.
   at DNS.Protocol.Marshalling.Struct.ConvertEndian[T](Byte[] data)
   at DNS.Protocol.Marshalling.Struct.GetBytes[T](T obj)
   at DNS.Protocol.Header.ToArray()
   at DNS.Protocol.Request.ToArray()
   at DNS.Client.ClientRequest.ToArray()
   at DNS.Client.RequestResolver.UdpRequestResolver.<Request>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DNS.Client.ClientRequest.<Resolve>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskA
waiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SimpleDnsCrypt.Tools.AnalyseProxy.<Analyse>d__0.MoveNext() in D:\\Users\\....\\Documents\\Visual Studio 2017\\Projects\\SimpleDnsCrypt\\SimpleDnsCrypt\\Tools\\AnalyseProxy.cs:line 58`

If I execute request.Resolve(); in the immediate window, I get this:
`request.Resolve()
Exception thrown: 'System.MissingMethodException' in DNS
Exception thrown: 'System.MissingMethodException' in mscorlib.dll
Id = 4283, Status = Faulted, Method = "{null}", Result = "{Not yet computed}"
    AsyncState: null
    CancellationPending: false
    CreationOptions: None
    Exception: Count = 1
    Id: 4283
    Result: null
    Status: Faulted`

I hope this helps. When I get some more time, I'll try to look into this further.

Cheers,
o

**Comment by bitbeans** [comment]
@oferz thank you, it seems there is a problem with finding the correct assemblies.

**Comment by bitbeans** [comment]
@rmcohen3  @nikw92 @oferz it may take some time, but for the next release i will publish a pre-release version :)

**Comment by Shir01** [comment]
I can confirm this bug, and the solution for me was installing .NET 4.7.1. 

My OS is Windows 7 SP1 x64.

**Comment by rmcohen3** [comment]
Yes, I can also confirm that installing .NET 4.7.1 resolved the problem for me as well.

**Comment by nikw92** [comment]
Thanks for reporting the solution @Shir01 . Installing the latest .NET framework (v 4.7.1) does indeed solve the problem.
