### ISSUE TITLE
Forwarding option will not stick

### ISSUE THREAD

**Issue by justinemerson** [bitbeans/SimpleDnsCrypt#169]
I cannot get forwarding under plugins to work. Every time I save the configuration it reverts back to blank, and the slider is to the left (off position).
Win10 x64, using latest version 0.4.3

**Comment by KakersUK** [comment]
I seem to be experiencing the same problem. Sometimes I can get it to save and other times I can't.

Domains will only save and update if I change the resolvers which won't save but instead revert back to their previous setting. Similarly I've managed to update the resolver but only by making a change to the domains which sometimes also revert back.

Trying multiple combinations, it seems completely random whether or not you can get the values to save or not.

Also Windows 10 x64 tested using the x86 and x64 Simple DNSCrypt 0.4.3

**Comment by bitbeans** [comment]
Thanks for reporting, i will check this.
