### ISSUE TITLE
Option to define Fallback Resolvers

### ISSUE THREAD

**Issue by bitbeans** [bitbeans/SimpleDnsCrypt#170]
As soon as both resolvers have been deactivated, it should be possible to define automatic fallback resolvers.
- OpenDNS (208.67.222.222; 208.67.220.220)
- Google (8.8.8.8; 8.8.4.4)

**Comment by TroudhuK** [comment]
DNS of societies which spy us?

**Comment by jedisct1** [comment]
Not a big fan of this either. But the only reliable alternative would be to run a local resolver.
