### ISSUE TITLE
v0.4.3: DNSCrypt Services disconnected too often

### ISSUE THREAD

**Issue by ballios** [bitbeans/SimpleDnsCrypt#171]
I have the last Win 10 (1709).

Primary and Secondary DNSCrypt Services disconnected too often after Win shutted down and starts after...

In Windows Services: 
- dnscrypt-proxy and dnscrypt-proxy-secondary are always unchanged by me = Running/Automatic
But - disconnected too often after Win shutted down and starts after...

I don't know why this happening and why I must start those Primary and Secondary DNSCrypt Services' selectors manually too often?

![faststoneeditor1](https://user-images.githubusercontent.com/19872946/32332087-3ea7b46a-bfed-11e7-96ae-901829b8df68.jpg)

**Comment by bitbeans** [comment]
will be fixed in new release
