### ISSUE TITLE
0.4.3 Erases proxy list when "Get some extra info about theh resolvers"

### ISSUE THREAD

**Issue by exec228** [bitbeans/SimpleDnsCrypt#173]
Hello!

Actions:
1) Start SimpleDnsCrypt.exe 0.4.3 (Windows 8.1x64, Wi-Fi)
2) Advanced settings\downloadlist = I download a fresh list of proxies
3) Standard settings\Get some extra info about the resolvers = 0.4.3 erases the list of proxies, combo-box of proxies becomes empty.
Reproduced with both msi and portable.

Expected behaviour, as in 0.4.2:
3) Standard settings\Get some extra info about the resolvers = 0.4.2 pings all of servers and returns ping times into combo-box.

**Comment by bitbeans** [comment]
Duplicate: #167 :)
