### ISSUE TITLE
Not Resolving. Again!

### ISSUE THREAD

**Issue by robin98** [bitbeans/SimpleDnsCrypt#177]
Hello;
The new version, as i described for older version, after restart, sleep or shutdown, can't resolve.
we must go to the windows services and 'restart' both dnscrypt services manually to back them again.
I got this problem before, in my windows 10, but i now use windows 7.i'm sure this is your fault.

**Comment by porsche613** [comment]
Well, maybe the dnscrypt-proxy services doesn't start automatically, which were disabled or disturbed by some software you installed and used. 

I have not meet this issues, which I use it for a long time on several computers (including Windows 10/8.1/7 x64). However, I have tested that VMWare Bridge Protocol is considered as a incompatible reason: [Connection issuse with VMWare Bridge Protocol enabled](https://github.com/shadowsocks/shadowsocks-windows/issues/1140) my be it can be helpful for you.
