### ISSUE TITLE
Specify custom DNSCrypt resolvers

### ISSUE THREAD

**Issue by Jan02** [bitbeans/SimpleDnsCrypt#18]
Allow user to specify custom resolvers

**Comment by squirrelboot** [comment]
I want to second this. For instance, why is DNS.WATCH not on the list?

**Comment by bitbeans** [comment]
Is dns.watch using dnscrypt?
Only resolvers in [this](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv) csv file are on the list:

**Comment by SquirrelCoder** [comment]
I set up my own resolver, and I wanted to know, if is it possible to add my own server to the available options? (My resolve is not on the official list!).

Thanks

**Comment by bitbeans** [comment]
@SquirrelCoder not **at the moment**. Simple DnsCrypt uses a hard coded public key to verify the .csv file. The only person who can add a resolver is jedisct1, because he has the private key to sign.

**Comment by meiskam** [comment]
is this wontfix? how do i connect to a custom resolver?
