### ISSUE TITLE
Live log keeps logging entries even though it's disabled

### ISSUE THREAD

**Issue by mr-brunes** [bitbeans/SimpleDnsCrypt#182]
Hi

After enabling SimpleDNS Live Log initially to help debug things, I then disabled it, but today I've noticed that the log file is being written to. SimpleDNS (0.4.3 x64) says that the number of Entries is 0, but this is clearly incorrect.
Is this a known issue?

**Comment by skwerlman** [comment]
In order to enable the live log, you needed to enable the logging plugin. Just disabling the live log will not also disable the logging plugin, which is why the file is still being written to.

**Comment by mr-brunes** [comment]
Thanks. Only just seen the reply to this - missed it somehow.

"Just disabling the live log will not also disable the logging plugin,"
So this then begs the question as to what does disabling the Live Log (feature) actually do?

One issue is certain - the Entries in LiveLog count of zero is wrong.
