### ISSUE TITLE
Resolver list moved to its own repo

### ISSUE THREAD

**Issue by licaon-kter** [bitbeans/SimpleDnsCrypt#186]
https://github.com/jedisct1/dnscrypt-resolvers

**Comment by bitbeans** [comment]
i will bring an update soon

**Comment by jedisct1** [comment]
I'm entirely guilty :(

Thought clients were not directly fetching these files from Github, and I didn't even check SimpleDNSCrypt :(

**Comment by licaon-kter** [comment]
I should have made a PR directly though :)
Thanks
