### ISSUE TITLE
No longer able to refresh public resolver list.

### ISSUE THREAD

**Issue by Rubber-Duckie** [bitbeans/SimpleDnsCrypt#188]
The resolver list was moved to; https://github.com/jedisct1/dnscrypt-resolvers/blob/master/v1/dnscrypt-resolvers.csv

This has broken the latest client. Consider placing this URL in the app config and surfacing it in the UI. Better error handling / messages would be useful here.

**Comment by bitbeans** [comment]
see #186 

👍
