### ISSUE TITLE
Simple DNSCrypt suddenly stopped working

### ISSUE THREAD

**Issue by n31n** [bitbeans/SimpleDnsCrypt#19]
First of all, THANK YOU, for creating a much more simple to use interface for DNScrypt.
I have been using the older versions for years now and have been hoping someone would make this more practical for the average person to use.

Installed on a clients computer, things worked fine for a few weeks.
He reported to me no internet access, after walking him though a few simple things, he returned the computer to me for maintenance.

After uninstalling then reinstalling simplednscrypt, I noticed that the dns proxy was set to 127.0.0.2. After I set it to .1, all was fine again... fyi.

Thank you again.

**Comment by bitbeans** [comment]
@n31n does 0.2.9 fix this issue?

**Comment by n31n** [comment]
I have not seen the issue since the update. I will report it if it occurs
again.

Thank you.

On Mon, Dec 28, 2015 at 12:34 AM, Christian Hermann <
notifications@github.com> wrote:

> @n31n <https://github.com/n31n> does 0.2.9 fix this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitbeans/SimpleDnsCrypt/issues/19#issuecomment-167489370>
> .
>



-- 

PikesvillePC.com





This email may contain privileged and/or confidential information that is
intended solely for the use of the addressee.  If you are not the intended
recipient or entity, you are strictly prohibited from disclosing, copying,
distributing or using any of the information contained in the
transmission.  If you received this communication in error, please contact
the sender immediately and destroy the material in its entirety, whether
electronic or hard copy.

**Comment by n31n** [comment]
I have noticed that the new version needs microsoft c++ redistributable. Is
it possible to bundle this with the new version of dnscrypt?


On Mon, Dec 28, 2015 at 7:14 AM, Christian Hermann <notifications@github.com
> wrote:

> Closed #19 <https://github.com/bitbeans/SimpleDnsCrypt/issues/19>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitbeans/SimpleDnsCrypt/issues/19#event-501290515>.
>



-- 

PikesvillePC.com





This email may contain privileged and/or confidential information that is
intended solely for the use of the addressee.  If you are not the intended
recipient or entity, you are strictly prohibited from disclosing, copying,
distributing or using any of the information contained in the
transmission.  If you received this communication in error, please contact
the sender immediately and destroy the material in its entirety, whether
electronic or hard copy.

**Comment by bitbeans** [comment]
@n31n i could include the package into the next installer (web install).

**Comment by n31n** [comment]
May I make another suggestion?

Have simple dnscrypt check the resolver to see if it is active/responding,
if not, simple dnscrypt should switch over to a secondary resolver that the
user has chosen.

Thank you again.

If you ever need specific testing I am willing to help in any way I can. I
am a tech, but not a programmer.



On Wed, Dec 30, 2015 at 12:44 AM, Christian Hermann <
notifications@github.com> wrote:

> @n31n <https://github.com/n31n> i could include the package into the next
> installer (web install).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitbeans/SimpleDnsCrypt/issues/19#issuecomment-167940810>
> .
>



-- 

PikesvillePC.com





This email may contain privileged and/or confidential information that is
intended solely for the use of the addressee.  If you are not the intended
recipient or entity, you are strictly prohibited from disclosing, copying,
distributing or using any of the information contained in the
transmission.  If you received this communication in error, please contact
the sender immediately and destroy the material in its entirety, whether
electronic or hard copy.
