### ISSUE TITLE
No internet when using simplednscrypt

### ISSUE THREAD

**Issue by knifenblood** [bitbeans/SimpleDnsCrypt#191]
No internet when using simplednscrypt...
Attached screenshot of settings

https://i.imgur.com/BvUXPag.jpg

Is there anything else I need to do after selecting network cards?

**Comment by knifenblood** [comment]
Bump

**Comment by slyphnier** [comment]
what connection u use ? wifi only ? 
anyway just to be sure just check for all connection lan - wifi- bluetooth

also click on the clock 
it will do ping, it will take few minutes... you will know it still pinging if you cant select any resolver
after the ping done, it will give sorted list resolver based lantecy 
pick the shortest one... 

last just to make sure
enable both primary and secondary service on bottom
