### ISSUE TITLE
Thanks for wasting 2 hours of my time...

### ISSUE THREAD

**Issue by crapsoftwareabounds** [bitbeans/SimpleDnsCrypt#193]
Just installed your bs program under regular non virtual win7 box (fully updated).

Then I have to install your crippleware patch c runtime update.

your stupid program cannot find installed c runtime update even though it says installed.

why you waste peoples' time debugging your script kiddie programs? Come back when you learn how
to code. Thanks!

**Comment by evilvibes** [comment]
@crapsoftwareabounds We will wait here for a better program from you

**Comment by jedisct1** [comment]
Thank you for your gratitude to people who wasted way more than 2 hours of their life to work on free software, just to read anonymous comments like this.
