### ISSUE TITLE
failed to refresh public resolver list

### ISSUE THREAD

**Issue by slyphnier** [bitbeans/SimpleDnsCrypt#194]
not sure if ISP blocking out or some section removed or other else
but the latest refresh that still work is on 6th january 2018 

just now i tried and it keep failing, even i tried to refresh with VPN
also i check this direct link for resolver :  
https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv
it give me 404 error 

am i the only one effected by this issue ? or anyone also getting same issue?
anyway hope this issue is just temporary

**Comment by rmcohen3** [comment]
I am experiencing this issue as well. It has been happening for a few days now. I just tried to uninstall and re-install Simple DNSCrypt (0.43, (x64)), but it did not help. And, to make matters worse, my public resolver list is now the old one (Oct-22-2017) from the install file.

**Comment by ChaseGrant** [comment]
This appears to be a result of the GIT repo for the DNSCrypt proxy being completely wiped and restarted.

**Comment by skapytek** [comment]
How can i use the edisct1/dnscrypt-proxy?
Doubleclick on it wont do anything.

regards

**Comment by skapytek** [comment]
Any infos or updates about this?

**Comment by arif-excell** [comment]
@ChaseGrant was right
Looks like the url of the public resolver list is changed, there is /v1/ on the url right now. And ATM the last update is 1st or 2nd Januari.
Refer to this : https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v1/dnscrypt-resolvers.csv

**Comment by ChaseGrant** [comment]
Yep. Actually they seem to have moved it out to a completely different repo.
SimpleDnsCrypt will probably need an update to use the new URL unless they convert to the new DNSProxy.

**Comment by bitbeans** [comment]
will be fixed in new release
