### ISSUE TITLE
[Feature Request] DNSCrypt v2 Support

### ISSUE THREAD

**Issue by zero77** [bitbeans/SimpleDnsCrypt#195]
Can you please consider supporting the DNSCrypt v2 protocol alongside or instead of the old DNSCrypt. 

Thanks

https://github.com/jedisct1/dnscrypt-proxy

**Comment by bitbeans** [comment]
yes! :)

**Comment by bitbeans** [comment]
Hey Frank,

I need to take a closer look at this first. :)
In any case, there will be major changes ... I really like the new concept! 👍

The previous configuration was done via the Windows registry.
**I want to use the toml file in the future, too.**

Currently I don't see any (comfortable) way to determine the currently selected server (to show up in the UI).
But maybe this is no longer necessary?
e. g: If other parameters such as "UseDnsSecOnly" can be introduced to the toml?

**Comment by jedisct1** [comment]
Hi Christian,

In version 2, one can select one or more servers, or rather "candidates". It's totally fine to include unresponsive servers in the set.

You can even select no server at all, which stands for "all possible servers, from local and remote sources". In that case, you can add filters such as `require_dnssec`, `require_nolog`, `require_nofilter`, and there are 61 bits left for future filter attributes.

At startup time, the latency of each server is measured, and the fastest one becomes the "preferred" candidate for further queries. But the second fastest also occasionally gets a change to handle queries.

The RTT of all servers is constantly measured. If the preferred candidate becomes unresponsive or repeatedly becomes slower than another random candidate, these will be swapped. That's the idea. The current implementation is still a bit primitive, but there is no "currently selected server" any more. It's a set of candidates. Queries are dynamically routed to the responsive ones. And if a dead candidate suddenly becomes reachable, it will be added to the pool.

Maybe something that could help you for the GUI would be the ability to dump the current state: the list of active servers, sorted by preference, and a bunch of live statistics.

**Comment by bitbeans** [comment]
I missed require_dnssec, require_nolog and require_nofilter :)

**Comment by jedisct1** [comment]
Just also added the much required `ipv4_servers` and `ipv6_servers` boolean flags as well.

**Comment by KrasnayaPloshchad** [comment]
In dnscrypt-proxy 2.0.0beta10, I found the package including 3 batch files including some command lines you need to.

**Comment by jedisct1** [comment]
These batch files install and uninstall the service after requesting privilege elevation.

@bitbeans doens't need that, he can do way way way better :)

**Comment by bitbeans** [comment]
i will try :)

**Comment by jedisct1** [comment]
Wait, what, already?

https://github.com/bitbeans/SimpleDnsCrypt/releases

**Comment by bitbeans** [comment]
just to start the new translations :) hehe

**Comment by zero77** [comment]
Thanks
