### ISSUE TITLE
AppVeyor builds

### ISSUE THREAD

**Issue by rddim** [bitbeans/SimpleDnsCrypt#196]
Could you add please SimpleDnsCrypt to the [AppVeyor](https://appveyor.com)? The builds will be very helpfully for testing and for the translators. This will eliminate the needs for non-developers to install tons of Visual Studio just for compile and test. I added it for myself and it work very well.

**Comment by bitbeans** [comment]
@rddim (unsigned portable version)
https://simplednscrypt.blob.core.windows.net/deploy/SimpleDnsCrypt/bin/x86/SimpleDNSCrypt_x86.zip
https://simplednscrypt.blob.core.windows.net/deploy/SimpleDnsCrypt/bin/x64/SimpleDNSCrypt_x64.zip

**Comment by rddim** [comment]
Thank you very much :) Is there any easy way to add the already translated strings to POEditor? I see in Bulgarian (and not only) is added only translation for `Network Cards`.

**Comment by bitbeans** [comment]
I tried, but some keys have changed. And since I do not speak Bulgarian, I cannot complete it. Further new keys will be added. Sorry for now :(

**Comment by rddim** [comment]
Ok, I will complete it, thanks ;)
