### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [bitbeans/SimpleDnsCrypt#197]
Hi,
I'm small translator & i want translate this program into Arabic for free 
just to make program easy to use from Arab people who's not know English
thx

**Comment by EsmailELBoBDev2** [comment]
i hate .po files -_-, but i will wait :) (please when program ready to translate tell me here or on my e-mail: esmailelbob01124320019@gmail.com)

**Comment by EsmailELBoBDev2** [comment]
i got the invitation :D

**Comment by bitbeans** [comment]
@EsmailELBoBDev2 great! thank you

**Comment by EsmailELBoBDev2** [comment]
some words in red, that's mean ?

**Comment by bitbeans** [comment]
hmm never see nred words. maybe the tool does not know this word ... keep going .. :)

whats the correct language code for your translation? ar-AR? https://msdn.microsoft.com/en-us/library/ms533052(v=vs.85).aspx

**Comment by EsmailELBoBDev2** [comment]
yeah AR (59.38% in some minutes :) ) & i can add words (like flag) ?

**Comment by EsmailELBoBDev2** [comment]
1- I'm done :) ^_^

2- you can add this words with translate because i'm small translator
Text: Arabic Translation By: Esmail EL BoB | E-mail: esmailelbob01124320019@gmail.com | Report Wrong Translation: http://bit.ly/2EVnQWr

3- i know, you thinking why i adeed " Report Wrong Translation: http://bit.ly/2EVnQWr " i added it because i'm in 15y so i not know all English words & i'm sure i will find wrong words so i added this to make people help me ^_^

4- Thx a lot

**Comment by EsmailELBoBDev2** [comment]
i'm waiting your reply & when Arabic Translation will release in the program?

**Comment by bitbeans** [comment]
Thank you very much! It should already be included: https://simplednscrypt.blob.core.windows.net/deploy/SimpleDnsCrypt/bin/x64/SimpleDNSCrypt_x64.zip

**Comment by EsmailELBoBDev2** [comment]
where my name :( ?
![2018-01-27_072511](https://user-images.githubusercontent.com/28893833/35468983-46f8fb4a-0333-11e8-825f-503a2958bc11.png)

**Comment by EsmailELBoBDev2** [comment]
& you can my text with translation right?
*** Arabic Translation By: Esmail EL BoB | E-mail: esmailelbob01124320019@gmail.com | Report Wrong Translation: http://bit.ly/2EVnQWr***

**Comment by bitbeans** [comment]
@EsmailELBoBDev2 your name is there: https://github.com/bitbeans/SimpleDnsCrypt/blob/dnscrypt-proxy2/Contributors.md the **Translations** section in the README (master brunch) is not up-to-date.
An sorry, no bitly links in the README ... :)

**Comment by EsmailELBoBDev2** [comment]
will, thx a lot ^_^

**Comment by EsmailELBoBDev2** [comment]
will, my brain thinking in: you gave me a review version so when Arabic translation will come in public version ?

**Comment by bitbeans** [comment]
sure it will come in, as soon as its ready :)

**Comment by EsmailELBoBDev2** [comment]
^_^

**Comment by EsmailELBoBDev2** [comment]
i bet the whole project changed & you need new translation but sorry buddy (ik its already late xD) but yeah i not feel i wanna to translate this project now
