### ISSUE TITLE
Please make suitable for ".net 4.6.1" builds .net.4.6.2 not supported here

### ISSUE THREAD

**Issue by spamkutu** [bitbeans/SimpleDnsCrypt#200]
As title page show please make suitable for ".net 4.6.1" builds .net.4.6.2 not supported here.
atleast latest dot net 4.6.1 builds required thanks..

**Comment by bitbeans** [comment]
@spamkutu 

> net.4.6.2 not supported here

whats **here**? :)

**Comment by jedisct1** [comment]
![Here](https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ3OTcwNzEyOV5BMl5BanBnXkFtZTcwNzQzNDI2Nw@@._V1_SY1000_CR0,0,675,1000_AL_.jpg)

**Comment by bitbeans** [comment]
@jedisct1  lol

**Comment by spamkutu** [comment]
It's on windows 8. Windows 8 support up to 4.6.1 dont know why. Atleast show us a way to make exe for support net 4.6.1only thanks.

**Comment by bitbeans** [comment]
@spamkutu just try the alpha 3 release (it`s .net 4.6.1 at the moment)
