### ISSUE TITLE
Stamp Properties

### ISSUE THREAD

**Issue by bitbeans** [bitbeans/SimpleDnsCrypt#201]
@jedisct1 do you have some details on the stamp properties for me?
https://github.com/bitbeans/SimpleDnsCrypt/blob/2a978490945de4181b4958b5861c5adf2ed49a03/SimpleDnsCrypt/Models/Stamp.cs#L80-L95

**Comment by jedisct1** [comment]
Bit `0` means that DNSSEC is supported, bit `1` means nolog, bit `2` is reserved for nofilter.

And that's pretty much all for now. There are plenty of bits left for future use.

**Comment by bitbeans** [comment]
Thank you! :)
