### ISSUE TITLE
Testers

### ISSUE THREAD

**Issue by bitbeans** [bitbeans/SimpleDnsCrypt#202]
I need some brave testers: https://github.com/bitbeans/SimpleDnsCrypt/releases/download/0.4.5-alpha3/SimpleDNSCrypt64.msi

Feeback of any kind is welcome! :)

Thanks again to all translators!
https://poeditor.com/join/project/3frSzJtSqc

**Comment by evilvibes** [comment]
I can't seem to get DNScrypt service to start.

Windows 10 Home
Version 1709
Build 16299.192

**Comment by Sporif** [comment]
Works beautifully here. Can finally stop using powershell scripts :) One bug is that after using the remove service option in advanced settings it does not indicate that the services are removed.

**Comment by GRMansell** [comment]
Good here on win 10 1709 pro. I had to reinstall the 127.0.0.1 dns address. Will try soon on home edition.Not currently using ipv6, need to get back in that.
Thanks 

    On Thursday, February 1, 2018 6:19 PM, Sporif <notifications@github.com> wrote:
 

 Works beautifully here. Can finally stop using powershell scripts :) One bug is that after using the remove service option in advanced settings it does not indicate that the services are removed.—

**Comment by evilvibes** [comment]
DNScrypt service still will not start for me. Not sure what info i can share to help with this issue.

**Comment by bitbeans** [comment]
@evilvibes have you tried uninstalling an old version? also try to stop the service if it is already installed?
There is now also a log folder, is there an error log?

**Comment by evilvibes** [comment]
Yes i did tried all that been trying to get it to work for few days now. I'll have a look at the log folder now.

**Comment by evilvibes** [comment]
Well after all that i had to go into regedit and manually delete  HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\dnscrypt-proxy

I now have it running.

**Comment by n31n** [comment]
Running excellent here. Will have to evaluate in detail later. Thank you again for this Most Excellent project.

**Comment by evilvibes** [comment]
Yup no issues at all now that i have it running. Awesome work @jedisct1 & @bitbeans

**Comment by rmcohen3** [comment]
When browsing to web sites in Chrome, I frequently get an error name resolution failed message. However, if I wait a few seconds, it refreshes and the web page loads.

**Comment by medack** [comment]
Weirdly, with the stable 0.4.5 version (haven't tested the alphas, sorry), the dnscrypt-proxy service does not seem to get properly installed/registered here. I am unable to start the service and, contrarily to the previous 0.4.3 version, no dnscrypt-proxy services are present in the Windows Services list. Any clue? (I removed the older version before installing the 0.4.5, just to be sure.)

Also, you are probably aware of this, but some translation strings are still unavailable to be translated! Other than that, thank you for your work!

Windows 10 x64, v1709

**Comment by bitbeans** [comment]
@medack are there any logs? C:\Program Files\bitbeans\Simple DNSCrypt x64\logs

**Comment by alfazaki** [comment]
@medack i have the same problem with the stable version 0.4.5 in my windows 10 pc, can't find any log at program files either

**Comment by bitbeans** [comment]
@medack @alfazaki maybe you have the same problem as @evilvibes 

`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\dnscrypt-proxy`

**Comment by alfazaki** [comment]
@bitbeans thanks for your response, i tried @evilvibes tips delete 
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\dnscrypt-proxy

and to make sure i do it 2 times and tried to install/uninstall/restart pc
service still not running, everything normal in previous version, any other tips?

**Comment by bitbeans** [comment]
@alfazaki yes, open a shell and check the output of:
```
cd "C:\Program Files\bitbeans\Simple DNSCrypt x64\dnscrypt-proxy\"
.\dnscrypt-proxy.exe -service -install
```

**Comment by medack** [comment]
@bitbeans Yep, that done it, but with a small modification in your line:
dnscrypt-proxy.exe -service install

May be this is also wrong in the setup routine?

**Comment by bitbeans** [comment]
@medack was there an error in the output? hmm yes i will check this again later. 

this is the current uninstall: https://github.com/bitbeans/SimpleDnsCrypt/blob/master/Uninstall/Program.cs (any improvement is welcome) :)

**Comment by medack** [comment]
@bitbeans Yes, with the extra "-", got an "Unknown action" from the dnscrypt-proxy.

My programming skills are relatively limited, but I will take a look at it. Just a question: why do we have now that service uninstall option? Doesn't it make sense only when you uninstall Simple DnsCrypt?

**Comment by bitbeans** [comment]
@medack it`s not a new option: https://github.com/bitbeans/SimpleDnsCrypt/blob/master/img/old/advanced.png

**Comment by medack** [comment]
@bitbeans True! I guess I didn't need to tweak anything in SimpleDNSCrypt for so long that I forgot what the advanced options looked like. Anyway, just a heads-up: updated a few minutes ago to 0.4.7 and everything is working well so far. Fantastic work, thank you!
