### ISSUE TITLE
Live Log: show resolved IP

### ISSUE THREAD

**Issue by rkawulak** [bitbeans/SimpleDnsCrypt#205]
It would be useful if Live Log also contained a column showing the resolved IP for each entry.

**Comment by bitbeans** [comment]
@rkawulak only these lines are available: https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/plugin_query_log.go#L85

**Comment by jedisct1** [comment]
There can be many more than one IP address for a given name. Or none. Or a pointer to another name (`CNAME`). So, this is hard to represent in a flat log format, and generally not useful.
