### ISSUE TITLE
Multiplicated entries in Live Log when using ICS

### ISSUE THREAD

**Issue by rkawulak** [bitbeans/SimpleDnsCrypt#206]
If the DNSCrypt-enabled network connection is shared using Internet Connection Sharing and a DNS query is made by a machine using the shared connection, the query appears 10 times in Live Log.

**Comment by bitbeans** [comment]
@rkawulak if the query appears 10 times in the **dns.log** file, it will appear 10 times in the live log.
don`t think this is a problem with SimpleDnsCrypt
