### ISSUE TITLE
Globally obsolete URL links on your maintained sites related to DNSCcrypt.

### ISSUE THREAD

**Issue by Ricky-Tigg** [bitbeans/SimpleDnsCrypt#209]
Hello maintainer of project SimpleDnsCrypt. It is most welcome to see a similar project to the one maintained by F1ash and intended only for UNIX/Linux systems as a Qt/KF5 GUI wrapper over dnscrypt-proxy (https://github.com/F1ash/dnscrypt-proxy-gui). With all the reasons not to be interested in Windows systems but with all the reasons to be interested with that present project (https://github.com/bitbeans/SimpleDnsCrypt), few considerations related to it emerged as follow:

Globally at your maintained web sites be locations https://simplednscrypt.org/ or https://github.com/bitbeans/SimpleDnsCrypt in tab Code, URLs related to DNSCrypt under the links 'DNSCrypt' and 'dnscrypt-proxy' are with no exception obsolete since protocol used for connections isn't any more HTTPS. On those links, at the redirected home page, as noticeable current application is not maintained.

As illustrated at https://simplednscrypt.org/
- In the area mentioned as 'Cayman theme' in 'This page was generated by GitHub Pages using the Cayman theme by Jason Long.' (obviously mention is obsolete too, as noticeable at https://github.com/jasonlong/cayman-theme). 
- At location 'Special Thanks Frank Denis (@jedisct1) for developing libsodium and DNSCrypt'.

At last in mention 'Current Simple DNSCrypt version: 0.4.3 (with dnscrypt-proxy 1.9.5)' version is not updated (current stable version is mentioned on respective site as '2.0').

It would be still worth to extend the project by including supports for UNIX/Linux systems, if the allocated funds from the EAM GmbH and bytejail allowed for such task, assuming of course that your skills as developer are more than sufficient. Regards.

**Comment by bitbeans** [comment]
fixed https://simplednscrypt.org/
