### ISSUE TITLE
Client 0.2.9 Crash

### ISSUE THREAD

**Issue by spinnenbein** [bitbeans/SimpleDnsCrypt#21]
Hello, The Client 0.2.9 crashes, report see picture. Win 8.1. Client 0.2.8 is ok. 
![vcrun](https://cloud.githubusercontent.com/assets/8226313/12003116/574d2c8e-ab13-11e5-9a47-72fbb0e6313a.JPG)
 
![crash](https://cloud.githubusercontent.com/assets/8226313/12003106/0c305d0c-ab13-11e5-8873-f4e914c1d92e.JPG)

**Comment by bitbeans** [comment]
Hey, can you try this: https://www.microsoft.com/en-us/download/details.aspx?id=48145 ?

**Comment by spinnenbein** [comment]
Hey, is installed, still crashes ... .

**Comment by bitbeans** [comment]
see #5
