### ISSUE TITLE
New Version isn't working for me

### ISSUE THREAD

**Issue by Zalica** [bitbeans/SimpleDnsCrypt#211]
I have a laptop with windows 10 x64 with the latest update ,the language is Chinese ,the 0.4.3 works great on this .but the new version of 0.4.5 isn't working ,strangely.
I tried to install the .net framework 4.6.1,but it says I already installed a newer version.
when I click the simple dnscrypt icon,there is only SimpleDnsCrypt.exe running ,dnscrypt-proxy.exe doesnot start. and that is all.
I wonder what the problem is,I know nothing about code ,so I guess is impossible for me to deal with this.
Is there any way to give you more detail ,like the some log file , or is there something I did wrong ?
Thanks.

I just uninstalled some vpn software , mannually installed dnscrypt-proxy service ,but still not working

**Comment by rebornishard** [comment]
New version not working for me
win 10 x64

**Comment by medack** [comment]
@Zalica @rebornishard 
It's probably related to what is being discussed in issue #202.

Try the following in a command line with administrator rights:
cd "C:\Program Files\bitbeans\Simple DNSCrypt x64\dnscrypt-proxy\"
.\dnscrypt-proxy.exe -service install

**Comment by Zalica** [comment]
@medack tried that.  it does not work

**Comment by medack** [comment]
@Zalica Did you receive any error?

**Comment by Zalica** [comment]
@medack 
No. Just Nothing happened.

**Comment by medack** [comment]
@Zalica So the service is well installed. Can you start it? Try the following:

.\dnscrypt-proxy.exe -service start

What is the output?

**Comment by bitbeans** [comment]
its not a new feature: https://github.com/bitbeans/SimpleDnsCrypt/blob/master/img/old/advanced.png

**Comment by Zalica** [comment]
@medack 

with a normal console I got
```
PS C:\Users\Zalica> cd "C:\Program Files\bitbeans\Simple DNSCrypt x64\dnscrypt-proxy"
PS C:\Program Files\bitbeans\Simple DNSCrypt x64\dnscrypt-proxy> .\dnscrypt-proxy.exe -service start
[2018-02-09 20:00:40] [NOTICE] Source [https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md] loaded
[2018-02-09 20:00:40] [NOTICE] dnscrypt-proxy 2.0.0
[2018-02-09 20:00:40] [FATAL] Failed to start DNSCrypt client proxy: Access is denied.
PS C:\Program Files\bitbeans\Simple DNSCrypt x64\dnscrypt-proxy>
```

And run in console as a  administrator i got

```

PS C:\WINDOWS\system32>  cd "C:\Program Files\bitbeans\Simple DNSCrypt x64\dnscrypt-proxy"
PS C:\Program Files\bitbeans\Simple DNSCrypt x64\dnscrypt-proxy>  .\dnscrypt-proxy.exe -service start
[2018-02-09 20:02:22] [NOTICE] Source [https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md] loaded
[2018-02-09 20:02:22] [NOTICE] dnscrypt-proxy 2.0.0
[2018-02-09 20:02:22] [NOTICE] Service started
PS C:\Program Files\bitbeans\Simple DNSCrypt x64\dnscrypt-proxy>
```

I forgot to mention:
when run th command to install the service , I had to use console as an admin . If not ,the output will show access denied

I think it may be something about that.

**Comment by Zalica** [comment]
@medack 
And one more thing , in the task manager it shows that the SimpleDnsCrypt.exe is run by current user ,but the dnscrypt-proxy is run by SYSTEM
I guess it may have something with the problem

**Comment by medack** [comment]
@Zalica Everything you report appears to be perfectly normal.

In the beggining you said you did not have dnscrypt-proxy.exe running, but now the task manager shows that it is in fact running. Are you still having problems? If so, can you be more specific to what is the issue now or to what you are unable to do?

**Comment by icbxg** [comment]
Yes I got the same problem, the GUI doesn't show up in Chinese language windows10 x64

**Comment by bitbeans** [comment]
@icbxg Chinese is not yet translated: https://poeditor.com/join/project/3frSzJtSqc (feel free to contribute, if you can) :)

**Comment by Zalica** [comment]
@medack 
For me it looks like dnscrypt-proxy works fine in every way ,buy simplednsproxy.exe just can't get the dnscrypt-proxy service to install or to start running.

**Comment by Zalica** [comment]
I have done some translation，but it surely needs polishing. Hope somebody could continue the work

**Comment by d3bil0x** [comment]
Two such problems here too:
The `dnscrypt-proxy.exe` isn't installed automatically.
Solved with run the `dnscrypt-proxy.exe -service install` and next `dnscrypt-proxy.exe -service start` as admin.
But still the GUI does not start, although `SimpleDnsCrypt.exe` is in the process manager as active.
Solved by change of setting `Control Panel->Clock, Language, and Region->Format` to `English (United States)` before first run. Then can go back to the preferred previous `Format` setting, the application will run properly each time.
Tested on Windows 7 SP1 x64.

**Comment by bitbeans** [comment]
@d3bil0x whats`s your default language?

**Comment by d3bil0x** [comment]
@bitbeans The Display Language: English
Keyboard: Polish (programmers)
Language for non-Unicode programs: Polish
Current Location: Poland
Format: Polish

**Comment by bitbeans** [comment]
I am testing on a fresh Windows 10 x64 VM (en).

1. installing SimpleDnsCrypt 4.3.0 (x64)
2. Configuring Proxy 1 and Proxy 2
3. restart the VM
3. start SimpleDnsCrypt
4. allow AutoUpdate
5. let SimpleDnsCrypt 0.4.5 install automatically
6. everything works and the old services are removed

Note: always Run as Administrator

**Comment by bitbeans** [comment]
@d3bil0x is there anything in the logs directory?

**Comment by Zalica** [comment]
With the new 0.4,6 version ,I finally see the GUI,but for only once.
after I quit the program ,and click the icon again , the old problem cames back.
I reboot, doesn't work
,reinstall the promgram , and it doesn't work either.

I notice there are some logs

2018-02-11 20_04_42_Warn:

`2018-02-11 20:04:43.1998 LoaderViewModel Translation for zh-CN is not available`

2018-02-11 20_04_42_Error:
```
2018-02-11 20:05:35.2735 DnsCryptProxyManager System.InvalidOperationException: 无法打开计算机“.”上的 dnscrypt-proxy 服务(can't open the dnscrypt-proxy  service on computer “.”)。 ---> System.ComponentModel.Win32Exception: 指定的服务未安装。(service not installed)

   --- 内部异常堆栈跟踪的结尾 (this part is too hard for me to translate)---
   在 System.ServiceProcess.ServiceController.GetServiceHandle(Int32 desiredAccess)
   在 System.ServiceProcess.ServiceController.GenerateStatus()
   在 System.ServiceProcess.ServiceController.get_Status()
   在 SimpleDnsCrypt.Helper.DnsCryptProxyManager.IsDnsCryptProxyRunning()
```

**Comment by bitbeans** [comment]
@Zalica please try: https://bitbeans.de/SimpleDNSCrypt64.msi

**Comment by Zalica** [comment]
@bitbeans 
just tried ,and no luck.
first time 0.4.7 installed .it started normally.And visual basic  2017 is installed
 I quited and start again, stuck. there is a 2018-02-11 20_46_18_Warn log file shows 
`2018-02-11 20:46:18.4629 LoaderViewModel Translation for zh is not available`

the error log didn't appear.

uninstalled ,reboot and reinstall 0.4.7,the I'm back to the very beginning ,the service did'nt install at all ,the GUI didn't show up.

**Comment by bitbeans** [comment]
@Zalica settings are stores here: 
`C:\Users\<user>\AppData\Local\SimpleDnsCrypt\<xxx>\<version>`

**Comment by Zalica** [comment]
@bitbeans 
Thank you. I deleted the settings ,reinstalled 0.4.6 and use the English Interface and everything works fine.

**Comment by bitbeans** [comment]
@Zalica i have tested your scenario, there is a problem indeed :)

**Comment by Zalica** [comment]
@bitbeans 
glad to help. 
after the test,something new problem happend.
the warn log says:

```
2018-02-11 21:49:51.9618 DnsCryptProxyManager [2018-02-11 21:49:51] [NOTICE] Source [https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md] loaded
[2018-02-11 21:49:51] [NOTICE] dnscrypt-proxy 2.0.0
[2018-02-11 21:49:51] [FATAL] Failed to install DNSCrypt client proxy: InstallAsEventCreate() failed: SYSTEM\CurrentControlSet\Services\EventLog\Application\dnscrypt-proxy registry key already exists
```

may be it's better to do some more cleaning after uninstallation.This can be done by hand ,but I guess It's a little tricky for some people.

**Comment by bitbeans** [comment]
@Zalica i don`t know why this key is even there ... but i can try to delete it ... so keep it **simple** :)

**Comment by bitbeans** [comment]
@Zalica can you please test the latest version? 0.4.7 thank you

**Comment by Zalica** [comment]
@bitbeans 
Just tested . Works fine for me .
By the way,can you update the Chinese translation in the next update? I made some improvement on POEditor.
Thank you.

**Comment by bitbeans** [comment]
@Zalica i will, thank you for testing!
