### ISSUE TITLE
Release 0.4.5 (x64): DNS settings

### ISSUE THREAD

**Issue by ballios** [bitbeans/SimpleDnsCrypt#212]
Is this correct that just one line (Preferred DNS server) pointing at 127.0.0.1 but Alternate DNS server is empty?
Preferred DNS server and Alternate DNS server were at 127.0.0.1 both in previous SimpleDnsCrypt version...

**Comment by bitbeans** [comment]
Ja das ist korrekt.
Es gibt nur noch eine dnscrypt-proxy Instanz (service).
