### ISSUE TITLE
Possible to bring back the resolver ping feature?

### ISSUE THREAD

**Issue by r-a-y** [bitbeans/SimpleDnsCrypt#213]
Congrats on the new release.

One thing I'm missing is pinging the resolvers and looking at the ping time.  It appears v0.4.5 makes finding the fastest resolvers a transparent process, but I'd rather see the results on screen.

Thanks for considering!

**Comment by bitbeans** [comment]
@r-a-y i will think about this. but the load-balancing work should be done by dnscrypt-proxy itself.

**Comment by solariz** [comment]
I agree that the load balancing should be done by the proxy itself. But still would be nice to see at least some statistics or Info about which NS are used and how they are perform in avg to maybe make a decission to disable those which often cause a timeout or slow response time.


Btw. thanks for the Project!

**Comment by ewwink** [comment]
up, really need this. sometime I think my ISP is the problem but actually the problem came from slow response or dead server
