### ISSUE TITLE
Can not open a website(s) with DNSSEC enabled

### ISSUE THREAD

**Issue by rddim** [bitbeans/SimpleDnsCrypt#215]
If `Only servers with DNSSEC support` is enabled I can not open the http://www.abelhadigital.com/

**Comment by bitbeans** [comment]
@rddim https://simplednscrypt.org/ also have DNSSEC: https://dnssec-debugger.verisignlabs.com/simplednscrypt.org can you open it?

https://dnssec-debugger.verisignlabs.com/abelhadigital.com

**Comment by rddim** [comment]
Yes, I can. Thank you very much. I will try to contact with the abelhadigital.com owners to solve the problem.

**Comment by bitbeans** [comment]
okay :D
