### ISSUE TITLE
v0.4.6 (x64) impossible Starting!

### ISSUE THREAD

**Issue by ballios** [bitbeans/SimpleDnsCrypt#217]
What did you do, man?
After installation (clean) the new v0.4.6 (x64), main panel does not want load completely!
"Starting" small window does not disappear and thus main panel just is visible but not available.
Hmm...
_May be that happening because of Auto check update is turn off?.._

![screenshot](https://user-images.githubusercontent.com/19872946/36074127-4bdd4ffe-0f44-11e8-9ebb-dcaff6ebed86.jpg)

**Comment by bitbeans** [comment]
@ballios yes, working on it. sorry! :)
