### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by d3bil0x** [bitbeans/SimpleDnsCrypt#218]
> You also can verify the MSI packages with minisign. The minisign signatures x86 and x64 can be verified with the following command:
> 
> minisign -Vm SimpleDNSCrypt64.msi -P RWTSM+4BNNvkZPNkHgE88ETlhWa+0HDzU5CN8TvbyvmhVUcr6aQXfssV

Result:
`Signature verification failed`

But `EAM Experience Area Münsingen GmbH` signature is OK

**Comment by bitbeans** [comment]
I've updated the signature at 5:33 pm.
Please try again :)
