### ISSUE TITLE
Facing Strange Error running the software on windows 10 64bit

### ISSUE THREAD

**Issue by sammboi101** [bitbeans/SimpleDnsCrypt#22]
issues uninstalling software after it began to not work, what should I do, here is the screenshot of the error I am facing.

![simple dnscrypt](https://cloud.githubusercontent.com/assets/3008967/12004285/d3ef4674-ab44-11e5-80fe-2ded452a89fc.PNG)

**Comment by bitbeans** [comment]
see #5
