### ISSUE TITLE
2.4.7: Settings confusion... IPV6??

### ISSUE THREAD

**Issue by EC-O-DE** [bitbeans/SimpleDnsCrypt#220]
Ihave IPV6 (and ipv4) - do I enable ipv6... but also block it?

**Comment by bitbeans** [comment]
@EC-O-DE 
If you have IPv6 connectivity, you can enable IPv6, you proably won`t block it.

**Comment by EC-O-DE** [comment]
Yes, but every now and then I see on the log that your very nice and great app isn't encrypting DNS requests... :00
