### ISSUE TITLE
Black screen on Query Log and title bar after start

### ISSUE THREAD

**Issue by rddim** [bitbeans/SimpleDnsCrypt#221]
SDC start with a black title bar. When it is minimized or leave the focus and click back again everything is good. This appear on v.0.4.7-0.4.5, not sure for v.0.4.4

![simpledns_black_title](https://user-images.githubusercontent.com/8998791/36078437-f70d68de-0f7e-11e8-9971-5ef3387e47fd.gif)

SDC version: 0.4.7
OS version: Win7 Pro x64 SP1

**Comment by bitbeans** [comment]
@rddim i can not reproduce this for now. 

Maybe you can start Simple DnsCrypt from a command prompt (administrator): 

> SimpleDnsCrypt.exe -debug

And then send me the debug.log (log folder)

**Comment by rddim** [comment]
Here is it
[2018-02-12 19_25_37_Debug.log](https://github.com/bitbeans/SimpleDnsCrypt/files/1717181/2018-02-12.19_25_37_Debug.log)

**Comment by bitbeans** [comment]
@rddim is the title bar still black in 0.4.8?

**Comment by rddim** [comment]
@bitbeans yes, it is :(

**Comment by rddim** [comment]
1. Start SDC with enabled `Query Log`
2. Start some other program (Notepad++ in example)
3. Minimize SDC
4. Back again to SDC
After many click sometimes it shows normal screen, sometimes not

![test](https://user-images.githubusercontent.com/8998791/36143459-d463c540-10b3-11e8-98a5-b66ec0a6441b.gif)

**Comment by rddim** [comment]
Fixed after reinstall the Windows...
