### ISSUE TITLE
Instant crash when i try to start the Dnscrypt service

### ISSUE THREAD

**Issue by LucaSoranota** [bitbeans/SimpleDnsCrypt#222]
i got Instant crash when i try to start the Dnscrypt service
and it looks like that the resolvers didnt find anything and when i tried to turn off the dnscrypt mode on the resolvers tab suddenly the app crash

**Comment by bitbeans** [comment]
@LucaSoranota is there anything in the **logs** directory?

**Comment by LucaSoranota** [comment]
[2018-02-13 06_47_47_Error.log](https://github.com/bitbeans/SimpleDnsCrypt/files/1718083/2018-02-13.06_47_47_Error.log)
[2018-02-13 06_47_47_Warn.log](https://github.com/bitbeans/SimpleDnsCrypt/files/1718084/2018-02-13.06_47_47_Warn.log)

here is the log.. i already try to reinstall the app and sadly it didnt fix the crash

**Comment by monstertruckpa** [comment]
revounisntaller with it. has the solution.

**Comment by Crazy-Clown** [comment]
I'm experiencing the exact same issue after updating to the latest version.

**Comment by bitbeans** [comment]
@LucaSoranota @Crazy-Clown 

Can you please open a CMD or PowerShell window as administrator:

> cd "C:\Program Files\bitbeans\Simple DNSCrypt x64\dnscrypt-proxy"
> .\dnscrypt-proxy.exe -service install

and show me the output.

**Comment by Crazy-Clown** [comment]
@bitbeans 
``
C:\Program Files\bitbeans\Simple DNSCrypt x64\dnscrypt-proxy>.\dnscrypt-proxy.exe -service install
[2018-02-15 14:47:47] [NOTICE] System DNS configuration not usable yet, exceptionally resolving [download.dnscrypt.info] using fallback resolver [9.9.9.9:53]
[2018-02-15 14:47:48] [CRITICAL] Unable use source [public-resolvers]: [Get https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md: read tcp 192.168.10.202:63170->37.59.238.213:443: wsarecv: An existing connection was forcibly closed by the remote host.]
[2018-02-15 14:47:48] [FATAL] No servers configured

**Comment by bitbeans** [comment]
@jedisct1 can you help out here? :)

**Comment by bitbeans** [comment]
@Crazy-Clown and if you try to start the service via cmd? will the same error message appear?

**Comment by Crazy-Clown** [comment]
@bitbeans 

So the install service cmdlet command works and service is startable (through services.msc) on a Win Server 2008 R2 x64 but does not start on the Win Server 2016 x64, I receive the error:
`Windows could not start the DNSCrypt client proxy service on Local Computer.

Error 193:0xc1`

**Comment by bitbeans** [comment]
@Crazy-Clown I don't have a Win Server 2016 x64 for testing. Is there an antivirus program on the server, which might cause a problem?

**Comment by Crazy-Clown** [comment]
@bitbeans No antivirus on the server, just standard MS protection.  I do have WatchGuard TDR (Threat Detection and Response) agent, but that has not triggered anything abnormal.

**Comment by bitbeans** [comment]
@Crazy-Clown do you have a second Win Server 2016 x64?

**Comment by Crazy-Clown** [comment]
@bitbeans I do not, what do you need?

By the way, the event log error I'm getting is:  

The DNSCrypt client proxy service failed to start due to the following error: 
DNSCrypt client proxy is not a valid Win32 application.

**Comment by bitbeans** [comment]
@Crazy-Clown i need a VM first. maybe i can setup one tomorrow. 
the problem doesn't seem to be SimpleDnsCrypt. i don't know if dnscrypt-proxy is compatible with windowserver 2016 x64?

**Comment by Crazy-Clown** [comment]
@bitbeans It was working previously for me.

**Comment by bitbeans** [comment]
@Crazy-Clown the 2.0 version? or the old 1.9.x?

**Comment by Crazy-Clown** [comment]
@bitbeans I believe before the 2.0 version.

Also, can confirm that x86 service does not install/run properly from the x86 installer on Server 2016 x64 - HOWEVER, manually installing via CMD and starting service does work.

So as far as I can tell, the x64 installer / proxy application doesn't run on x64 on Server 2016 x64.
The x64 installer DOES work properly on Win10 x64.

**Comment by bitbeans** [comment]
@Crazy-Clown 
I have just tested dnscrypt-proxy and SimpleDnsCrypt on a Windows Server 2016 x64. All of them work without any problems in my opinion.
There must be a Problem with your installation ... :(

**Comment by LucaSoranota** [comment]
@bitbeans 
reinstalling the service via powershell work 
this thing happen probably because when updating from 1.9.x to 2.0.x the installer fails to reintall the service or accidentically makes it didnt work

**Comment by Crazy-Clown** [comment]
@bitbeans Interesting.  The installation I have here is defaulted, with a Plex server.  There are not any other roles listed on this.  It's running in a Workgroup mode, nothing special.  That's bizarre.

**Comment by bitbeans** [comment]
@LucaSoranota but it does not fail on every system ... thats the problem :)
