### ISSUE TITLE
Having hard time to grasp when SimpleDNScrypt enabled...

### ISSUE THREAD

**Issue by EC-O-DE** [bitbeans/SimpleDnsCrypt#223]
Having hard time to grasp when SimpleDNScrypt enabled... My network card and router has both ip4v and ip6v - using Win 10 Pro x64.

I hesitate a bit to write this as it's marvelous that this app is done to the very wysiwyg-ppl of Windows :D I recently installed Python on mi comp - so I know more than CMD :)

But I'm vary when it comes to the GUI of this app - there's necessarily not too many options and button - no - in the LOG tab sometimes I see addresses that are of plain English - and sometimes something else that could be a clear indication of DNS Crypt taking place. 

But when I leave the app on and check back  ~ it's changed,, making me think that perhaps I haven't set it right,, but ~ I've tried different 'settings' and I'm no where near "just enable and leave it". Guides on websites and vid tut's on Youtube weren't that much any helpful.

^ There's a Wiki section on here. If I get this going I could do a setup guide with pictures :) to strengthen those in doubt. 

If the addresses in the log section variate that much - I guess I'm not doing it right :hmm:

**Comment by bitbeans** [comment]
@EC-O-DE maybe you want try the original https://github.com/jedisct1/dnscrypt-proxy/wiki and play a little bit. I don`t have IPv6 support on my provider.
