### ISSUE TITLE
Check for updates on startup issue

### ISSUE THREAD

**Issue by ballios** [bitbeans/SimpleDnsCrypt#224]
I have - v0.4.6
Check for updates on startup - is on (for Stable).
Why I don't see update notification about v0.4.7 ?
And what happening with SimpleDnsCrypt at all?

**Comment by bitbeans** [comment]
@ballios please change to "Preview" and restart the application.
And be sure you have installed Microsoft Visual C++ Redistributable for Visual Studio 2017, otherwise the signature verification will fail.
