### ISSUE TITLE
After Installing, Windows File Signatures All Messed up! Accessing Services.MSC = "Do you want to allow the following program from an unknown publisher make changes to this computer"

### ISSUE THREAD

**Issue by ravenise** [bitbeans/SimpleDnsCrypt#225]
Was the SimpleDnsCrypt RSA Code Signing CA used to hack my computer and replace all my Windows certificates? Why did the one certificate for the adapter installed with SimpleDnsCrypt affect every other critical MMC process and adapter in Windows 7? I never verified the MSI packages with minisign; is this the reason? Man one thing after another!  "Publisher Unknown" File Origin "Hard Drive On This Computer." Wow what thee fuck just happened?

**Comment by ravenise** [comment]
This happens when accessing the device manager, adapters, any msc... the list goes on.  What the fuck?

**Comment by ravenise** [comment]
Uninstalling does not fix this problem... how do I remove this certificate?

**Comment by monstertruckpa** [comment]
What's happen with this version, the secondary service 127,0.0.2 doesn't  exist? thanks apreciatte proyect, i want the secondary service,

**Comment by monstertruckpa** [comment]
the new versión 0.4.8  (2018) its very slow on everyone menues,  please recompile it again other version.

**Comment by rddim** [comment]
@monstertruckpa I think there is no need from secondary service. If you check the `config.yaml` you will see that there is `PrimaryResolver:` and `SecondaryResolver:`

**Comment by ravenise** [comment]
Never mind, fixed the problem using sigcheck with the command-line option -tv "sigcheck tv"
