### ISSUE TITLE
Can not disable Query Log

### ISSUE THREAD

**Issue by rddim** [bitbeans/SimpleDnsCrypt#226]
I enable the `Query Log` for some testing and now I can not disable it.

1. Start SDC and enable `Query Log`
2. Close SDC
3. Start SDC and disable `Query Log`
4. Close SDC
5. Start SDC > the `Query Log` is enabled

This is the content of `dnscrypt-proxy.toml`
```
listen_addresses = ["127.0.0.1:53", "[::1]:53"]
max_clients = 250
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
require_dnssec = true
require_nolog = true
require_nofilter = true
daemonize = false
force_tcp = false
timeout = 2500
log_level = 0
use_syslog = false
cert_refresh_delay = 240
fallback_resolver = "9.9.9.9:53"
ignore_system_dns = false
block_ipv6 = true
cache = true
cache_size = 256
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_ttl = 60

[query_log]
format = "ltsv"
file = "query.log"

[nx_log]
format = "ltsv"

[blacklist]

[ip_blacklist]

[sources]

[sources.public-resolvers]
url = "https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md"
minisign_key = "RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3"
cache_file = "public-resolvers.md"
refresh_delay = 72
prefix = ""
```

**Comment by rddim** [comment]
To disable `Query Log` manually I need to:

1. Disable `Query Log` from the slider
2. Disable `DNSCrypt Service` to unlock the `query.log` file in `dnscrypt-proxy` folder
3. Delete the `query.log` because if it exist it will be used even if step 4 is done
4. Remove the line `file = "query.log"` from `dnscrypt-proxy.toml`

**Comment by user8446** [comment]
I was getting ready to open a new issue and saw your open issue.

What I have noticed is when you open the program and click the "Query Log" tab, the slider automatically gets turned on. If you slide it off it will stay off until the program is re-opened and you click the Query Log tab again in which the cycle repeats. 

Running 0.4.8 (x64) on W10
