### ISSUE TITLE
Need more width for Settings

### ISSUE THREAD

**Issue by rddim** [bitbeans/SimpleDnsCrypt#227]
In some languages the Settings windows doesn't show the full translations

Bulgarian and French
![sdc_bulgarian](https://user-images.githubusercontent.com/8998791/36145546-61714682-10ba-11e8-869d-89daf4f906ec.png) ![sdc_french](https://user-images.githubusercontent.com/8998791/36145547-61945762-10ba-11e8-85e4-a07aa955747a.png)

Portuguese and Spanish
![sdc_portuguese](https://user-images.githubusercontent.com/8998791/36145548-61b3676a-10ba-11e8-8db6-5e2ad6fb03ba.png) ![sdc_spanish](https://user-images.githubusercontent.com/8998791/36145549-61d20756-10ba-11e8-9391-221c504d6d7f.png)
 and some others.

Also the title bar name is not changed when change the language. It needs to restart the SDC to show the selected language.

**Comment by bitbeans** [comment]
@rddim thank you for testing all the languages!
