### ISSUE TITLE
How to use Simple DNSCrypt with DNSSEC together in Windows?

### ISSUE THREAD

**Issue by ravenise** [bitbeans/SimpleDnsCrypt#228]
Can someone please explain how to do this? Does this happen automatically inside Simple DNSCrypt? Plenty of tutorials exist for Linux on this combination, but I cannot find any information for windows. Thanks!

**Comment by bitbeans** [comment]
@ravenise this happen in https://github.com/jedisct1/dnscrypt-proxy
