### ISSUE TITLE
Non-human-readable timestamps in the log file

### ISSUE THREAD

**Issue by rkawulak** [bitbeans/SimpleDnsCrypt#230]
In the new version, timestamps are encoded as Unix time, but in the previous versions they were formatted to be human-readable, which was more user-friendly. From what I found in dnscrypt-proxy sources, setting log format to "tsv" should provide a nice ISO date-time format.

**Comment by bitbeans** [comment]
@rkawulak for now it will be ltsv. Maybe i will make it configurable or will change it. 
I have a lot of missing basic features with higher priority. Sorry :)
