### ISSUE TITLE
Unable to disable Query Log

### ISSUE THREAD

**Issue by salavessa** [bitbeans/SimpleDnsCrypt#232]
Observed in versions 0.4.7x64 and 0.4.8x64 (never tried any other versions).
It seems that the action to disable the query log just restarts dnscrypt-proxy service and updates the UI (until restarted) but it doesn't actually remove the _file = "query.log"_ entry from _[query_log]_ section on _dnscrypt-proxy.toml_.

The action to enable the query log works just fine but I was only able to disable it by manually commenting/deleting the property mentioned above and service restart afterwards.

Thanks!

**Comment by bitbeans** [comment]
@salavessa sould be fixed: https://github.com/bitbeans/SimpleDnsCrypt/issues/226 https://github.com/bitbeans/SimpleDnsCrypt/commit/bba6a25d0aa86774fd47f40e62f2365e78108575

Maybe you want test and validate it? :) https://simplednscrypt.blob.core.windows.net/deploy/SimpleDnsCrypt/bin/x64/SimpleDNSCrypt_x64.zip

**Comment by salavessa** [comment]
Thanks for that, that version is working fine for me!
