### ISSUE TITLE
Rate Limitations, DNS servers not reoslving, inconsistent 

### ISSUE THREAD

**Issue by Crazy-Clown** [bitbeans/SimpleDnsCrypt#233]
I'm not sure if this is related to the project here or DNSCrypt servers themselves, but I've noticed when configuring for dnscrypt.ca-1, dnscrypt.ca-2 and dnscrypt.ca-3 for requests, I've been noticing a lot of issues with DNS not resolving (and resulting in no internet access).

I have PRTG Network monitor on one of my boxes pinging my client network connections (around maybe 50 outgoing pings), and do have DNS Caching enabled on the SimpleDNSCrypt client but for whatever reason, just turned on my main system and noticed I had no internet connection.  The DNS Servers were not responding.  I had to statically set them to OpenDNS.

Are there any known restrictions for DNSCrypt servers with regards to the amount of requests and if so, is there a work-around to prevent this from happening if deployed on a large scale from a single network?

**Comment by bitbeans** [comment]
@Crazy-Clown please understand that simplednscrypt is only a configuration interface for dnscrypt-proxy itself. I think this question should be placed in the https://github.com/jedisct1/dnscrypt-proxy project. :)
