### ISSUE TITLE
[bug][enhancement] settings do not persist during auto-update

### ISSUE THREAD

**Issue by user8446** [bitbeans/SimpleDnsCrypt#234]
During the auto-update from 0.4.8 to 0.4.9, the settings do not persist like the previous version auto-updates. I don't know if this is a bug or if this is now intentional. Thank you.

**Comment by bitbeans** [comment]
@user8446 0.4.9 -> 0.5.0 -> 0.5.1 ? :)

**Comment by user8446** [comment]
Yes, through all three of those updates the settings do not persist.

**Comment by jedisct1** [comment]
Bugs that don't want to go away are annoying and make people grumpy, so here is a cute kitten.

![kitten](https://static.wamiz.fr/images/upload/17662257_1163602267101936_1623276077705068544_n(1).jpg)

**Comment by user8446** [comment]
lol :)

**Comment by TroudhuK** [comment]
I'm still in 0.4.3 because you proposed to auto-upgrade even if we lost big functionalities (block list! All is allowed, okkk), can I upgrade now to 0.5.2, without losing anything and keeping my settings (except for server management which changed with v2)?

**Comment by bitbeans** [comment]
Settings from 0.4.3 to 0.5.x are not automatically applied. But future settings should be retained.
