### ISSUE TITLE
Windows services

### ISSUE THREAD

**Issue by rddim** [bitbeans/SimpleDnsCrypt#236]
Which services are needed for SDC to start the GUI? Last night I reinstall my Windows, stop and disable some services and now SDC crash at startup. I don't remember which services are stopped, but I create a restore point before that. Recover of the restore point doesn't help me. Here are the log files:

[2018-02-20 19_27_34_Debug.log](https://github.com/bitbeans/SimpleDnsCrypt/files/1741166/2018-02-20.19_27_34_Debug.log)
[2018-02-20 19_27_34_Error.log](https://github.com/bitbeans/SimpleDnsCrypt/files/1741167/2018-02-20.19_27_34_Error.log)

Event Viewer:

Application Error
```
Faulting application name: SimpleDnsCrypt.exe, version: 0.4.9.0, time stamp: 0x5a89bdac
Faulting module name: KERNELBASE.dll, version: 6.1.7601.23677, time stamp: 0x589c9a27
Exception code: 0xc06d007e
Fault offset: 0x000000000001a06d
Faulting process id: 0xa10
Faulting application start time: 0x01d3aa701848e820
Faulting application path: C:\Program Files\bitbeans\Simple DNSCrypt x64\SimpleDnsCrypt.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 56c18d41-1663-11e8-a6a9-bc5ff4456361
```

.NET Runtime
```
Application: SimpleDnsCrypt.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c06d007e, exception address 000007FEFD8AA06D
```

OS: Windows 7 Pro SP1
Net Framework: 4.7.1

**Comment by bitbeans** [comment]
@rddim please try 0.5.0

**Comment by rddim** [comment]
@bitbeans  Again - crash at startup. On VM with untouched services it works fine.

**Comment by rddim** [comment]
Fixed! I just reinstall Net Framework and now SDC works fine :) Why M$ sux so much?!
