### ISSUE TITLE
v0.5.1 (x64) - Resolvers connection problem

### ISSUE THREAD

**Issue by ballios** [bitbeans/SimpleDnsCrypt#237]
There are frequent disconnections when I'm connected via for ex. d0wn-us-ns4 resolver!
Can you make the resolvers more stable?
P.S. Those disconnections is happening from version to version in SimpleDnsCrypt...

**Comment by bitbeans** [comment]
@ballios this is not a Simple DNSCrypt or dnscrypt-proxy problem. Please choose another server. I`am not the maintainer of the servers ...

**Comment by bitbeans** [comment]
@ballios maybe you want setup your own server: https://github.com/jedisct1/dnscrypt-proxy/wiki/How-to-setup-your-own-DNSCrypt-server-in-less-than-10-minutes
