### ISSUE TITLE
Question: Can ISP still see DNS look-ups / queries?

### ISSUE THREAD

**Issue by grand-lotus-iroh** [bitbeans/SimpleDnsCrypt#238]
So if someone like me is using Comcast, Verizon or whomever... and uses Simple DNScryot, can ISP still see activity resolver queries / logs? If things are encyrpyed, does that mean they just see a bunch of 0's and 1's?

Just looking to get your opinion.

Thanks!

---

![image](https://user-images.githubusercontent.com/1291364/36528201-4ef674fe-1782-11e8-9d65-676e6fd9b11b.png)

![image](https://user-images.githubusercontent.com/1291364/36528215-58ba839a-1782-11e8-95dc-5e6decf18e59.png)

![image](https://user-images.githubusercontent.com/1291364/36528232-62ccaab6-1782-11e8-8b01-6c89ee40b39b.png)

**Comment by Sporif** [comment]
Yes that's one of the benefits of dnscrypt, dns queries are encrypted. Your ISP will only see that connections are made to the dnscrypt server used.
