### ISSUE TITLE
api-ms-win-crt-runtime-l1-1-0.dll error

### ISSUE THREAD

**Issue by AlexBaker-** [bitbeans/SimpleDnsCrypt#24]
After installing the latest binary of this on Windows 8.1 x64, I received a .dll error that made SimpleDNSCrypt crash with a stack trace when attempting to run it.  Googling the error led me to [a different Github issue](https://github.com/cmderdev/cmder/issues/501) that was resolved.  To resolve this, download the [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) and install it.

Suggested solution: Maybe include this VC++ distributable and install it if not already installed.

**Comment by 0x23marco** [comment]
Same issue with latest Simple DNSCrypt 0.2.9 on Windows 7 x64 tried reinstalling as also fresh install always ends in above runtime error.
Stacktrace and error messages attached for detailed troubleshooting.

![stacktrace](https://cloud.githubusercontent.com/assets/7345406/12221420/3a0e9fa2-b79a-11e5-9156-9826314dfed2.jpg)
![systemerror](https://cloud.githubusercontent.com/assets/7345406/12221421/3a32ac08-b79a-11e5-9366-7a80623f0313.jpg)

**Comment by bitbeans** [comment]
Thank you for reporting this, i will include it into the next release.
See #27
