### ISSUE TITLE
How I can set opendns in 5.1 ?

### ISSUE THREAD

**Issue by anirugu** [bitbeans/SimpleDnsCrypt#241]
I was happy with the old version I was using. I simply set opendns and forget which network I am connecting to. I always get opendns working.

Now I can't set IP or I am missing something. Where I need to set the ip of opendns. Does someone can help me to find put how to set dns ip.

Thanks

**Comment by jedisct1** [comment]
Same here. You just have to choose `Cisco` in the list.

**Comment by anirugu** [comment]
@jedisct1  Thanks for reply. Sorry, I am still not getting you. please show me a screenshot so I can do it on my machine.

**Comment by bitbeans** [comment]
@anirugu are you using Simple DNSCrypt or dnscryp-proxy?

**Comment by bitbeans** [comment]
![cisco](https://user-images.githubusercontent.com/1482102/36635256-253d4412-19b2-11e8-9a5b-4a3f8944f7df.PNG)

**Comment by jedisct1** [comment]
Gorgeous.

**Comment by anirugu** [comment]
Thanks, I have checked 3 option in first tab so It was not showing to me.  It's fine now.
