### ISSUE TITLE
Does SimpleDNSCrypt use DNSSEC?

### ISSUE THREAD

**Issue by ravenise** [bitbeans/SimpleDnsCrypt#243]
Does Simple DNSCrypt automatically enable and use DNSSEC? or does it only enable and use DNSCrypt? The GUI defaults to enable only servers that support DNSSEC; Though I see no documentation confirming whether or not DNSSEC is actually implemented by Simple DNSCrypt. Could you please confirm this? Thank you so much, and keep up the revolutionary, amazing work!

**Comment by Sporif** [comment]
Simple DNSCrypt doesn't need to do anything regarding DNSSEC, that's all on dnscrypt-proxy and the servers used.
