### ISSUE TITLE
Domain Blacklist issue

### ISSUE THREAD

**Issue by rddim** [bitbeans/SimpleDnsCrypt#245]
Enabling `Domain Blacklist and Whitelist` (DBW) doesn't create the `blacklist.txt` file. This affect the `DNSCrypt Service` by disabling it after close and re-open SDC. Disabling the `DBW` is not possible after it is enabled. To solve this the `blacklist.txt` file must be created manually or the `blacklist_file = "C:\\Program Files\\bitbeans\\Simple DNSCrypt x64\\dnscrypt-proxy\\blacklist.txt"` line must be removed from `dnscrypt-proxy.toml` If the `blacklist.txt` exists, then enabling\disabling `DBW` will work as expected.

**Comment by sergeevabc** [comment]
Am not sure if it is relevant here, but no doubt an issue. If I download @jedisct1’s [mybase.txt][1], then rename it to domain-blacklist.txt, then open SimpleDNS and switch to Blaclist tab, the app freezes to death. 

[1]: https://download.dnscrypt.info/blacklists/domains/mybase.txt

**Comment by jedisct1** [comment]
Given that it's more than 111,000 lines this is probably not something you want to manually edit in a text form.

**Comment by sergeevabc** [comment]
But how to load ```mybase.txt``` along with SimpleDNS then? If I manually add
```[blacklist]
log_format = "ltsv"
blacklist_file = "mybase.txt"
```
then launch SimpleDNS, it silently replaces that snippet with
```[blacklist]
log_format = "ltsv"
blacklist_file = blacklist_file = "C:\\Program Files\\SimpleDNSCrypt\\dnscrypt-proxy\\blacklist.txt"
```
and ```blacklist.txt``` is empty.

**Comment by sergeevabc** [comment]
Agrrhhh, I’ll stick to bare ```dnscrypt-proxy``` then, given that it already has a way to install as service.
