### ISSUE TITLE
Need more width and height (part 2)

### ISSUE THREAD

**Issue by rddim** [bitbeans/SimpleDnsCrypt#247]
Dynamic heigth can be added for `Resolvers`, `Query Log`, `Domain Block Log` and `Domain Blacklist`

![width_1](https://user-images.githubusercontent.com/8998791/36642354-10c492b6-1a47-11e8-8ff0-8c2449c834c4.png)

Dynamic width can be added for `Domain Blacklist`. Also there are need more width for `Blacklist:`, `Whitelist Rules:` and `Blacklist Rules:` localization for some languages (example Bulgarian, Russian, Hungarian and some others). There is a problem with Italian language and the text around `Blacklist Rule` (see the screenshot below)
![width_2](https://user-images.githubusercontent.com/8998791/36642355-10e41fbe-1a47-11e8-9698-dcc30c857daa.png)

**Comment by bitbeans** [comment]
@rddim Thank you very much for the extensive testing!!!

**Comment by bitbeans** [comment]
Italian string fixed

**Comment by bitbeans** [comment]
Dynamic height:
- [x] Main Tab
- [ ] Resolvers
- [x] Advanced Settings
- [x] Query Log
- [x] Domain Block Log
- [x] Domain Blacklist
