### ISSUE TITLE
Possible Update Bug

### ISSUE THREAD

**Issue by zero77** [bitbeans/SimpleDnsCrypt#248]
This may or may not be a bug but, SimpleDnsCrypt only seams to check and install updates when the UI has been opened.

Which is not very offer when its working, at least for me, could you get it to update automatically in the background with out having to open the UI.

**Comment by bitbeans** [comment]
@zero77 this is not a bug :) 
checking for updates in the background would require a separate service.

**Comment by zero77** [comment]
Yes, I wasn’t sure if it was a bug or not, though Is this something that will be implemented.

Because, SimpleDnsCrypt is a great application that seems to just work without any monitoring. 

Once configured I imagine that most people just leave it and are unlikely to open it to check for updates.

**Comment by bitbeans** [comment]
currently not planned
