### ISSUE TITLE
[Request] Perl Compatible Regular Expressions (PCRE) support for domain filtering

### ISSUE THREAD

**Issue by Gaffnet** [bitbeans/SimpleDnsCrypt#249]
I use an older version of Simple DNSCrypt with Acrylic DNS because Acrylic allows the use of PCRE in its filters and I have a requirement that involves blocking many randomly generated hexadecimal style domain names of varying character length.  E.g.

db8a41d81b8dfe41de2.com
77d0f28ca582231.com
ff5bd8d9f8df.com
etc...

Pre-emptively blocking any domain which follows the hexadecimal naming format isn't feasible under the current wildcard system, and I think PCRE matching in general would be a very useful feature to have.  (_Edited for clarity_)

Thanks!

**Comment by bitbeans** [comment]
@Gaffnet can't you add the entries via the interface (Simple DnsCrypt UI) or doesn't dnscrypt-proxy react to it?

**Comment by Gaffnet** [comment]
Sorry, I should have given a more concise explanation.  I wish to preemptively block any domain which follows the hexadecimal domain name format via Simple DNSCrypt.  

In my particular home-use case, these kinds of domains are being used for dubious ad networks or outright malicious purposes.  I suspect that the people behind the domains have generated a reserve of hundreds (maybe thousands) of these hexadecimal domain names.  If any of their domains get blocked or blacklisted, they reconfigure their systems with an unused, non-blacklisted domain from that large reserve.  Since I have no way of knowing what their next domain will be, only that it will be in randomly generated hexadecimal format of varying length, being able to preemptively filter them out would be immensely helpful.

**Comment by bitbeans** [comment]
@Gaffnet 
Simple DnsCrypt only adds the rules to the blacklist file.
They are read and used by dnscrypt-proxy.
