### ISSUE TITLE
Simple DNS Crypt for Windows not compatible with Panda URL Filtering.

### ISSUE THREAD

**Issue by liubomirwm** [bitbeans/SimpleDnsCrypt#25]
Hello, when Panda URL Filtering is installed along Simple DNS Crypt, the internet doesn't work and Chrome says that there is a DNS bad config.

**Comment by bitbeans** [comment]
Hmm, sorry i dont know Panda URL Filtering.
Maybe you can add 127.0.0.1 to this software directly?

**Comment by liubomirwm** [comment]
It it the URL Filtering component of Panda Free Antivirus. 

pandasecurity.com
