### ISSUE TITLE
dnsencrypt-proxy.exe detected as virus

### ISSUE THREAD

**Issue by ukind** [bitbeans/SimpleDnsCrypt#250]
I'm using bitdefender free edition, and just today my antivirus detect it as virus. here's the screenshot:

![untitled](https://user-images.githubusercontent.com/10288424/36765376-7ad9b528-1c63-11e8-9799-c8a71f52e9a2.png)

**Comment by bitbeans** [comment]
@ukind are you using a signed or CI build?

Maybe check: https://www.virustotal.com

**Comment by jedisct1** [comment]
Or even better, report it to Bitdefender as a false positive.
