### ISSUE TITLE
Service not started upon reboot

### ISSUE THREAD

**Issue by n31n** [bitbeans/SimpleDnsCrypt#253]
Windows 10 x64 latest updates.
Seemingly at random boots, the SimpleDnsCrypt service will not be started. 
Toggling the service to start in SimpleDnsCrypt fails, it disables itself immediately.

I run an IP firewall, called Peerblock. On the boots that SimpleDnsCrypt service will not start, I notice that Peerblock has blocked "IBM Corporation" dns, at 9.9.9.9:53 .
After I disable Peerblock and allow 9.9.9.9:53, in Peerblock, SimpleDnsCrypt allows me to enable its service immediately.

 I think it is a bug, that SimpleDnsCrypt service will not enable if 9.9.9.9:53 is blocked.

Since using the latest versions of SimpleDnsCrypt, I have noticed Peerblock picking up other blacklisted DNS I.P.'s, such as UK social security adminstration and Terratransit.

Hope this is a clear enough description. 

Attaching screenshots.
![simplednscrypt bug](https://user-images.githubusercontent.com/16268723/36949563-323777b2-1fb8-11e8-96f4-210348e75395.jpg)
![simplednscrypt bad dns](https://user-images.githubusercontent.com/16268723/36949582-8765ee6c-1fb8-11e8-964f-85c8657fb2d2.png)

**Comment by bitbeans** [comment]
@n31n can you give me the outpuf of:

> cd "C:\Program Files\bitbeans\Simple DNSCrypt x64\dnscrypt-proxy"
> .\dnscrypt-proxy -service start

**Comment by n31n** [comment]
C:\Program Files\bitbeans\Simple DNSCrypt x64\dnscrypt-proxy>.\dnscrypt-proxy -service start
[2018-03-05 15:22:41] [NOTICE] Source [https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md] loaded
[2018-03-05 15:22:41] [NOTICE] dnscrypt-proxy 2.0.4
[2018-03-05 15:22:41] [FATAL] Failed to start DNSCrypt client proxy: Access is denied.

**Comment by bitbeans** [comment]
@n31n you need to start it as administrator (cmd or powershell). and you are not using the latest version?

**Comment by n31n** [comment]
Oh, are you asking to do this while the bug is occurring?

**Comment by bitbeans** [comment]
@n31n the latest version uses dnscrypt-proxy **2.0.6**

> [2018-03-05 15:22:41] [NOTICE] dnscrypt-proxy 2.0.4

**Comment by n31n** [comment]
This issue has not appeared again since the latest update .0.5.3 proxy version 2.0.6. The Terratransit dns's have seemingly not appeared, also. 

Thank you again for all your efforts with this project. It has progressed far since its inception.

**Comment by chrone81** [comment]
I still got this issue on 0.5.3 proxy 2.0.6.

`C:\Program Files (x86)\bitbeans\Simple DNSCrypt\dnscrypt-proxy>dnscrypt-proxy.exe -service start
[2018-03-21 20:35:41] [INFO] Loading source information from URL [https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md]
[2018-03-21 20:36:11] [NOTICE] System DNS configuration not usable yet, exceptionally resolving [download.dnscrypt.info] using fallback resolver [9.9.9.9:53]
[2018-03-21 20:36:42] [INFO] Loading source information from URL [https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md.minisig]
[2018-03-21 20:37:12] [CRITICAL] Unable use source [public-resolvers]: [Get https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)]
[2018-03-21 20:37:56] [FATAL] No servers configured`

**Comment by chrone81** [comment]
Turned out my government block access to download.dnscrypt.info hence broke SimpleDNSCrypt app services. :(

**Comment by jedisct1** [comment]
It doesn't seem to be blocked: https://www.greatfirewallofchina.org/index.php?siteurl=dnscrypt.info

But try replacing `fallback_resolver = '9.9.9.9:53'` with `114.114.114.114:53` in the `.toml` file.

**Comment by chrone81** [comment]
Thanks @jedisct1 

I'm from Indonesia and I think my government block the route access to *.dnscrypt.info and also they intercept dns traffic to any other public DNS and redirected to their own.

**Comment by jedisct1** [comment]
Ouch :( This is not great :(

What IP address do you get when trying to resolve `download.dnscrypt.info`?

Can you copy/paste the output of `tracert -n 37.59.238.213`?

**Comment by chrone81** [comment]
@jedisct1 I got lucky today, they were not blocking dnscrypt.info anymore. I disabled the dnscrypt automatic mode and stick with cloudflare though. I'll post the traceroute results when I got blocked again. Thanks!

**Comment by chrone81** [comment]
@jedisct1 I got blocked again but managed to get tracert result below. At this point, dnsproxy service could not be run and crashed often due to not finding the new public-resolvers.md.

I had to use download new public-resolvers.md using VPN and update the toml file to make dnscrypt proxy works again. I wish dnscrypt service still working eventhough the public-resolvers.md time to live has expired. At least there's a fallback to still using dnscrypt to download new public-resolvers.md.

```
C:\WINDOWS\system32>tracert -d download.dnscrypt.info
Tracing route to download.dnscrypt.info [37.59.238.213]
over a maximum of 30 hops:
  1    <1 ms    <1 ms    <1 ms  10.1.1.1
  2    50 ms     2 ms     1 ms  10.84.0.1
  3     1 ms     1 ms     1 ms  125.160.0.117
  4     1 ms     1 ms     1 ms  180.252.3.201
  5    24 ms    23 ms    24 ms  180.240.193.30
  6    23 ms    23 ms    23 ms  180.240.193.29
  7   216 ms   216 ms   216 ms  180.240.192.150
  8   209 ms   209 ms   209 ms  198.27.73.152
  9   268 ms   267 ms   268 ms  178.32.135.161
 10   265 ms   265 ms   265 ms  198.27.73.218
 11     *      280 ms   279 ms  192.99.146.132
 12     *        *      281 ms  213.251.130.102
 13     *        *        *     Request timed out.
 14     *        *        *     Request timed out.
 15     *        *        *     Request timed out.
 16   277 ms     *        *     37.59.238.213
 17     *      277 ms     *     37.59.238.213
 18     *        *        *     Request timed out.
 19     *        *        *     Request timed out.
 20     *      277 ms     *     37.59.238.213
 21     *        *      277 ms  37.59.238.213
Trace complete.
```
