### ISSUE TITLE
How do I ensure DNSSEC is working with Simple Dnscrypt?

### ISSUE THREAD

**Issue by ravenise** [bitbeans/SimpleDnsCrypt#254]
I notice by default Simple DNSCRYPT is set to only connect to servers with DNSSEC support. How do I test to make sure DNSSEC is working as it should be? And is DNSSEC enabled by default through simple DNS? Thank you very much!

**Comment by cnoizem** [comment]
something like this? https://dnssec.vs.uni-due.de/
I wish I knew other tools to test it as well.
