### ISSUE TITLE
Plugin Page Missing on 0.5.3

### ISSUE THREAD

**Issue by rahadiancs** [bitbeans/SimpleDnsCrypt#257]
I still used version 0.4.3 on my old pc and I install the latest 0.5.3 on my new pc. But I can't find plugin page on the new version, I really need the forwarding function. Is it missing or removed?

**Comment by xxKryptonite** [comment]
Same question/issue for me.  Was wondering where the forwarding option was located.  Is there a reason for this?  Is it possible to still forward by editing/creating a text file?

**Comment by bitbeans** [comment]
@rahadiancs this feature ist not yet available in the UI.
@xxKryptonite But if you edit the [toml](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml#L156), Simple DNSCrypt should keep this setting: https://github.com/bitbeans/SimpleDnsCrypt/blob/master/SimpleDnsCrypt/Models/DnscryptProxyConfiguration.cs#L370

**Comment by bitbeans** [comment]
see https://github.com/bitbeans/SimpleDnsCrypt/issues/259
