### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by mardetanha** [bitbeans/SimpleDnsCrypt#258]
I don't if it is an intended feature or not, but every time I reboot my system and wanted to start simple dnscrypt, it goes through a lengthy setup saying downloading installer, I didn't have this problem with older version but is so annoying. could you please update me on this.

**Comment by bitbeans** [comment]
@mardetanha have you installed [Microsoft Visual C++ Redistributable for Visual Studio 2017](https://github.com/bitbeans/SimpleDnsCrypt#prerequisites)?

Maybe minisign is not able to verify the installer.
Are there any logs (Error or Warn) in the **logs** folder?

**Comment by mardetanha** [comment]
@bitbeans this is clean install on windows 10 and I don't have anything installed on it (microsoft C++ . I don't get any errors or anything but it takes up to 5 minute to start. (just for headsup I am from iran and ISP tend to mess with dns  but never had this issue before)

**Comment by bitbeans** [comment]
@mardetanha so can you install the Redistributable package and try again?

**Comment by mardetanha** [comment]
@bitbeans I will

**Comment by mardetanha** [comment]
@bitbeans reinstalled the packages and seems the issue has been fixed, I will check tomorrow again, and will update here, Thanks for swift response

**Comment by bitbeans** [comment]
you are welcome :)
