### ISSUE TITLE
New Features Request

### ISSUE THREAD

**Issue by zero77** [bitbeans/SimpleDnsCrypt#26]
Can you add a DNS benchmark facility to find the fastest DNS available to you. 

Can you add more information about each DNS option. 

Can you add a check option to make sure your DNS traffic is being rooted correctly. 

Can you also add a traffic tab so you can view life DNS requests being made.

**Comment by dnscryptme** [comment]
> Can you add a DNS benchmark facility to find the fastest DNS available to you.

Does this help: [Global DNSCrypt resolver map](https://dnscrypt.me:8443/map.html)?

**Comment by zero77** [comment]
This is good but I meant more like one of these grc.com/dns/benchmark.htm or code.google.com/p/namebench but built in to a separate tab in the software.

**Comment by bitbeans** [comment]
> Can you add a DNS benchmark facility to find the fastest DNS available to you.

i think this is out of scope for the moment, sorry.

> Can you also add a traffic tab so you can view life DNS requests being made.

You can use the log plugin for this.
