### ISSUE TITLE
dnscrypt-proxy detected as malware

### ISSUE THREAD

**Issue by kravietz** [bitbeans/SimpleDnsCrypt#262]
The dnscrypt-proxy.exe binary bundled with SimpleDnsCrypt 0.5.2 is being detected as malware by 11 antivirus engines on VirusTotal. I *suppose* this is a false positive but this will definitely impair user experience for most people installing SimpleDnsCrypt.

https://www.virustotal.com/#/file/2e760fd512781c532b6a3d9c0a26816d01a8c89a10b6f046e958d184eecdc232/detection

The dnscrypt-proxy binary (2.0.6 win64) downloaded from https://github.com/jedisct1/dnscrypt-proxy/releases (2.0.6) is classified as safe by VirusTotal.

**Comment by evilvibes** [comment]
https://github.com/jedisct1/dnscrypt-proxy/issues/205

**Comment by bitbeans** [comment]
@kravietz nothing i can do, users must report this ... :)

**Comment by jedisct1** [comment]
Report this here: https://www.bitdefender.com/support/what-to-do-when-bitdefender-detects-legitimate-applications-491.html

(I think reporting this to Bitdefender is enough and other software flagging this also use the Bitdefender engine)

**Comment by kravietz** [comment]
The newer version is reported as safe so the easiest solution is to upgrade. For the older version I'd suggest everyone who gets here from Google goes to https://www.virustotal.com/#/file/2e760fd512781c532b6a3d9c0a26816d01a8c89a10b6f046e958d184eecdc232/community and votes **Safe**.
