### ISSUE TITLE
When SimpleDNS back using 2 DNS Service?

### ISSUE THREAD

**Issue by benyaminl** [bitbeans/SimpleDnsCrypt#263]
Hello, I would like to ask about 2 dns service like on version 0.4 before. That's quite convenience, because when one or the other down, the dns still running, so I don't need to check the dns service. But, seems the new one doesn't support it. It really suck. Is there anyway you would support it again? Thanks

**Comment by bitbeans** [comment]
@benyaminl dnscrypt-proxy 2.x can use more than one resolver. https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml#L22
