### ISSUE TITLE
SimpleDnsCrypt没有用CDN DNS吗?

### ISSUE THREAD

**Issue by asdyjd** [bitbeans/SimpleDnsCrypt#264]
有些DNS服务器会根据用户的IP,返回离用户距离最近的DNS结果.
但是SimpleDnsCrypt不会.
我在中国,访问有些中国网站时,SimpleDnsCrypt会把域名解析为外国IP,导致网络速度变慢了.

能做一些改进吗?

**Comment by bitbeans** [comment]
@asdyjd english please :)

**Comment by tinyboxvk** [comment]
@bitbeans Translation: Some DNS servers will return an IP depending on where the user is. But SimpleDNSCrypt does not support this feature. Can you please make some modifications to the software?

@asdyjd This feature depends on the implementation of the DNS server you are using. It's not up to SimpleDNSCrypt to decide which IP is in the DNS response. SimpleDNSCrypt is simply an implementation of the DNSCrypt protocol. 返回IP跟你选的DNS服务器相关，SimpleDNSCrypt只是负责加密DNS流量。
