### ISSUE TITLE
Linux SimpleDNSCrypt and DNS-over-HTTPS

### ISSUE THREAD

**Issue by cnoizem** [bitbeans/SimpleDnsCrypt#265]
Hi, I'd like to know if you have any plans to port your software to Linux; I personally think it would be extremely interesting to have a good gui to manage the dnscrypt-proxy 
Also, will you include in the future some kind of stats showing if the server is using Dns-over-https? The reason I'm asking it seems a couple of servers are using the dns-over-https experimental and it could be confusing to know if the server is/isn't using the dnscrypt protocol

Thank you

**Comment by bitbeans** [comment]
not for now :)
