### ISSUE TITLE
cannot install on Thinkpad Windows 10 Pro x64?

### ISSUE THREAD

**Issue by ingber** [bitbeans/SimpleDnsCrypt#266]
We have 2 Thinkpad Carbon X1 Touch PCs running the latest Windows 10 x64 Pro (Build 17115.rs4_release.180302-1642).

On one PC, installation repeatedly fails.  It has failed on this PC each of several times I've tried the past few months.  I attach snapshots of what I see.

![capture1](https://user-images.githubusercontent.com/796522/37518847-2b327596-28d4-11e8-87bd-28443a728aa7.JPG)
![capture2](https://user-images.githubusercontent.com/796522/37518849-2b6226b0-28d4-11e8-8d0f-ac65105d5bac.JPG)

**Comment by bitbeans** [comment]
@ingber Maybe you can try to start the installer with verbose logging:

Open a CMD or PowerShell with administrative rights and run:
`msiexec /i SimpleDNSCrypt64.msi /l*v debug.txt`

**Comment by ingber** [comment]
Thanks for the suggestion.  This problem happens on just one of our Thinkpads, but neither PC has had any other problems with msi files.

Right now I'm running the command line dnscrypt-proxy-win64-2.0.6 which seems to be fine on both PCs.

Lester
