### ISSUE TITLE
Unbinding of local host is not recognized

### ISSUE THREAD

**Issue by HXmniDhWNevihHm7PwVyN4Knvt9yQrRt** [bitbeans/SimpleDnsCrypt#267]
System: W7_64 Prof and V053 of SDC.
This bug occurred, when I performed a repair of the driver for the Ethernet Adapter. After that everything was reset to the default DHCP configuration. That is not the problem, but the lack of a warning message from SDC stating that the encrypted connection to the DNS resolvers is broken. Even in the GUI there is not a single hint for that failure. I consider this to be a serious security breech, because there might be an attack that switches DNS configuration and the user gets no warning.
but nevertheless many thanks for Your great work.
Andreas

**Comment by bitbeans** [comment]
Manually changing the network card requires administrative rights (so this is the smallest problem with a call). If SimpleDnsCrypt is restarted, the change of the network card should be detected.

**Comment by HXmniDhWNevihHm7PwVyN4Knvt9yQrRt** [comment]
But having in mind that software like virus-scanner or malware sometimes change the DNS configuration, it wouold be a nice ( and imho important) feature, to monitor it and give a warning in case of configuration change.
Regards
Andreas
