### ISSUE TITLE
No resolvers on the list

### ISSUE THREAD

**Issue by ahmeed-dhon** [bitbeans/SimpleDnsCrypt#269]
It is already 2 days and there is no resolver listed
already reinstall SimpleDnsCrypt but still no resolver
[screenshot here](https://i.imgur.com/GfRzbbU.png)

**Comment by BillyC05** [comment]
Got the same problem. I noticed it just crashes when i try to start the service

**Comment by jedisct1** [comment]
Replace `fallback_resolver = '9.9.9.9:53'` with `fallback_resolver = '114.114.114.114:53'` in the configuration file.

**Comment by ahmeed-dhon** [comment]
which config is that? I've look at `SimpleDnsCrypt.exe.config` but there is no option for `fallback_resolver`

**Comment by evilvibes** [comment]
In the .toml

**Comment by ahmeed-dhon** [comment]
thanks for the help
