### ISSUE TITLE
[Request] Great app but it could use a way to add blacklists directly from query.logs

### ISSUE THREAD

**Issue by marxenegls** [bitbeans/SimpleDnsCrypt#270]
I love the app , i've used the cli version of dnscrypt for years on all platforms today i installed SimpleDnsCrypt on Win7 and it works very well, spotted all my nics gave me option to chose resolvers with varying options ..great stuff , Thanks 
 An easy way to either be able to access the logs directly - the link fails to open the directory or to select them from the running query.logs -it should be able to scroll down the query.logs, it doesn't and pointing to the scroll down arrow selects window adjustment.The only way is to latch on the scroll tab on the side and pull it up/down. 
I could see tons of ads links flashing by but too difficult to add one by one to blacklist. Also there isn't a minimizing to tray option which would free up desktop and still have it running .  
There's a ddwrt/packages here on github with adguard lists and tons of other features that you might be able to integrate . just a thought 
Thanks again .

**Comment by bitbeans** [comment]
@marxenegls thank you for the feedback!
Tray: https://github.com/bitbeans/SimpleDnsCrypt/issues/125
Multiselect: https://github.com/bitbeans/SimpleDnsCrypt/issues/271
