### ISSUE TITLE
Add easter eggs

### ISSUE THREAD

**Issue by jedisct1** [bitbeans/SimpleDnsCrypt#272]
AFAIK, this app doesn't have any easter eggs. This is sad. Especially a few days before easter.

**Comment by sergeevabc** [comment]
I would better focus on optimizing memory consumption.
Even without blacklist enabled it takes ~140 MB.

**Comment by AnthonyBe** [comment]
Not that I'm a 'bah hambug' type, but I agree, given that there is one developer and quite a few open issues affecting core functionality, reliability, and stability, I also feel time would be better spent here than on easter eggs.

**Comment by evilvibes** [comment]
You both can always put some of your time into it!

Roll out the Easter eggs!

**Comment by sergeevabc** [comment]
Let barbers, chefs, and policemen put off scissors, knifes and batons to create a code, while you expect a haircut, a salad and a protection, right? Cut the bullshit: our society is based on the division of labour, polymaths are rare beasts. Once a programmer decides to do more than his daily share (to improve the world o’nights or just to brag about charity in résumé) — rest assured, the world will respond. If efforts are aligned with real necessities, then users will praise the contribution and glorify its creator. Feedback via issue tracker is the way to avoid wishful thinking and become aware of ambiguous, broken and missing points which then affect a road map and priorities — and that is what most mere users, myself included, put time into.
