### ISSUE TITLE
DNScrypt Service won't running

### ISSUE THREAD

**Issue by hexaholix23** [bitbeans/SimpleDnsCrypt#273]
Hello, I already use SimpleDNScrypt for long time but today the service cannot be start I try to reinstall it but it's not working. The slider won't turn green like always. Can't you look into it? Thanks

![untitled-1](https://user-images.githubusercontent.com/37743071/37865348-f3be2a48-2fad-11e8-948d-0446ee44020d.png)
![untitled-2](https://user-images.githubusercontent.com/37743071/37865349-f44bbc3c-2fad-11e8-8285-412e717884a7.png)

**Comment by hexaholix23** [comment]
Oh and I try to change the fallback resolver to 114.114.114.114:53 and it's still get the same message

![untitled-3](https://user-images.githubusercontent.com/37743071/37865435-f9a330ba-2fae-11e8-9a78-1b2f9123c2f8.png)

**Comment by jedisct1** [comment]
Are you in Indonesia?

**Comment by hexaholix23** [comment]
@jedisct1 Yes yes, I'm in Indonesia

**Comment by jedisct1** [comment]
Unfortunately, the dnscrypt website has been blocked by the government, so the list cannot be downloaded from it any more :(

Maybe the download location can be changed to `https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md`, if Github is not blocked (yet).

**Comment by evilvibes** [comment]
@jedisct1 If needed i can host the files from my website.

**Comment by jedisct1** [comment]
And your website will get blocked as well :/

**Comment by hexaholix23** [comment]
@jedisct1 for now it's works! I changed it to https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md, hope it gonna last

@evilvibes Maybe I'll take the offer if the government make another block :(

**Comment by jedisct1** [comment]
One thing I can implement is the ability to have multiple URLs for a given source. They will be tried in random order.

This will allows having multiple mirrors for these files, which will greatly improve resiliency.

**Comment by evilvibes** [comment]
Alternative url can be found here

[evilvibes.com/list/](https://www.evilvibes.com/list/)
