### ISSUE TITLE
dnscrypt incompatible on severals security suite software, tested on two laptops

### ISSUE THREAD

**Issue by monstertruckpa** [bitbeans/SimpleDnsCrypt#274]
the .msi installer runned perfectly , After of completting installation dnscrypt launcher experimented problems with security software HitmanPro.Alert and Voodooshield, someone could explain what happens. What have i do, is it false positive? There I show you images.
![1](https://user-images.githubusercontent.com/15215547/37873547-bde83f6e-2fd3-11e8-9edb-0eb834495470.png)
![2](https://user-images.githubusercontent.com/15215547/37873548-be0bec16-2fd3-11e8-85c8-669a6c96badc.png)

**Comment by monstertruckpa** [comment]
The program is calling to "C:\windows\system32\conhost.exe" to work, without conhost.exe the SimpleDnsCrypt.exe crash instantly with error on desktop screen.  conhost.exe on virustotal/communityscore has bad reputation because it is of doubtful activity or unknow, although the file appears without signature, it seems clean of virus... https://www.virustotal.com/#/file/046f7a1b4de67562547ed9a180a72f481fc41e803de49a96d7d7c731964d53a0/community

**Comment by nalyDylan** [comment]
it seems likely to me that some antiviruses will think any program that changes the DNS is a virus.

There is a common tactic in malware to redirect your internet searches, i.e. `google.com` will instead be resolved to a similar looking webpage that still polls Google for search results, but puts 4-5 ads on the page so the malware creator generates some ad revenue for themselves. Obviously dnscrypt is not doing this, but, it's impossible for the antivirus to tell the difference.

it's entirely a false positive though, conhost.exe is part of Windows, it means Console Host and is literally just the GUI front end for the command prompt.

In this case it appears that the antivirus is blocking the main dnscrypt screen from launching the dnscrypt-proxy service, which is the main component of dnscrypt

**Comment by bitbeans** [comment]
nothing i can do here
