### ISSUE TITLE
Query Log view scrolling issue

### ISSUE THREAD

**Issue by rkwk** [bitbeans/SimpleDnsCrypt#275]
In Query Log view, the scroll bar causes the whole window contents to be scrolled rather than only the control containing the log.

**Comment by B00ze64** [comment]
Yop, I was gonna report this too, even took screenshots but I guess they aren't really necessary. What it does here is that it ALSO grows the window beyond the height of the screen, and when I resize, it does this weird thing where the entire inside of the window is made scrollable, not just the listview.

**Comment by bitbeans** [comment]
should be fixed :)
