### ISSUE TITLE
0.5.3 - "Open log directory" button does nothing

### ISSUE THREAD

**Issue by AnthonyBe** [bitbeans/SimpleDnsCrypt#276]
I'm running Simple DNSCrypt 0.5.3 on Windows 10 x64 1790 (16299.309 - current release build with all Windows Updates as of 28 Mar 2018).

When I click on the "Open log directory" button in the Simple DNSCrypt app title bar, nothing happens. When I hover over it, it lights up and I get the tooltip label, but clicking it does nothing.

The other buttons (About and Settings) are working fine.

Only non-standard aspect to my install is I changed the default installation path from:
C:\Program Files (x86)\bitbeans\Simple DNSCrypt
to
C:\Program Files (x86)\Simple DNSCrypt

Any idea why this would be the case?

**Comment by bitbeans** [comment]
@AnthonyBe no logs == no directory :)

**Comment by AnthonyBe** [comment]
I'm not sure why you are assuming I have no logs?

In the **C:\Program Files (x86)\Simple DNSCrypt\dnscrypt-proxy** folder is the **query.log** and **blocked.log** so am I incorrect in assuming that clicking on the "Open log directory" button should open an explorer window at **C:\Program Files (x86)\Simple DNSCrypt\dnscrypt-proxy** ?

**Comment by bitbeans** [comment]
@AnthonyBe only errors or warnings of SimpleDNSCrypt are written there

**Comment by AnthonyBe** [comment]
Ahh.. now that I've finally encountered an error (I guess I should be happy it's taken this long :)) it is working and opening the \logs folder.

Another option might be to simply create an empty \logs folder as part of the install so the button always operates and at least opens an empty logs folder if there have not been any errors/warnings?
