### ISSUE TITLE
Changing the DNS Servers filtering does not un-select entries

### ISSUE THREAD

**Issue by B00ze64** [bitbeans/SimpleDnsCrypt#277]
Good day.

I've been playing with SimpleCryptDNS for a week. Turns out it has several bugs and is restrictive enough that I will not really be using it now that I've got the proxy running. But I would LIKE to be able to use it because it does something I cannot do easily, which is to decode the sdns:// strings and sort the servers by flag (e.g. Does not keep logs, has no filters, etc.) So I will report a bunch of bugs and wishes today. This is my first bug ->

**Issue**: Going to a more restrictive set of server filters does not update server_names= to remove servers that no longer fit the selected filters.

**Steps to reproduce**: Turn off all server filtering (Only Servers With...) then switch to the servers tab and select a bunch of servers. Apply, so that server_names= is updated in the toml file. Go back to the main tab and enable all filtering options. Go back to the server list - it now shows only the servers that match the selected filters. Select a server or unselect one, so that the APPLY button makes sense, and apply. Have a look at server_names= and see that it still contains servers that no longer match selected filtering rules.

**Why this might be a problem**: If you have a look at the proxy logfile, you will see that when server_names= is specified, the proxy will ping ALL the servers listed in the variable; it appears to ignore the require_xxx rules in the toml file if server_names is specified. So it is important to prune the no longer acceptable servers from server_names=.

Regards,

**Comment by bitbeans** [comment]
@B00ze64 thank you for reporting this! I can confirm this bug.
