### ISSUE TITLE
General logfile issues

### ISSUE THREAD

**Issue by B00ze64** [bitbeans/SimpleDnsCrypt#278]
Good day.

I have several issues with logging and SimpleDNSCrypt.

1. There is no way to specify the proxy log level and logfile location, we have to edit the toml file. When I first ran SimpleDNSCrypt, the proxy managed to fail to start and I ended-up with [WARN] and [ERROR] files in the SimpleDNSCrypt "logs" folder. Since then I have not seen any logs written there. In fact I have no idea how these 2 files could ever have been created - someone appears to have read the proxy's logfile and split it into 2 files. I now use loglevel=0 and I specify a path for the logfile, so this splitting no longer works. Suggest that splitting the logfile is not really necessary and makes debugging harder; I personally do not want the log split into different files for the different log levels.

2. I would like to use Automatic log files rotation, but every time I run SimpleDNSCrypt, it strips all the options from the toml file that it does not understand. Feature-Request: Do not strip unknown options.

3. Support TSV: SimpleDNSCrypt has a tendency to ask for LTSV logs, and for the Query log that means that the timestamp is not humanly readable. I want to keep several days of query logs, but with LTSV they are meaningless; I would like to keep them as TSV where the timestamp is readable. Speaking of Query log, a button for loading the entire log would be nice, instead of only showing new entries appearing after the Query log TAB is selected in SimpleDNSCrypt. And finally there is a weird bug with the Query log TAB and the window and the scrollbar, but there is already a bug opened for his here on Github.

4. When we enable the blocked-requests log, you write log_file = "blocked.log" in the toml file. Same for the query log, SimpleDNSCrypt stores it in the proxy's folder by default (this time with full path). Why is there a LOGS folder in SimpleDNSCrypt's base folder if no logs ever go there? Also, SimpleDNSCrypt creates TWO empty "blocked.log" files when this is enabled, one in SimpleDNSCrypt's base folder and one in the proxy's sub-folder.

I think that covers the logfile issues.
Regards,

**Comment by B00ze64** [comment]
Wow, you don't erase "unknown" fields from the TOML file anymore! At least my log archiving entries are staying put when I run SimpleDNSCrypt! Woohoo! thank you :+1:

**Comment by B00ze64** [comment]
Hi Christian.

I have played some more with SimpleDNSCrypt. I see that you now respect ALL logfile locations! :+1:  

You still require labelled-tsv, but I was thinking about that and if you were to add a button to load the entire query log and the blocked log, then I guess I would not need to read them by hand, although I do wish Excel was able to load LTSV, wouldn't need anything from SimpleDNSCrypt then. You could also add a tab for the NX log (you've all the other logs covered).

Anyway, you worked hard on SimpleDNSCrypt, thank you very much!

**Comment by bitbeans** [comment]
See #325 :)
