### ISSUE TITLE
[Request] Silent Updates

### ISSUE THREAD

**Issue by zero77** [bitbeans/SimpleDnsCrypt#282]
When SimpleDnsCrypt updates, can you please silently run the installer instead of using the installer UI.
Thanks

**Comment by bitbeans** [comment]
👍

**Comment by Rictusempra** [comment]
@bitbeans I think you need to check #283 first

**Comment by zero77** [comment]
@bitbeans 
This may be of help, https://github.com/Squirrel/Squirrel.Windows
