### ISSUE TITLE
Service disabled

### ISSUE THREAD

**Issue by olino** [bitbeans/SimpleDnsCrypt#283]
Hello,
When I change wifi connections I have to re-enable dnscrypt service.
( more precise explanation-when I move between the two countries and I change wifi I have to re-enable dnscrypt service.)
Also settings are still not remembered after update.
Thanks

**Comment by DaBomby** [comment]
https://github.com/bitbeans/SimpleDnsCrypt/issues/251

**Comment by bitbeans** [comment]
Settings should be remebered for now
