### ISSUE TITLE
Add 1.1.1.1 to Available Resolvers

### ISSUE THREAD

**Issue by DaBomby** [bitbeans/SimpleDnsCrypt#284]
Is it possible to add the 1.1.1.1 and 1.0.0.1 servers to the list of available resolvers? More details about the Cloudflare system here: https://blog.cloudflare.com/dns-resolver-1-1-1-1/.

Thanks in advance.

**Comment by jedisct1** [comment]
This was added 2 weeks ago. Just choose "Cloudflare" in the list.

**Comment by DaBomby** [comment]
@jedisct1 Thanks for the update. I had searched for closed issues about this and could not find anything prior to posting. Are resolver updates posted or listed somewhere else?

**Comment by jedisct1** [comment]
The public-resolvers file can be review here: https://dnscrypt.info/public-servers

And it's maintained in this repository: https://github.com/DNSCrypt/dnscrypt-resolvers

**Comment by DaBomby** [comment]
This is great! Thanks. I will close this now.
