### ISSUE TITLE
Add 9.9.9.9 to Available Resolvers

### ISSUE THREAD

**Issue by DaBomby** [bitbeans/SimpleDnsCrypt#286]
Is it possible to add the Quad9 (9.9.9.9 and secondary) servers to the list of available resolvers? More details about the Quad9 system here: https://quad9.net/faq/#Does_Quad9_support_DNS_over_TLS.

Thanks in advance.

**Comment by jedisct1** [comment]
Quad9 doesn't support DNSCrypt yet, but they are working on it.

**Comment by DaBomby** [comment]
Similarly related: https://github.com/jedisct1/dnscrypt-proxy/issues/68

**Comment by DaBomby** [comment]
One more related: https://github.com/DNSCrypt/dnscrypt-resolvers/issues/1

**Comment by DaBomby** [comment]
Should we leave this open to track if or when Quad9 will support it or should this be closed?

**Comment by jedisct1** [comment]
Leaving it open is useless.
