### ISSUE TITLE
Selecting a single resolver is semi-broken and cumbersome

### ISSUE THREAD

**Issue by Zero3** [bitbeans/SimpleDnsCrypt#288]
On the Resolvers tab in the GUI, I deselected Automatic Mode and selected a single resolver. But when clicking apply settings, the GUI throws away by selection and instead selects every single resolver.

Also, it seems like there is no easy way to deselect all the wrongly selected resolvers. So I had to manually click on every other resolver than the one I wanted, which I think is unnecessarily cumbersome. I think the UX could be improved here.

**Comment by bitbeans** [comment]
@Zero3 thank you for reporting this. you don`t need to unselect all. just switch the tab. its a bug in the UI.

**Comment by B00ze64** [comment]
Hmmm, #292 might be the same problem...
