### ISSUE TITLE
Cannot Change Fallback Resolver

### ISSUE THREAD

**Issue by runrun63** [bitbeans/SimpleDnsCrypt#289]
I am not able to change the Fallback Resolver. Whatever I change it to it reverts to 9.9.9.9.

**Comment by runrun63** [comment]
Manually changed Fallback Resolver in dnscrypt-proxy.toml. Is this OK? Thanks.

**Comment by bitbeans** [comment]
@runrun63 you tried it with a port?

**Comment by user8446** [comment]
It appears that it reverts back if you actually close and reopen (not close to tray)

**Comment by NAVrasZ** [comment]
Same here.
Also I can't enable query log, stuck at "waiting for DNS queries" and no log is created in the directory.
