### ISSUE TITLE
Error after update 0.2.8 -> 0.2.9

### ISSUE THREAD

**Issue by sluTTYusr** [bitbeans/SimpleDnsCrypt#29]
![2016-01-22_112203](https://cloud.githubusercontent.com/assets/11618119/12508347/bad2ac86-c0fb-11e5-89fc-1b706e8bb947.jpg)
![2016-01-22_112223](https://cloud.githubusercontent.com/assets/11618119/12508350/bf3c8f08-c0fb-11e5-8def-c2a509dfda0a.jpg)

After the update 0.2.8 -> 0.2.9 I get these error messages.
A new install did not help. Had to uninstall and go back to 0.2.8.

**Comment by bitbeans** [comment]
See #24 this should fix the issue.
I will include the VCR in the next release

**Comment by sluTTYusr** [comment]
Thanks, that did it.
Should have checked the closed issues, too.
