### ISSUE TITLE
Run On Different IP? - Work With BIND9

### ISSUE THREAD

**Issue by war59312** [bitbeans/SimpleDnsCrypt#290]
Hi,

Would be great if I could run SimpleDNSCrypt on another IP, besides 127.0.0.1.

In an older version, I was able to run the second service which ran on 127.0.0.2.

Worked great, as BIND 9 runs on 127.0.0.1 and forwards to 127.0.0.2.

Just need both to play nice together again in Windows 10.

Thanks,

Will

**Comment by bitbeans** [comment]
fixed in 0.5.4 i think :)

**Comment by war59312** [comment]
Thank you very much.

Confirmed working in 0.5.6 👯‍♂️
