### ISSUE TITLE
Updating SimpleDNSCrypt overwrites TOML file

### ISSUE THREAD

**Issue by B00ze64** [bitbeans/SimpleDnsCrypt#291]
Hi BitBeans.

Updated to version 0.5.4 just now, and just in case, I made a backup of my TOML file beforehand. That was a good thing, since installing 0.5.4 overwrote the file - my list of servers=, logfile names, etc, all gone. Surprised no one else noticed.

That it's! Best Regards,

**Comment by TroudhuK** [comment]
Woooooooow I just have seen that. So since 30/03 I'm naked, I now understand why some Windows Update things were automatically installed, my computer was rebooted, my firewall did a lot of unusual alerts and so on. So we have to check that TOML because (trusted) automatic things overwrite it.

**Comment by bitbeans** [comment]
fixed
