### ISSUE TITLE
System service is not removed when uninstalling SimpleDnsCrypt

### ISSUE THREAD

**Issue by Zero3** [bitbeans/SimpleDnsCrypt#295]
The `DNSCrypt client proxy` system service is not removed when uninstalling SimpleDnsCrypt.

OS: Windows 7 x64

**Comment by cobafesbuk** [comment]
I experienced this too on Windows 10 1709 x64.
I need to remove the service manually after the uninstall.

**Comment by bitbeans** [comment]
@Zero3 @cobafesbuk also with the current version?

**Comment by Zero3** [comment]
@bitbeans I don't know. I was uninstalling SimpleDnsCrypt because of all the other bugs I ran into. So I'm afraid I don't know whether this problem is resolved in the current version.

**Comment by bitbeans** [comment]
okay
