### ISSUE TITLE
Uninstalling SimpleDnsCrypt leaves internet connection broken with missing DNS servers

### ISSUE THREAD

**Issue by Zero3** [bitbeans/SimpleDnsCrypt#296]
When I installed SimpleDnsCrypt, it removed my existing DNS server settings for my internet connection without asking. This is bad enough. But even worse, when uninstalling, it left them in this invalid state:

![image](https://user-images.githubusercontent.com/82504/38436028-cc42ffb8-39d3-11e8-9346-6cab8e1925eb.png)

My internet connection was thus left broken, and required me to manually put back valid DNS server settings.

OS: Windows 7 x64

**Comment by bitbeans** [comment]
@Zero3 is this still relevant in the newest version?

**Comment by Zero3** [comment]
@bitbeans I don't know. I ran into too many issues with SimpleDnsCrypt, so I uninstalled it (as you can guess from this bug report).
