### ISSUE TITLE
Broken/Incompatible Resolvers/Automatic Mode

### ISSUE THREAD

**Issue by 47Haven** [bitbeans/SimpleDnsCrypt#298]
Back when there's no automatic mode, i only uses like, 2 or 3 resolver, mainly Sotysiak and 2 other that's no longer available in the current version. Now that there's automatic mode, rather than solve my problem and automatically selects the fastest and working resolver, all it did was made thing worse. Slower internet connection, sometimes up to just a crawl, inconsistent availability, mainly with reddit, since sometimes it works, sometimes it doesn't, and sometime it even blocks my internet connection, to the point that i can't even access site that isn't blocked in the first place.

Does every resolver work? Is there some obsolete resolver (P.S. I used to think that the d0wn resolvers is labelled that since it's, well, down)? Or is there a region restricting thing going on? I live in Indonesia, so perhaps some of the resolver is just too far for it to work, if that make any sense? Would love to have some method to check whether or not the resolver would work though

**Comment by ledlamp** [comment]
#470 related, turn on and monitor the query log to see what resolvers are causing problems.
