### ISSUE TITLE
web information about requirments wrong

### ISSUE THREAD

**Issue by spamkutu** [bitbeans/SimpleDnsCrypt#299]
Its show as Prerequisites
At least one system with Windows 7 SP1 and the installation of. NET Framework 4.6.1 is currently required.

Its show the some requirments on chocolately too
as its show 4.6.1 its very well for us becouse we cant install 4.6.2 and futher.

So please complie it for that .net 4.6.1 it will be very well since most of them download and use 0.4.2 (with dns crypt v1) or atleast change simple brief requirment!! but you must be know we all waiting .net 4.6.1 compatible version please complie latest one with that!!

**Comment by bitbeans** [comment]
it is using 4.6.1
