### ISSUE TITLE
Add support for secondary resolver

### ISSUE THREAD

**Issue by bitbeans** [bitbeans/SimpleDnsCrypt#3]
We need to wait for the new dnscrypt-proxy release

**Comment by dpelletier360** [comment]
Is this still being worked on?

**Comment by bitbeans** [comment]
i am still waiting for an update (dnscrypt-proxy) :)

**Comment by ngenx** [comment]
cmd /c nssm install dnscrypt2 "C:\Program Files (x86)\bitbeans\Simple DNSCrypt\dnscrypt-proxy\dnscrypt-proxy.exe" --local-address=127.0.0.2:53 -R okturtles --ephemeral-keys

**Comment by bitbeans** [comment]
see https://github.com/jedisct1/dnscrypt-proxy/issues/418
