### ISSUE TITLE
SimpleDnsCrypt every start trying to install VC++

### ISSUE THREAD

**Issue by ghost** [bitbeans/SimpleDnsCrypt#305]

**Comment by dns** [comment]
This also happen to me.

**Comment by marxenegls** [comment]
i have similar issue everything was fine last i used it but after an update and reboot  it doesn't launch anymore instead it initiates a whole download procedure and it's doing it on both machines i have it installed. Service was still running but obviously it weren't resolving in the intended manner , i noticed some sites refused access before stopping the service manually . bummer i really liked the app .. considering using the cli version and set up service and forget about it ,... the eye candy : \

**Comment by bitbeans** [comment]
Maybe you can install it manually. minisign-net needs this to validate the updates
