### ISSUE TITLE
A short holiday

### ISSUE THREAD

**Issue by bitbeans** [bitbeans/SimpleDnsCrypt#306]
I just wanted to let you know that I am on a short holiday until May 7th!

Afterwards i will **continue** with fresh energy!

Sorry! 😁 

- Chris @bitbeans

**Comment by jedisct1** [comment]
Enjoy your vacation, Chris!

**Comment by B00ze64** [comment]
I kinda figured you were taking a break ;-)
Sorry for bombarding you with requests and bugs.
Have a good break!
