### ISSUE TITLE
SimpleDnsCrypt wakes second GPU from ULPS sleep

### ISSUE THREAD

**Issue by gashtal** [bitbeans/SimpleDnsCrypt#307]
I have two AMD GPUs in Crossfire configuration with ULPS enabled so that the second GPU is completely turned off when no 3D workload is running. For some reason, as soon as I start SimpleDnsCrypt, the program wakes the second GPU from sleep until it is closed again. This results in significant waste of power since the app is supposed to run all the time, keeping the second GPU as long as my machine is on. I believe this could be because of hardware-accelerated decoding of the loading animation when the application is started. Is there anyway this problem could be avoided (e.g. disabling/removing the animation)? Note that disabling crossfire from the driver will not do anything in such case.

**Comment by bitbeans** [comment]
@gashtal sorry for the waste of power :P But i will not remove the animation.
