### ISSUE TITLE
Resolving suddenly stops

### ISSUE THREAD

**Issue by johncarterofmars** [bitbeans/SimpleDnsCrypt#31]
I am using 0.2.9 on Windows 7 Pro 64 bit. I have updated to the newest list of resolvers. It doesn't matter which ones I use, it seems many sites can't be resolved until I disable DimpleDNSCrypt. I can re-enable it again later but it will stop at random times. I have chosen 10 different servers to test and get the same results. Does anyone have any suggestions? Thank you

**Comment by bitbeans** [comment]
Please check you network card settings (127.0.0.1). 
You also can check if the **dnscrypt-proxy** service is running.

**Comment by johncarterofmars** [comment]
Thank you Yes the service is running and the IP for Primary DNS is 127.0.0.1. As i mentioned, everything will work for random periods of time and then suddenly DNS will stop resolving. So i have to disable the interface inside Simple and then DNS will work on the network provided server. After which, if I set it back to Simple, then it will work again for random periods of time. I also notice that there are some sites that will never resolve with any DNSCrypt servers.

**Comment by bitbeans** [comment]
Hmm, sorry maybe it`s not a dnscrypt problem. Antivirus? Other services on your system?
