### ISSUE TITLE
query log not rotated automatically - file locked by SimpleDNSCrypt process

### ISSUE THREAD

**Issue by scubasunny** [bitbeans/SimpleDnsCrypt#312]
The query log is not rotated automatically as long as the Gui is running.
Closing the Gui and restarting the dns-crypt proxy service solves this issue.

**Comment by bitbeans** [comment]
@scubasunny since this is a "live log" and entries are to be displayed immediately, the file must remain open.

For example, if FileSystemWatcher is used, the entries are displayed with a delay. 

Simple DNSCrypt does not have to be started to use dnscrypt-proxy.
