### ISSUE TITLE
Windows 10: DNS requests using ISP unless cache flushed recently

### ISSUE THREAD

**Issue by paucp** [bitbeans/SimpleDnsCrypt#313]
Pretty much the title. Sometimes when testing on sites like https://www.dnsleaktest.com/ the ISP dns is there, with the DNScrypt servers, this happens until the dns cache is flushed (using "ipconfig /flushdns"), and for a while the ISP dns is not there, then it shows up again. 
This happens on both auto mode, and with resolvers selected.
The only way I found around this Is disabling Windows dns caching completly. I dont know if this affects DNSCrypt cache though.

**Comment by slyphnier** [comment]
its either your isp doing dns-cache-poisoning or unstable connection causing it 
when connection unstable (connection to dnscrypt servers cannot be reached), somehow it will use fall-back using straight dns which what in router/modem/AP

thats why when u disable dns-caching, which is always force to look for server address each request, it will look the address or if failed it will end up in connection-time-out

i am not sure the detail, but from my own experience/testing, it been like that

did u try change DNS to manual in router/modem ? 
it create something like 2nd attempt, and prevent more using your ISP dns by default

alternatively you can try change dns-cache setting with your browser, for firefox i think you need to change "network.dns.disablePrefetch"
chrome also have such setting iirc
