### ISSUE TITLE
Splash dialog won't go away

### ISSUE THREAD

**Issue by laymonage** [bitbeans/SimpleDnsCrypt#316]
Sometimes when I start Simple DnsCrypt, the splash dialog won't go away and I can't access the app, even though I can see that it's already open behind the splash dialog. If I kill the splash dialog using Task Manager, the app continues to run without any problem. This seems to happen when the app has successfully started before the splash dialog starts (is this even possible?).

**Comment by bitbeans** [comment]
@laymonage does that happen with the latest version? Which version of Windows do you use?

**Comment by bitbeans** [comment]
@laymonage thank you for the feedback!
