### ISSUE TITLE
DNSCrypt client proxy service terminated unexpectedly. (event 7034)

### ISSUE THREAD

**Issue by axzxc1236** [bitbeans/SimpleDnsCrypt#317]
This doesn't happen very often, but it happened three times in past 7 days.

SimpleDnsCrypt log doesn't show anything other than it failed to check for update, I only find things in Event Viewer, I don't see anything else logged in event viewer when DNSCrypt client proxy service terminated.

I saved events as attachment, I hope it is useful.
[SimpleDnsCryptCrashed.zip](https://github.com/bitbeans/SimpleDnsCrypt/files/2027299/SimpleDnsCryptCrashed.zip)

**Comment by Zabanya** [comment]
+1

**Comment by asian2017** [comment]
+1, win7

**Comment by TehBotolSosro** [comment]
The DNSCrypt client proxy service terminated unexpectedly.  It has done this 2 time(s).

had to manually turn on the service again for it to work or the browser cannot browse site

**Comment by bitbeans** [comment]
is there a problem with the pre-release version? eg: https://simplednscrypt.blob.core.windows.net/deploy/SimpleDnsCrypt/bin/x64/SimpleDNSCrypt_x64.zip

**Comment by TehBotolSosro** [comment]
Seems it was dnscrypt issue https://github.com/jedisct1/dnscrypt-proxy/issues/447

trying the pre-release will let you know if i encounter it again with the pre-release thanks

**Comment by TA2DF** [comment]
FYI: Until you correct the problem, the workaround I have found is as follows...

![dnscrypt_workaround](https://user-images.githubusercontent.com/8312068/40834016-3bdc33b8-6598-11e8-8c42-74579fcf91da.jpg)

**Comment by TehBotolSosro** [comment]
Well it's been 3 days since i use the pre release and haven't had any "DNSCrypt client proxy service terminated unexpectedly" error yet.

will report if any issue occur thx

**Comment by bitbeans** [comment]
@TehBotolSosro 0.5.5 is equal with the current preview.
I will cose this for now.

**Comment by DRSDavidSoft** [comment]
I'm on Windows Server 2016, and this have happened two times.
I hope @TA2DF's solution works.

**Comment by KrasnayaPloshchad** [comment]
dnscrypt-proxy 2.0.16 is released, so you'll no longer encountering this trouble.
