### ISSUE TITLE
Global Resolver

### ISSUE THREAD

**Issue by lintangtimur** [bitbeans/SimpleDnsCrypt#320]
how to use global resolver?
is from my phone connect to my pc ip address?

**Comment by bitbeans** [comment]
@lintangtimur just enable it in the advanced settings and enter your ip address from your computer in your phone

**Comment by SirusDoma** [comment]
Sorry to bring this up, but can you make it clear where should I put my computer ip address? I mean at which settings?

I can't make the global resolver work, I thought it works as simple as enable it

**Comment by brbergami** [comment]
Idk if people digs too much to solve this kind of things by their own, but as @SirusDoma said, the thing seems to be way _too simple_ to work for real. There's documentation explaining the process?

What I'm currently doing with my DD-WRT custom firmware on WRT3200ACM router is to use local DNS server, pointing DNSMASq to my computer's local IP, avoiding use resolv conf, and enabling global resolver on my computer. Is that simple... so simple it doesn't works. My pc can resolve addresses without issue, but the router is not routing new requests from computer. Does this need some kind of firewall rule on pc? Any port to specify (53?)
I've also tried to point my IP DNS server in my cellphone (under the same AP, no AP isolation), and it's not working too.. So no signs of Global resolver working for now.

Can you give some support on this? At least something to test outside the computer that the global resolver works.

Cheers

**Comment by fusionneur** [comment]
Is this actually working?

**Comment by fusionneur** [comment]
i see host is listening on 127.0.0.1:53, so how can i forward this port in router if it's not listening on 0.0.0.0? What am I missing?

**Comment by fusionneur** [comment]
It looks like a DNAT prerouting must be done https://unix.stackexchange.com/questions/570194/redirect-external-request-to-localhost-with-iptables

Maybe i'm wrong..

**Comment by fusionneur** [comment]
I managed to make it work
1. remove dnscrypt service first (or else there's a bug that i could not add listening addresses)
2. dnscrypt > advanced settings > manage listen addresses > add hosts's IP provided in router

![image](https://user-images.githubusercontent.com/7840350/113415956-f4848580-93c8-11eb-99fa-cf6848b2558e.png)
