### ISSUE TITLE
Microsoft is acquiring GitHub! What's next for SimpleDnsCrypt?

### ISSUE THREAD

**Issue by rddim** [bitbeans/SimpleDnsCrypt#321]
@bitbeans did you plan to move the code and the development of `SimpleDnsCrypt` to another resource like `GitLab`, `BitBucket` or something else? What's the users opinion/suggestion?

**Comment by bitbeans** [comment]
@rddim what`s wrong with Microsoft? I also use: C#, .NET, VS, ... :)

**Comment by rddim** [comment]
Hehe, what's not :) It is just interested situation for me, because we saw what happened with Skype and Nokia. M$ and "open source" are not the same thing.

**Comment by solariz** [comment]
@rddim they hugely improved on that compared to 10yrs ago. Let's see what's comming. No reason for panic attacks.

**Comment by bitbeans** [comment]
closed. time will tell. :)
