### ISSUE TITLE
Stop service! again and agian.

### ISSUE THREAD

**Issue by robin98** [bitbeans/SimpleDnsCrypt#322]
Hi,
From the past 2 years, I warmed you that software service stops automatically all the times.
now it's here! it's back from ver 0.5.5.
why you don't like to fix this problem?
it's simple, just check the activity of the service at fixed intervals, and then reactivate that if disabled!
of easier! you can find the bug[s] that caused this problem, and fix them. you know, this can't fix by itself! it can? so you must try to fix it.
you spent your time on it and I know it. I respect that; but don't let these funny problems and bugs turn your app into garbage!
thanks a lot!

**Comment by slyphnier** [comment]
so far there also person that didnt get the issue, i personaly didnt get dnscrypt-service stopped by itself 
probably once, when there is push-update, so its like waiting for user-respond

when there are people with issue and there that didnt, it not easy to detect what causing the issue
it not as simple as creating restart-script

check dnscrypt log and see what it said in there when the service stop running 
additionally u can also look at windows-event-viewer see if you can get any additional hint

also try excluding dnscrypt in your AntiVirus/anti-malware/internet security software
it possible those causing the issue, internet security software usually have their system to check secure connection or not, that can conflicting with dnscrypt

**Comment by nibaranmir** [comment]
Many times dnscrypt client proxy got terminated on its own after recent update.  I found a workaround which is pretty simple but effective. 
go to services, right click on DNSCrypt client, go to properties> recovery. then make restart the service for first failure,second failure & subsequent failures, apply it. 
![2018-06-25_19-21-38](https://user-images.githubusercontent.com/24574786/41854267-6509be40-78ad-11e8-972b-7bb75d89ab89.png)

Hope, it helps.

**Comment by Neo00001** [comment]
after recent update the dnscrypt proxy service is getting stopped every now & then. I've found a very easy workaround for it

go to services, then right click on DNSCrypt client proxy, then go to propeties>recovery>
![2018-06-25_19-21-38](https://user-images.githubusercontent.com/40570803/41855336-086ab0a6-78b0-11e8-87ff-b611485277f9.png)
 apply it. Hope, it helps.

**Comment by cybort** [comment]
The 53 port is already occupied causes service stop on my computer. Maybe you can have a check if there's any process using this port.

**Comment by glnzglnz** [comment]
I'm having the same issue and found a (so far) workaround.  
See my thread here at [https://github.com/bitbeans/SimpleDnsCrypt/issues/356](https://github.com/bitbeans/SimpleDnsCrypt/issues/356)
But I'm a NON-tech, and so I hope the underlying issue is identified and then solved by the tech-wizards here.
