### ISSUE TITLE
Not an issue, just a question regarding IP/domain names blocking

### ISSUE THREAD

**Issue by zymase** [bitbeans/SimpleDnsCrypt#33]
Hi,

Enjoying _Simple DNSCrypt_ which has just been smoothly updated from 0.29 to 0.30. Need to say this is an awesome application bringing the highest ease of use to _DNSCrypt_. Wonderfully carried out.

I hope I'm not trespassing the issue section when providing a simple question, aiming to use _DNSCrypt_'s ability to _block IPs & domains_

I read on https://dnscrypt.org/ that one of the plug-ins provided with the application allows to block IPs and domains recorded on a simple text file.As I've understood it the plug-in is _libdcplugin_ldns_aaaa_blocking.dll_ included with _Simple DNSCrypt_ of course.

This plug-in is not made directly accessible from _Simple DNSCrypt_ and I'd wish to know how to proceed manually to use it, as I haven't quite understood the procedure mentioned on https://dnscrypt.org/ paragraph _IP/domain names blocking_

Thanks in advance for your help.

**Comment by bitbeans** [comment]
Hey,

you are looking for the 

> libdcplugin_ldns_blocking 

plugin.
See: https://github.com/jedisct1/dnscrypt-proxy#plugins

This one is not yet part of Simple DNSCrypt.
But i will try to include it on a future release: #34

**Comment by zymase** [comment]
Thanks for the information, @bitbeans

**Comment by bitbeans** [comment]
Please update to 0.3.1. 
If you find some bugs, please let me know. :)

**Comment by zymase** [comment]
Hi bitbeans,

I've just had _Simple DNSCrypt_  (SDC) update to 0.3.1 and encountered issues with the new access to Block Addresses and Domains plug-in.

1- I've tested with block domains, that is included a domain in a text file and set SDC to that file, then confirmed - OK
2- Tested the domain, it was blocked - OK
3- Exited the browser (because of DNS cache), edited the BlockDomain txt file : removed the domain -> file empty
4- Issue #1 : DNS Primary Service was OFF and impossible to get it back to ON
5- Disabled the Block Addresses and Domains plug-in, returned to main settings and this time I could set DNS Primary Service back to ON
...
6- I thought then the issue was related to an empty BlockDomains txt file
7- Issue#2 : I tested again, with 2 domains this time, and this time neither domain was blocked (1 domain per-line) - Tested again by keeping only 1 domain : same issue. The plug-in seems now totally ineffective..

Thanks for your work. This was my testing report.

**Comment by bitbeans** [comment]
Okay thank you, i will check this out

**Comment by zymase** [comment]
@bitbeans do you have any idea of 0.4.0 release schedule? To be frank I'm wondering of another way of running DNSCrypt which would handle if not all included plugins at least IP & domain names blocking. I appreciate your work but on another hand I'm more and more looking forward to deploying DNSCrypt to its full potential- Thanks

**Comment by zymase** [comment]
For the sake of updated truth :=) I have to point out that latest version 0.3.6 of 'Simple DNSCrypt' handles both address and domain blocking plug-ins. No problem.

**Comment by Skrell** [comment]
Can someone PLEASE help me with the libdcplugin_ldns_blocking plugin?  I think I built the blacklist txt files correctly but when I look in dns.log I see all the IP that I blocked with [A]'s next to them...what does that mean?  I have a feeling it means they are NOT being blocked... :(

**Comment by zymase** [comment]
You can check if SimpleDNSCrypt's blocking plugin is effective by having a look in your registry,
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\dnscrypt-proxy\Parameters\

You should have a key named Plugins,
Plugins key should include localization set by you with SimpleDNCDrypt of your address and/or IP log files in the form:
libdcplugin_ldns_blocking.dll,--ips=C:\[PATH]\blacklisted-addresses.txt,--domains=C:\[PATH]\\blacklisted-domains.txt

If all corresponds then, IMO, the blocking plugin is operational. It's always possible to verify : take a valid IP or url (i.e.from your bookmarks) -- I say valid to be sure the url/ip is not handled by another blocking device such as the HOSTS file (url) or other blocker -- add the address to your blacklisted-domains file and/or the IP to your blacklisted-addresses file, empty the dns cache if running and if testing on IE or restart any other browser ... and test your dummy added address and/or IP ... that's what I did to be 100% sure, and all was fine, of course.

**Comment by Skrell** [comment]
So i do in fact have the registry setting so that is encouraging.  Can you please tell me what the [A] means in the dns.log file?

**Comment by Skrell** [comment]
UPDATE:  Ok looks like i proved it's working now.  As a side note, it appears as if you can mix IP and domain names in both blacklist files and the parser will still correctly work.  This is nice to know when you get combined lists of ip/domains that need to be blocked.

**Comment by zymase** [comment]
I have no idea what the [A] means in the dns log file, I don't log dns requests, but should I that I'd certainly be puzzled with this as you are. Does anyone have the answer?

> As a side note, it appears as if you can mix IP and domain names in both blacklist files and the parser will still correctly work. 
Now this is interesting and of course a question arises: why, in such a case, are there two seperate blacklists if one can handle both addresses and ips? Does anyone have the answer?

That's two questions! Good surfin' worldwide to all!

**Comment by bitbeans** [comment]
A: https://de.wikipedia.org/wiki/A_Resource_Record

**Comment by MacgyverJohnson** [comment]
Hello there @bitbeans 
Could you please help....
I went to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\dnscrypt-proxy\Parameters\Plugins
It has the following data
libdcplugin_ldns_blocking.dll,--ips=C:\Users\test1\DNScrypt\block ip.txt,--domains=C:\Users\test1\DNScrypt\block domain.txt
libdcplugin_logging.dll,C:\Users\test1\DNScrypt\dns.log
libdcplugin_ldns_aaaa_blocking.dll

But domains are not getting blocked....
my domain blocklist
0.0.0.0 umeng.com
0.0.0.0 dts.ushareit.com
or 
umeng.com
dts.ushareit.com
(tried with|without 0.0.0.0|127.0.0.1|)
simply not working... i tried pinging from cmd...they are not being blocked...but i can block them from host....I just wanted to tryout the awesome wildcard feature it says it has.
Thanks in advance
(Using windows 8.1x64 simpledns crypt 0.3.6....)
