### ISSUE TITLE
Installation fails due to insufficient privileges.

### ISSUE THREAD

**Issue by ZzzZombi** [bitbeans/SimpleDnsCrypt#330]
Here's the error:
https://i.imgur.com/UInSSeS.jpg

It happens even if I deselect the desktop and start menu shortcut options and I can't run the installer as administrator since, I guess, it's an .MSI file.

**EDIT:** It seems after I set that folder permissions and allow "Everyone" to access & write to that folder, installation completed. I installed it before on this system, never had any errors like this one.

**Comment by bitbeans** [comment]
sorry, can not reproduce this error for now. try the newest installer and feel free to re-open
