### ISSUE TITLE
OpenNIC filter in main configuration section

### ISSUE THREAD

**Issue by b9AcE** [bitbeans/SimpleDnsCrypt#332]
It would be nice if another filter was added in the main configuration section with "Only OpenNIC-servers" so that those that specifically want OpenNIC can check that alongside the other similar filters for e.g. "Only servers without logging" and thus still use "Automatic Mode" on the "Resolvers" screen instead of having to read through the list of servers and choose those labeled there as OpenNIC.

**Comment by bitbeans** [comment]
SDC only uses filters, provider by dnscrypt itself

**Comment by b9AcE** [comment]
Yes, of course I would not have asked for the improvement if it didn't already have and indeed even display the information to filter for, right next to the criteria currently available as filter-checkboxes.
