### ISSUE TITLE
Add forwarding and cloaking functionality

### ISSUE THREAD

**Issue by anon88841** [bitbeans/SimpleDnsCrypt#333]
By default dnscrypt-proxy has support for both forwarding rules and cloaking rules which work the same way hosts file does on Windows. 
SimpleDnsCrypt on the other hand lacks this feature and it's impossible to forward requests to a specific domain or IP address. Please consider fixing this issue.

**Comment by bitbeans** [comment]
@anon88841 feel free to test: https://simplednscrypt.blob.core.windows.net/deploy/SimpleDnsCrypt/bin/x64/SimpleDNSCrypt_x64.zip
