### ISSUE TITLE
Occasionally well known sites addresses can not be resolved, until Automatic Mode is disabled and re-enabled

### ISSUE THREAD

**Issue by AdKiller** [bitbeans/SimpleDnsCrypt#339]
At seemingly random intervals some sites that I frequently visit are not resolved and fail to open in the browser (Firefox)
If I disable Automatic Mode, and select a resolver like Cloudflare, it works right away.

Questions

How can I find out which is the crappy resolver that does work?
I have DNS cache enabled, shouldn't it be able to find the address in cache since it is site that I frequently visit?

Simple DNSCrypt 0.5.6 x64, dnscrypt-proxy 2.0.15
OS Windows 10 Pro

**Comment by martinsstuff** [comment]
I have the same issue BUT I have set it to Cloudflare only. (IPv4)

I you enable the Query log and check whenever this happens, do you see a "Server Error" message?

**Comment by rkwk** [comment]
I've seen the same. Occasionally (several times a day), with either automatic or manual mode, some queries are not resolved (SERVER_ERR in the log) and I get "could not locate remote server" in a browser. When I retry (i.e. reload the page), it usually works.

**Comment by bitbeans** [comment]
resolver problem, bot SDC :)
