### ISSUE TITLE
Root certificate!

### ISSUE THREAD

**Issue by sun-shine-boy** [bitbeans/SimpleDnsCrypt#341]
Hi, it seems this App modify the Root Certificates.
it doesn't happen with installation but after 2-3 days. can I know why is that?
the reg path that SimpleDnsCrypt tries to modify:
HKEY_LOCAL_MACHINE\SOFTWARE\MICROSOFT\SYSTEMCERTIFICATES\AUTHROOT\CERTIFICATES\D23209AD23D314232174E40D7F9D62139786633A\[Blob]

Equifax Secure Certificate Authority.

**Comment by martinsstuff** [comment]
(Not a dev)

May I know how you determined that SimpleDNSCrypt is doing this?

Does running sigcheck: https://docs.microsoft.com/en-us/sysinternals/downloads/sigcheck

with the -tuv parameters display any mismatching certificates? (Except two Xbox Live and possibly 1 Hyper-V result)

**Comment by sun-shine-boy** [comment]
> May I know how you determined that SimpleDNSCrypt is doing this?
Hi, Sure why not.
My HIPS(360 total security Hips) told me that.
Also, I analyzed the installer with a Chinese malware analysis service.
the results:
https://s.threatbook.cn/report/file/e9caa278c67550eabba5b662ca66a8b5fccb61dc5d9fa7ed140e73d0d583495f/?sign=history&env=win7_sp1_enx64_office2013
just translate the page to English(like I do).
this App install 2 root  certificates(according to report) and modify system certificates(COMODORSAAddTrustCA)
I'm not malware analysis expert : ) just don't feel safe with these actions!
maybe it's safe! idk.
I apologize for my English mistakes

**Comment by bitbeans** [comment]
I don`t think SDC is the problem with your certificates
