### ISSUE TITLE
A simply silly question

### ISSUE THREAD

**Issue by Decopi** [bitbeans/SimpleDnsCrypt#342]
Hi,

Latest dnscrypt-proxy version is 2.0.16.
SimpleDnsCrypt uses 2.0.15.

Please, a simply silly question: Is there any expectation about when will be the SimpleDnsCrypt update?

Thank you in advance!

PS: Feel free to close the issue.

**Comment by DRSDavidSoft** [comment]
@Decopi Well as of Simple DNSCrypt v0.6.0, the included `dnscrypt-proxy` is version **2.0.19**.
