### ISSUE TITLE
chocolatey package for SimpleDnsCrypt is deprecated

### ISSUE THREAD

**Issue by chantisnake** [bitbeans/SimpleDnsCrypt#347]
I was the maintainer for the [chocolatey](https://chocolatey.org/) package for SimpleDnsCrypt.
  I am deprecating the chocolatey package for SimpleDnsCrypt because I no longer have time to maintain it.

  I have requested for another package maintainer here: https://github.com/chocolatey/chocolatey-package-requests/issues/418
  The chocolatey package page for SimpleDnsCrypt : https://chocolatey.org/packages/SimpleDnsCrypt

  Sorry for all the inconvenience I have caused.

  (This issue is created automatically, some of the links may be wrong, please inform me if You want me to change them.)

**Comment by bitbeans** [comment]
https://github.com/bitbeans/simplednscrypt-choco
