### ISSUE TITLE
Missing vcruntine140.dll

### ISSUE THREAD

**Issue by jeffbeu** [bitbeans/SimpleDnsCrypt#35]
Followed the update prompts in Simple DNSCrypt to upgrade to 0.3.1. and obtained the above error on restart.

The installer seems to have pulled in the x64 version of Visual C++ Redistributable for Visual Studio 2015 instead of the x86 version as a dependency.

**Comment by bitbeans** [comment]
Hmm, whats your windows version?

**Comment by jeffbeu** [comment]
Win7 x64

OS Name:                   Microsoft Windows 7 Professional
OS Version:                6.1.7601 Service Pack 1 Build 7601
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free

**Comment by bitbeans** [comment]
The installer only will download this: https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe

Can you try to install it without the update prompt? So uninstall, download https://github.com/bitbeans/SimpleDnsCrypt/releases/download/0.3.1/SimpleDNSCrypt.msi and install.

**Comment by jeffbeu** [comment]
Well that is a bit strange. 
I uninstalled Simple DNSCrypt & vcdist(x64,x86)
Using the link above the installation works.

Do you have a link to the old version of DNSCrypt, I am curious if I can reproduce it?

**Comment by bitbeans** [comment]
https://github.com/bitbeans/SimpleDnsCrypt/releases/download/0.2.9/SimpleDNSCrypt.msi

https://github.com/bitbeans/SimpleDnsCrypt/releases/download/0.3.0/SimpleDNSCrypt.msi

**Comment by bitbeans** [comment]
Seems the installer does not install the prerequisites on an upgrade

**Comment by jeffbeu** [comment]
I am looking to see if I already had vcdist x64 already installed. I know I didn't explicitly install it.

**Comment by jeffbeu** [comment]
Is there a x64 version of SimpleDNSCrypt? My logs show that I installed SimpleDNSCrypt on the 5th Jan 2016. It crashed and then vcdist(x64) was installed 5min later.

**Comment by bitbeans** [comment]
I don't know if there was the vcdist(x64) defined in a previous installer (by mistake).
In 0.2.9 there was a vcruntine140.dll next to the .exe, i removed it and added the complete vcdist(x86) as prerequisite (for alle windows versions).

**Comment by jeffbeu** [comment]
So SimpleDNSCrypt has never been released as a 64bit binary?

**Comment by bitbeans** [comment]
no :)

**Comment by jeffbeu** [comment]
Well I have been running SimpleDNSCrypt without vcdist(x86) for the past month.

**Comment by bitbeans** [comment]
Yes, maybe because the vcruntine140.dll was included in the installation folder.

**Comment by jeffbeu** [comment]
Thanks for your help. Looks like this issue may have been unique to my machine.

**Comment by bitbeans** [comment]
thank you for reporting this, i think there was something wrong with an update. should be fixed for further updates.
