### ISSUE TITLE
 Dnscrypt-proxy starts then terminates on boot - no internet - Win 7 Pro 64-bit

### ISSUE THREAD

**Issue by glnzglnz** [bitbeans/SimpleDnsCrypt#356]
Five months ago, we installed Simple DNSCrypt 64-bit on our Win 7 Pro 64-bit machine (16GB RAM, Verizon FIOS 1Gbps), which in turn installed the dnscrypt-proxy process and service on the machine.

Starting just three weeks ago ±, on reboots, our internet connection got spotty on this machine and then started to die.  Not all reboots, but maybe half.  I figured out that the dnscrypt-proxy process and service are starting on reboots **but then something is terminating them** pretty quickly as booting continues.  When they terminate, the PC cannot connect to the internet.

I tried a number of things, but the only immediate solution I found was to change the dnscrypt-proxy service's start to "Automatic (Delayed Start)", which works but causes every reboot to take longer.

Here's a link that will take you to an xls with the entire Autoruns list of startup items:  [https://onedrive.live.com/view.aspx?resid=C405D387ABA56BA!162&ithint=file%2cxlsx&app=Excel&authkey=!ADan0i2LhXcYGyk](https://onedrive.live.com/view.aspx?resid=C405D387ABA56BA!162&ithint=file%2cxlsx&app=Excel&authkey=!ADan0i2LhXcYGyk)   (Rows with ~~strikeout text~~ are DISABLED and do not start.)   Do you see anything in this startup list that would cause the dnscrypt-proxy process and service to terminate?

**UPDATE - SOME PROGRESS - Oct 14 2018**

I have done the following:

1) I have written this .bat file and saved it to my desktop - and you will see that the next-to-last line is the important one:

```
cd "C:\Users\[MyUserName]\Desktop\"  
echo. >> start-dnscrypt-results.txt  
echo -------------------- >> start-dnscrypt-results.txt  
echo. >> start-dnscrypt-results.txt  
echo %DATE% %TIME% >> start-dnscrypt-results.txt  
echo. >> start-dnscrypt-results.txt  
sc start dnscrypt-proxy >> start-dnscrypt-results.txt  
echo. >> start-dnscrypt-results.txt
```

2) I have gone into Task Scheduler and scheduled the above batch file to run on Startup, with a delay of 30 seconds, and with Highest Privileges. (I had to use Task Scheduler with Highest Privileges because I could NOT get my bat file to run as Administrator otherwise - if I run it any other way, I must manually run it "as Administrator" and click Yes on the UAC prompt.)

3) I configured the Properties of the service dnscrypt-proxy to retry to start three times.

4) I also needed to change that service to start as "Automatic" and not "Automatic (Delayed Start)".

Well, it is working.

When I reboot, I can see either that the service is starting and staying on, in which case the .bat file leaves an error message in the results file,
or that the service starts and then stops and then starts again, with success codes in the results file.

What do you think?

By the way, that results file looks like this --

> [SC] StartService FAILED 1056:
> An instance of the service is already running.
> ---------- 
> Sat 10/13/2018 18:32:52.80 
> [SC] StartService FAILED 1056:
> An instance of the service is already running.
> ---------- 
> Sat 10/13/2018 18:35:04.10 
> [SC] StartService FAILED 1056:
> An instance of the service is already running.
> ---------- 
> Sat 10/13/2018 19:11:52.22 
> SERVICE_NAME: dnscrypt-proxy 
>         TYPE               : 10  WIN32_OWN_PROCESS  
>         STATE              : 2  START_PENDING 
>                                 (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
>         WIN32_EXIT_CODE    : 0  (0x0)
>         SERVICE_EXIT_CODE  : 0  (0x0)
>         CHECKPOINT         : 0x0
>         WAIT_HINT          : 0x7d0
>         PID                : 3532
>         FLAGS              : 
> ---------- 
> Sat 10/13/2018 20:52:48.19 
> [SC] StartService FAILED 1056:
> An instance of the service is already running.
> ---------- 
> Sun 10/14/2018  7:17:51.31 
> SERVICE_NAME: dnscrypt-proxy 
>         TYPE               : 10  WIN32_OWN_PROCESS  
>         STATE              : 2  START_PENDING 
>                                 (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
>         WIN32_EXIT_CODE    : 0  (0x0)
>         SERVICE_EXIT_CODE  : 0  (0x0)
>         CHECKPOINT         : 0x0
>         WAIT_HINT          : 0x0
>         PID                : 2592
>         FLAGS              : 
> ---------- 
> Sun 10/14/2018  9:27:55.70 
> [SC] StartService: OpenService FAILED 5:
> Access is denied.
> -------------------- 
> Sun 10/14/2018 10:25:22.13 
> [SC] StartService FAILED 1056:
> An instance of the service is already running.
> -------------------- 
> Sun 10/14/2018 10:27:36.17 
> SERVICE_NAME: dnscrypt-proxy 
>         TYPE               : 10  WIN32_OWN_PROCESS  
>         STATE              : 2  START_PENDING 
>                                 (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
>         WIN32_EXIT_CODE    : 0  (0x0)
>         SERVICE_EXIT_CODE  : 0  (0x0)
>         CHECKPOINT         : 0x0
>         WAIT_HINT          : 0x7d0
>         PID                : 4048
>         FLAGS              : 
> ------------------- 
> Sun 10/14/2018 11:12:03.61 
> [SC] StartService FAILED 1056:
> An instance of the service is already running.
> 

Thanks.

**Comment by glnzglnz** [comment]
And maybe there's another possibility, although I have not tested it,
Go to C:\Program Files\bitbeans\Simple DNSCrypt x64\dnscrypt-proxy\, look for the file dnscrypt-proxy.exe, right-click it, go to Properties, click on the "Compatibility" tab, hit the button at the bottom "Change settings for all users", and now enable "Run this program as an administrator".
Again, I have not yet tested to see whether this (by itself) overcomes the unknown evil force that is stopping the dnscrypt-proxy service on some (not all) of my boot-ups.
Please report back.

**Comment by glnzglnz** [comment]
stealzy - can you see what is happening at your bootup?
I also (for a very long time) have had Task Manager start automatically at bootup.  It's a separate Task Scheduler item.  If I leave Task Manager on the Services tab, then, when it starts, I see that dnscrypt-proxy starts then stops, and then my bat file kicks in to start it again, dnscrypt-proxy reaches "Running" and my bat task exits.
Before you try my bat file, please make Task Manager start at bootup and let us know what you see.

**Comment by dimsdein** [comment]
Also I'm seeing this issue on a computer with Windows 7 and 8.1, both x64 Enterprise. I tested with UAC disabled through secpol but it's still happening, and, as previous reports, on boot and when using for a while. If threre's something I can help to debug or provide additional info, please let me know.

**Comment by glnzglnz** [comment]
In case it's not clear, my steps 1 - 4 above have been working.

**Comment by rkwk** [comment]
I'm experiencing the same issue. It looks to me as if the service doesn't start properly if it can't download the latest resolvers list, which may be the case e.g. when using a dial-up connection. If I reboot the same day then it works fine. But if I reboot after a few days, it apparently tries to update the list and fails to start at all.

**Comment by glnzglnz** [comment]
rkwk - I'm not a tech and you may be 100% right in your observation.
However, I'm on 1Gbps FIOS with low latency (always ≤5ms), not dial-up, and I definitely have this issue about half of my reboots.
Maybe on reboot our NIC+network connections don't start quite fast enough or give priority to other processes and services, dnscrypt-proxy stops if it doesn't get an immediate NIC+network connection to the internet, and then with the dnscrypt-proxy service stopped, the PC cannot connect to the internet at all.  Maybe that's why my steps 1) - 4) above work.

**Comment by glnzglnz** [comment]
It's still a mystery why dnscrypt-proxy service shows as "Stopped" in my Task Manager during bootup.   (My bat file then kicks it into "Starting" and "Running".)
Any ideas what causes this?  Sequence of startup items?
My PC also has as startup items: Avast Free AV, MalwareBytes, OneDrive, SpiderOakOne, PCloud, iReboot (because my PC dual boots 7 and 10, both Pro 64-bit), Start Menu X ...
Of course, a million other things also start on boot.  Please see my link at the start here to an xls printout of ALL my startup items from Autoruns.
Any ideas, anyone?

**Comment by dimsdein** [comment]
I just noticed that after running Simple DNSCrypt with no issue of being deactivated, it happened again after reboot. The notorious change made in the system, are updates installed by Windows Update, and perhaps it's likely _cleaned_ by Windows Defender KB915597. (Windows 7 Enterprise x64 SP1). It's worth investigating more in depth, but I didn't found a log or proper way to track Defender activities.
If anyone can spot a matching as consequence after install updates, please report.

**Comment by glnzglnz** [comment]
dimsdein - you may well be right, but my Win 7 Pro 64-bit system uses Avast AV Free, not Windows Defender, and I have the problem on some bootups.

**Comment by dimsdein** [comment]
> 
> 
> dimsdein - you may well be right, but my Win 7 Pro 64-bit system uses Avast AV Free, not Windows Defender, and I have the problem on some bootups.

The PC has ESET installed, however, real-time analysis of Windows Defender was disabled. Now I've disabled system-wide Windows Defender through Group Policy,  and I'll keep an eye if it was causing conflicts.

**Comment by d3bil0x** [comment]
In my case it was the cumulation of 2 problems that I solved.
1. When my machines boots without any active internet connection (e.g. used non-autoconnect WiFi or unplugged LAN cable) then the `dnscrypt-proxy` service does not start.
I solved this by creating a simple task in the Task Scheduler that automatically restart the `dnscrypt-proxy` service when the Internet connection is established (I have added to the post the attachment [d3bil0x-DNSCryptRestart.zip](https://github.com/bitbeans/SimpleDnsCrypt/files/2576315/d3bil0x-DNSCryptRestart.zip) in the xml format that must be imported into the Windows Task Scheduler).
2. But sometimes the above solution failed, fortunately I discovered the culprit - the popular PeerBlock app, which (based on its default lists) blocks access to the default address of SimpleDNSCrypt `Advanced Settings->Fallback Resolver: 9.9.9.9:53`. if the validity period of the Resolvers List expires (it seems to me determined by the `refresh_delay = 72` parameter from the `[sources.public-resolvers]` section from the `dnscrypt-proxy.toml` configuration file). The solution is to add the address 9.9.9.9 to the exceptions in the PeerBlock or change the address of SimpleDNSCrypt Fallback Resolver to another, e.g. GoogleDNS 8.8.8.8:53 or OpenDNS 208.67.222.222:53

After 2 weeks of testing all works fine.

**Comment by dimsdein** [comment]
> 
> 
> In my case it was the cumulation of 2 problems that I solved.
> 
>     1. When my machines boots without any active internet connection (e.g. used non-autoconnect WiFi or unplugged LAN cable) then the `dnscrypt-proxy` service does not start.
>        I solved this by creating a simple task in the Task Scheduler that automatically restart the `dnscrypt-proxy` service when the Internet connection is established (I have added to the post the attachment [d3bil0x-DNSCryptRestart.zip](https://github.com/bitbeans/SimpleDnsCrypt/files/2576315/d3bil0x-DNSCryptRestart.zip) in the xml format that must be imported into the Windows Task Scheduler).
> 
>     2. But sometimes the above solution failed, fortunately I discovered the culprit - the popular PeerBlock app, which (based on its default lists) blocks access to the default address of SimpleDNSCrypt `Advanced Settings->Fallback Resolver: 9.9.9.9:53`. if the validity period of the Resolvers List expires (it seems to me determined by the `refresh_delay = 72` parameter from the `[sources.public-resolvers]` section from the `dnscrypt-proxy.toml` configuration file). The solution is to add the address 9.9.9.9 to the exceptions in the PeerBlock or change the address of SimpleDNSCrypt Fallback Resolver to another, e.g. GoogleDNS 8.8.8.8:53 or OpenDNS 208.67.222.222:53
> 
> 
> After 2 weeks of testing all works fine.
> 
> NOTE: For a connections requiring longer time, eg for performing slower DHCP autoconfiguration, you can enable the parameter `Edit Trigger-> Advanced Settings-> Delay task for: x seconds` from Task Scheduler.

@d3bil0x You are right, after testing issue was hidden by coincident moves. Nonetheless, I think that dnscrypt-proxy should be aware by waiting for internet connection.

**Comment by bitbeans** [comment]
Did you guys try to play with this: https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml#L187 ?

**Comment by d3bil0x** [comment]
Hi @bitbeans.
With the `netprobe_timeout = 0` it looks like it works :)

**Comment by glnzglnz** [comment]
dimsdein, d3bil0x and Mr. Hermann - 
First, a txt copy of my dnscrypt-proxy.toml is here -- 
https://1drv.ms/t/s!ArpWuno4XUAMgST2ktvO7c4faIGw 
Second, I love Simple DNSCrypt on my PC (and DNSCloak on my iPad) but I'm not a tech.  Could the three of you do a little brainstorming and put the final fix into a new version of Simple DNSCrypt itself?  
I am NOT convinced it is ONLY one thing or another.  My workaround Task Scheduler+bat is working, but it is not the same as the notes here from dimsdein and d3bil0x - and I do not have the same anti-virus as you guys.  There is a deeper reason for the glitch I think.

**Comment by dimsdein** [comment]
> 
> 
> dimsdein, d3bil0x and Mr. Hermann -
> First, a txt copy of my dnscrypt-proxy.toml is here --
> https://1drv.ms/t/s!ArpWuno4XUAMgST2ktvO7c4faIGw
> Second, I love Simple DNSCrypt on my PC (and DNSCloak on my iPad), but I'm not a tech and I cannot follow your suggestions. I think dnscrypt-proxy is good tech for good social reasons but ideally should work nicely.
> **Could the three of you do a little brainstorming and put the final fix into a new version of Simple DNSCrypt itself?**
> I am NOT convinced it is ONLY one thing or another. My workaround Task Scheduler+bat is working, but it is not the same as the notes here from dimsdein and d3bil0x - and I do not have the same anti-virus as you guys. There is a deeper reason for the glitch I think.

@glnzglnz Change option **netprobe_timeout** to netprobe_timeout = 0 in your 'dnscrypt-proxy.toml', that is what is working for @d3bil0x, seems that dnscrypt-proxy shuts down when a network is not available after netprobe_timeout has reached. I assume that setting to 0 dnscrypt-proxy will wait until a network is available.

**Comment by bitbeans** [comment]
0.6.1 will have this setting in the UI

**Comment by bitbeans** [comment]
0.6.1 released with netprobe_timeout.
