### ISSUE TITLE
Preparing files for removal

### ISSUE THREAD

**Issue by njscorpion** [bitbeans/SimpleDnsCrypt#357]
while installing i am stuck at "Preparing files for removal"

installer "SimpleDNSCrypt64.msi"

https://i.imgur.com/jpnY9K4.png

I am using Windows 10 pro (x64)

[msiexec log.txt](https://github.com/bitbeans/SimpleDnsCrypt/files/2527311/msiexec.log.txt)
Or https://pastebin.com/7YEATV2F

**Comment by Woofy-Wolf** [comment]
same for me, using Windows 7 Pro 64-bit. I can't install versions of SimpleDnsCrypt after 0.5.5. They stop with the message, ""Preparing files for removal".

My .NET Framework is up to date (except ver. 4.7.2), and I updated to the latest build of visual c++. I'm out of ideas.

**Comment by bitbeans** [comment]
@njscorpion @Woofy-Wolf i will publish a new version
