### ISSUE TITLE
System.Exception: Missing path

### ISSUE THREAD

**Issue by i-cant-git** [bitbeans/SimpleDnsCrypt#358]
First time trying SimpleDnsCrypt.

1. I installed `dnscrypt-proxy` manually to `D:\dnscrypt-proxy`
2. Then I put the [AppVeyor build files](https://simplednscrypt.blob.core.windows.net/deploy/SimpleDnsCrypt/bin/x64/SimpleDNSCrypt_x64.zip) into `D:\dnscrypt-proxy`
3. I start SimpleDnsCrypt.exe and infinitely program is stuck in green loading panel.
4. It detects an exception but doesn't show any error message box (e.g. `MessageBox.Show`).

#### The exception is recorded in `logs\2018-11-03 14_51_13_Error.log`
```
2018-11-03 14:51:13.5556 DnsCryptProxyManager System.Exception: Missing D:\dnscrypt-proxy\dnscrypt-proxy\dnscrypt-proxy.exe
   At: SimpleDnsCrypt.Helper.DnsCryptProxyManager.ExecuteWithArguments(String arguments)
2018-11-03 14:51:14.6898 LoaderViewModel System.ArgumentNullException: Value cannot be null.
Parameter name: format
   At: System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   At: System.String.Format(String format, Object arg0)
   At: SimpleDnsCrypt.ViewModels.LoaderViewModel.<InitializeApplication>d__8.MoveNext()
```

**Yes I need to create a subfolder named `dnscrypt-proxy` under `dnscrypt-proxy`,
I'm just giving heads up if you want to fix this uncatched exception.**

**Comment by bitbeans** [comment]
If the dnscrypt-proxy directory is missing i get:
![missing_folder](https://user-images.githubusercontent.com/1482102/48944265-504fc180-ef26-11e8-829d-9d524c835e8e.PNG)
