### ISSUE TITLE
Why the 0.5.6 broke auto update?

### ISSUE THREAD

**Issue by DRSDavidSoft** [bitbeans/SimpleDnsCrypt#363]
As you stated the 0.5.6 release broke auto update.

May I ask what was changed and how it was broken? I'm interested to know.

**Comment by bitbeans** [comment]
@DRSDavidSoft i think it was: https://github.com/bitbeans/SimpleDnsCrypt/commit/978458c2c7a6f2fed70e51cc6e4444b83ef081b8 just a typo from me :)
