### ISSUE TITLE
Uninstall Bugs/Quirks

### ISSUE THREAD

**Issue by rlesch** [bitbeans/SimpleDnsCrypt#364]
Following Issues on Uninstalling SDC (5.8.0 / 6.0.0) on win7 pro 64bit:

1) the installation folder is deleted completely, _regardless_ of any preexisting files/folders or new added files/folders. thats means all logs, settings, dnscrypt subfolder are gone w/o any warning.. 
Suggestion: 
- increase granularity of uninstall routine. ask if everything should be deleted or logs and settings should be kept. 
- keep anything that was in existing installationfolder before installation _untouched_.

2) it seems to be a good idea to restart the system after installation/uninstallation to avoid issues like wrong path names of service when installation folder changed. 

error log:
DnsCryptProxyManager System.InvalidOperationException: Cannot start service dnscrypt-proxy on computer '.'. ---> System.ComponentModel.Win32Exception: Das System kann die angegebene Datei nicht finden
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at SimpleDnsCrypt.Helper.DnsCryptProxyManager.Start()

registry cleaning and a proper new install with restartcycle solved it
- maybe propose a system restart after installation/uninstall 

3) at elast once the adapter settings for dns werent reset on uninstall (may be due to aboves problem)

**Comment by bitbeans** [comment]
the uninstall.exe had an bug inside. fixed in 0.6.1 and uninstall 0.2.4
