### ISSUE TITLE
Unable to start the dnscrypt service in  64 bit version only. No problem in x86.

### ISSUE THREAD

**Issue by Techguyprivate** [bitbeans/SimpleDnsCrypt#366]
The 64 bit of simplednscrypt is not working. 

I am unable to start the dnscrypt proxy service. 

 I am able to start the dnscrypt service in x86 version each time.

Exact steps:

1. First ,I uninstalled any simplednsrypt version & then rebboted my computer. Restarting it ,not shutdown.

 2. Then ,I installed the 64 bit . I was unable to start the dnscrypt proxy service.

3. Then , I uninstalled the 64bit version.Restarted my PC. 

4. Installed x86 version. I was able to start the dnscrypt service.

5. I think that I have been  facing the same issue for 3 months.

Windows 10 pro 64bit.

**Comment by bitbeans** [comment]
@Techguyprivate is there anything in the log folder? You also can try enable the dnscrypt-proxy logging by yourself: https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml#L123 Or maybe try to start the dnscrypt-proxy.exe from a powershell/cmd, to get some output..

**Comment by Techguyprivate** [comment]
![simple dnscryptuntitled](https://user-images.githubusercontent.com/43615747/48967935-eac00b80-efdf-11e8-8efb-0a8b2d569d8b.jpg)

**Comment by bitbeans** [comment]
@Techguyprivate looks good :)

**Comment by Techguyprivate** [comment]
Ok . An extremely weird and odd thing. Or may be not so.I don't know.

If I click ( Very imprtant only clicks, like toggle )  on the dnscrypt service button to enable it,  it just won't turn green .ie. not getting enabled. 

But If I drag it to enable it , it is getting enabled,aka  turning into green . 

But If i click on it to disable it, It is getting disabled. Important by clicking , not dragging. 

Same for Log. 

See the gif.
![simplednscrypt problem issue bugs](https://user-images.githubusercontent.com/43615747/48968035-59519900-efe1-11e8-9f23-222fab0f2fa9.gif)

**Comment by Techguyprivate** [comment]
Able to start dnscrypt proxy service from cmd/powershell.  Seems a GUI problem.

**Comment by glnzglnz** [comment]
Techguyprivate - maybe your issue is similar to ours?
See this "Issue" -- https://github.com/bitbeans/SimpleDnsCrypt/issues/356

**Comment by bitbeans** [comment]
![service](https://user-images.githubusercontent.com/1482102/49326176-683ecb00-f54e-11e8-8c10-ce5a78427194.PNG) how is your path in the windows service?

**Comment by Techguyprivate** [comment]
![simple dns crypt](https://user-images.githubusercontent.com/43615747/49326547-9cfd5300-f54b-11e8-9ad4-95f0a3ceb09c.png)
Mine. Same.  Let me take a scientific look at the problem with precision , instead of chaotic , random trial & error method. I will post If I find something.

**Comment by bitbeans** [comment]
@Techguyprivate and also try:
- complete uninstall
- remove service
- delete folders
- reboot

fresh install of 0.6.1

**Comment by Techguyprivate** [comment]
Shit. It was a very simple problem. It is embarrassing. Okay , here what was happening ,I think . 

What I did that led me to face the problem : 

1. I removed x86 version with a special uninstaller ( Iobit uninstaller in my case . Also I tried revo  uninstaller ,geek uninstaller ,ccleaner ,bleachbit , 3or 4 more special uninstaller I forgot their name cause I tried solving the problem several times )

2. Restart my computer .Not shutdown cause although I have not enabled fast startup in windows. (linux installed) 

3. Installed x64 

4. I was unable to start the dnscrypt service . Little bit odd things & very few details are above in other posts. 

5. Also tried to start the dnscrypt service by going to windows services. Service didn't start.

What I discover. Where was the problem .

Going to services in windows , the path was different for dnscrypt service .it was refering to the x86 version , not x64 .

 What did I do that solved the problem for silly me at least.

1. Uninstalled every version with a special uninstaller which remove any leftover setting , config file etc automatically. 

2. Restarted . Not shutdown and start . 

3. Installed the x86 version .

4. Going in advanced setting , removed the dnscrypt service. Yes. major thing.

5. Restart computer. Installed x64 version.

 Working fine. 

Here is the bug or problem  I think . 

 Removing simplednscrypt doesn't remove the dnscrypt service. Or removing x86 version doesn't remove the service .

Or installing the x64 version didn't override the service or changed it path to x64 for dnscrypt service.

**Comment by bitbeans** [comment]
@Techguyprivate i fixed this in 0.6.1 :) the old service should now be removed on uninstall.

**Comment by Techguyprivate** [comment]
Sorry for the above long post . Posted for noobs like me. 

Installing the x64 version after uninstalling the x86 version , doesn't change dnscrypt proxy service path in windows service manager. I mean , go to windows service manager, click on dnscrypt service , then right click on it , then go to  porporties  . In general tab , the path of the service is to x86 version after uninstalling the x86 & installing x64 version. I think the service should remove itself when installing x86 version or override or replace itself when installing x64 version.

**Comment by Techguyprivate** [comment]
> 
> 
> @Techguyprivate i fixed this in 0.6.1 :) the old service should now be removed on uninstall.

Or override or replace when installing new or other version . Anyway, huge thank you for your awesome service.

**Comment by bitbeans** [comment]
you are welcome

**Comment by AdKiller** [comment]
Just did a clean install of Windows 1909 and I have the same problem. was working fine in Windows 10 1803. The service just doesn't start no matter what I do... restart Windows, reinstall, click, click and drag on toggle. 

SimpleDNSCrypt64 0.7.0
