### ISSUE TITLE
Settings reset on program update

### ISSUE THREAD

**Issue by CDR-DPH** [bitbeans/SimpleDnsCrypt#367]
This issue is still occurring. After the latest update v2.0.19 I have had to reconfigure the advanced settings and reselect the resolvers. It took me a while to figure out why none of of my devices could maintain a stable intenret connection - The Global Resolver setting was turned off after the update.

**Comment by bitbeans** [comment]
it is because the file dnscrypt-proxy.toml is overwritten

**Comment by bitbeans** [comment]
fixed in 0.6.1
