### ISSUE TITLE
SDC Crash while Query Log active.

### ISSUE THREAD

**Issue by rlesch** [bitbeans/SimpleDnsCrypt#368]
SDC 6.0.0 / 5.8.0   win7 64 pro

Application/GUI crashed while query log window open and logging active.
DNSCrypt Service was running and kept running& logging unaffected.

interpreting the unix-time correctly, those seem to be the last entries on/before crashing:

time:xxxx	host:127.0.0.1	message:pixel.quantserve.com	type:A	return:PASS
time:xxxx	host:127.0.0.1	message:clc.stackoverflow.com	type:A	return:PASS

though the queried host(s) seem to be not related, a repetition didnt lead to any crash.

**ErrorLog:**
> xxxx QueryLogViewModel System.Reflection.TargetInvocationException: An error occurred while dispatching a call to the UI Thread ---> System.InvalidOperationException: An ItemsControl is inconsistent with its items source.
>   See the inner exception for more information. ---> System.Exception: Information for developers (use Text Visualizer to read this):
> This exception was thrown because the generator for control 'SimpleDnsCrypt.Controls.LoggingListView Items.Count:2543' with name '(unnamed)' has received sequence of CollectionChanged events that do not agree with the current state of the Items collection.  The following differences were detected:
>   Accumulated count 2542 is different from actual count 2543.  [Accumulated count is (Count at last Reset + #Adds - #Removes since last Reset).]
> 
> One or more of the following sources may have raised the wrong events:
>      System.Windows.Controls.ItemContainerGenerator
>       System.Windows.Controls.ItemCollection
>        System.Windows.Data.ListCollectionView
>         System.Collections.ObjectModel.ObservableCollection`1[[SimpleDnsCrypt.Models.QueryLogLine, SimpleDnsCrypt, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null]]
> (The starred sources are considered more likely to be the cause of the problem.)
> 
> The most common causes are (a) changing the collection or its Count without raising a corresponding event, and (b) raising an event with an incorrect index or item parameter.
> 
> The exception's stack trace describes how the inconsistencies were detected, not how they occurred.  To get a more timely exception, set the attached property 'PresentationTraceSources.TraceLevel' on the generator to value 'High' and rerun the scenario.  One way to do this is to run a command similar to the following:
>    System.Diagnostics.PresentationTraceSources.SetTraceLevel(myItemsControl.ItemContainerGenerator, System.Diagnostics.PresentationTraceLevel.High)
> from the Immediate window.  This causes the detection logic to run after every CollectionChanged event, so it will slow down the application.
> 
>    --- End of inner exception stack trace ---
>    at System.Windows.Controls.ItemContainerGenerator.Verify()
>    at System.Windows.Controls.VirtualizingStackPanel.MeasureChild(IItemContainerGenerator& generator, IContainItemStorage& itemStorageProvider, IContainItemStorage& parentItemStorageProvider, Object& parentItem, Boolean& hasUniformOrAverageContainerSizeBeenSet, Double& computedUniformOrAverageContainerSize, Double& computedUniformOrAverageContainerPixelSize, Boolean& computedAreContainersUniformlySized, Boolean& hasAnyContainerSpanChanged, IList& items, Object& item, IList& children, Int32& childIndex, Boolean& visualOrderChanged, Boolean& isHorizontal, Size& childConstraint, Rect& viewport, VirtualizationCacheLength& cacheSize, VirtualizationCacheLengthUnit& cacheUnit, Boolean& foundFirstItemInViewport, Double& firstItemInViewportOffset, Size& stackPixelSize, Size& stackPixelSizeInViewport, Size& stackPixelSizeInCacheBeforeViewport, Size& stackPixelSizeInCacheAfterViewport, Size& stackLogicalSize, Size& stackLogicalSizeInViewport, Size& stackLogicalSizeInCacheBeforeViewport, Size& stackLogicalSizeInCacheAfterViewport, Boolean& mustDisableVirtualization, Boolean isBeforeFirstItem, Boolean isAfterFirstItem, Boolean isAfterLastItem, Boolean skipActualMeasure, Boolean skipGeneration, Boolean& hasBringIntoViewContainerBeenMeasured, Boolean& hasVirtualizingChildren)
>    at System.Windows.Controls.VirtualizingStackPanel.MeasureOverrideImpl(Size constraint, Nullable`1& lastPageSafeOffset, List`1& previouslyMeasuredOffsets, Nullable`1& lastPagePixelSize, Boolean remeasure)
>    at System.Windows.Controls.VirtualizingStackPanel.MeasureOverride(Size constraint)
>    at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
>    at System.Windows.UIElement.Measure(Size availableSize)
>    at System.Windows.ContextLayoutManager.UpdateLayout()
>    at System.Windows.Controls.ItemsControl.OnBringItemIntoView(ItemInfo info)
>    at SimpleDnsCrypt.Controls.LoggingListView.AutoScroll_ItemsCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
>    at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
>    at System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
>    at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
>    at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
>    at System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
>    at System.Windows.Data.ListCollectionView.ProcessCollectionChangedWithAdjustedIndex(NotifyCollectionChangedEventArgs args, Int32 adjustedOldIndex, Int32 adjustedNewIndex)
>    at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
>    at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
>    at SimpleDnsCrypt.ViewModels.QueryLogViewModel.<>c__DisplayClass8_0.<AddLogLine>b__0()
>    at Caliburn.Micro.XamlPlatformProvider.<>c__DisplayClass8_1.<OnUIThread>b__0()
>    --- End of inner exception stack trace ---
>    at Caliburn.Micro.XamlPlatformProvider.OnUIThread(Action action)
>    at SimpleDnsCrypt.ViewModels.QueryLogViewModel.AddLogLine(QueryLogLine queryLogLine)
>    at SimpleDnsCrypt.ViewModels.QueryLogViewModel.<QueryLog>b__24_2()
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
>    at SimpleDnsCrypt.ViewModels.QueryLogViewModel.<QueryLog>d__24.MoveNext()

**Comment by bitbeans** [comment]
see #337
