### ISSUE TITLE
Get an error when installing on an offline VM

### ISSUE THREAD

**Issue by rugk** [bitbeans/SimpleDnsCrypt#37]
When I tried to install this on a test VM without internet connection I got this error:
```
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 12007. The arguments are: https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe, , 
Error 4153. Visual C++ Redistributable for Visual Studio 2015 x86 mandatory prerequisite was not correctly installed.
=== Logging stopped: 2/16/2016  4:22:05 ===
```

Before the UAC request it showed me basically the first line and afterwards it showed me the second error. I assume this problem occurred, because it could not download Visual Studio 2015 x86.
But in this case it should at least display a more meaningful error message and probably also provide the download link, so that the user can click on it and install it manually.

**Comment by licaon-kter** [comment]
Does this still give an error if you install this pack: http://forums.guru3d.com/showthread.php?t=393405
