### ISSUE TITLE
Blocking websites with Simple DNSCrypt

### ISSUE THREAD

**Issue by lenkarin** [bitbeans/SimpleDnsCrypt#371]
Yesterday i hear about dnscrypt-proxy and I decide to try but I choose use the simple dnscrypt and everything it seems working perfectly but when I try to block websites didn't works.

I want block these websites below

[Websites to block.txt](https://github.com/bitbeans/SimpleDnsCrypt/files/2659736/Websites.to.block.txt)

**Comment by lenkarin** [comment]
In the moment I'm using acrylic dns proxy

**Comment by bitbeans** [comment]
You need to enable the Block Tab in settings. After this you can add the domains to the blacklist
