### ISSUE TITLE
DNSCrypt Service does't appear in Windows Services after manual update

### ISSUE THREAD

**Issue by M1k3G0** [bitbeans/SimpleDnsCrypt#372]
I updated 056 to 058, but dnscrypt-proxy.exe stoped working.

I decided to remove and clean everything:
1) close program
2) sc delete dnscrypt-proxy (cmd root)
3) uninstall program
4) reboot system
5) install program SimpleDNSCrypt64.msi
Now dnscrypt-proxy does not appear in Windows Services.

Could you make a button not only to delete DNSCrypt Service, but also to restore it?

**Comment by bitbeans** [comment]
@M1k3G0 can you please update to 0.6.2? if you start the service SDC will install it again.

**Comment by M1k3G0** [comment]
> @M1k3G0 can you please update to 0.6.2? if you start the service SDC will install it again.
> 
> https://github.com/bitbeans/SimpleDnsCrypt/releases/tag/0.6.2

The same problem with 062. I have this ... on win7 and win10 (x64).
After install 058 or 062 service does't appear in Windows Services.
I guess I did something wrong when I run: sc delete dnscrypt-proxy (cmd root).
How to fix it?
