### ISSUE TITLE
DNS Cache: option for "in memory only"

### ISSUE THREAD

**Issue by BananaAcid** [bitbeans/SimpleDnsCrypt#374]
Is is kind of a security enhancement, but would be very nice to have.

Why?
Keeps traces off the local drive.

Pro
Same as within a file.

Con
Re-caching after reboot.

**Comment by bitbeans** [comment]
@BananaAcid Simple DNSCrypt does not manage the DNS Cache. It`s only a GUI for: https://github.com/jedisct1/dnscrypt-proxy
