### ISSUE TITLE
QUERY Log: option for "in memory only"

### ISSUE THREAD

**Issue by BananaAcid** [bitbeans/SimpleDnsCrypt#375]
Is is kind of a security enhancement, but would be very nice to have.

Why?
Keeps traces off the local drive. No write permissions required. For debugging without file change triggering.

Pro
Same as within a file.

Con
Previous entries are gone after logout / reboot- no continuous logging.

**Comment by bitbeans** [comment]
@BananaAcid Simple DNSCrypt does not manage the Query Log, i only read the file which dnscrypt-proxy writes to. It`s only a GUI for: https://github.com/jedisct1/dnscrypt-proxy
