### ISSUE TITLE
Fallover resolvers

### ISSUE THREAD

**Issue by n31n** [bitbeans/SimpleDnsCrypt#38]
I have noticed that once in a while a resolver will not respond or be unavailable causing a lack of web access. I would suggest allowing the user to choose several backup resolvers, 5 or more, so that if the primary, or secondary, or whatever fails, the next resolver in line will become active. Maybe a visual notification that 1. The resolver has failed or is unavailable, and 2. That a new resolver is being used.
This would prevent losing web access due to resolver failure, hopefully.

Thank you

**Comment by bitbeans** [comment]
See #3
