### ISSUE TITLE
Does Simple DNSCrypt need to run at startup or just DNSCrypt Service?

### ISSUE THREAD

**Issue by PhAlAnXcOiN** [bitbeans/SimpleDnsCrypt#381]
Sorry to open an issue on this but I haven't been able to find a Simple DNSCrypt forum to ask this yet. 

Is the purpose of Simple DNSCrypt just to configure the DNSCrypt Service? Or should I assign task scheduler to start Simple DNSCrypt at startup?

For instance, I know that DNSCrypt's design is to now continually test available resolvers and use the fastest one at any given time. Will this continue to happen without Simple DNSCrypt running?

**Comment by Techguyprivate** [comment]
GO to windows services. Administartive services.
Search for dnscrypt services. 
Click on properties.
Set to it to start automatic. Apply it. Don't close it. Go to recovery tab.
Go the next tabs, click  on dependency. 
Set o restart service if failed to start. 

Dnscrypt is a service .

**Comment by AdKiller** [comment]
> DNSCrypt's design is to now continually test available resolvers and use the fastest one at any given time. Will this continue to happen without Simple DNSCrypt running?

I would like to know this too.

**Comment by jedisct1** [comment]
Yes.
