### ISSUE TITLE
Add Adguard dns over https to lists. 

### ISSUE THREAD

**Issue by Techguyprivate** [bitbeans/SimpleDnsCrypt#384]
Adguard launched their Dns over https , dns over tls few weeks ago. 

https://github.com/AdguardTeam/AdguardDNS

https://adguard.com/en/blog/adguard-dns-announcement/

DNS-over-HTTPS

Use https://dns.adguard.com/dns-query for "Default" and https://dns-family.adguard.com/dns-query for "Family protection" mode.

**Comment by jedisct1** [comment]
Adguard servers have been in the list for a very long time. They are almost the first entries: https://dnscrypt.info/public-servers

**Comment by 3xploiton3** [comment]
![image](https://image.prntscr.com/image/4fDwk9mARQO2kpPaLHgd_A.jpeg)
