### ISSUE TITLE
[i18n] Migrate to the Crowdin platform

### ISSUE THREAD

**Issue by MS-PC** [bitbeans/SimpleDnsCrypt#402]
I was wondering if you can migrate to the Crowdin platform for translations. I think it is much more effective since there are many more translators in Crowdin. I would help as proofreader with the Spanish language.
It should be noted that this is only a suggestion.

Support for open source projects: https://crowdin.com/page/open-source-project-setup-request

**Comment by bitbeans** [comment]
sorry at the moment the project will stay at poeditor :)
