### ISSUE TITLE
SimpleDnsCrypt GUI not starting on logon

### ISSUE THREAD

**Issue by brbergami** [bitbeans/SimpleDnsCrypt#403]
I know this maybe has been asked a trillion of times.. but why SDC can't simply start with the system? I tried creating task with task scheduler, but only got the service running instead.

Is like the GUI refuses to launch even if I'm calling the task with admin privileges, and just get the service (which forces me to manually open the app later).
![image](https://user-images.githubusercontent.com/37002893/54965194-3cf14900-4f4e-11e9-9577-9dd5e7af4d7e.png)

Why there's no a simple button in the settings "Launch at System start" is so basic.. and this is required. We can't trust the service is running in background and I tend to check everytime. Even I saw one issue raised about to make the tray icon show the status.. the user want feedback about the app status.

Any future plans to implement this? Thank you in advance.

**Comment by Moxville** [comment]
is this required for "DNSCrypt Service" to auto-start during log-on for user ?
or this is only for GUI to show up during every log-on for user ?

**Comment by brbergami** [comment]
I just want to emulate a click on the app once I login in my computer (with the behavior "start hidden in tray" enabled). So just the "loading" screen of the app is shown and then the tray icon. Just that.
You can run the service standalone using `net start dnscrypt-proxy`, but that is not actually opening the app, that is the reason why SDC exists.

**Comment by slyphnier** [comment]
i think by design the UI is just to simplified DNScrypt use/settings thus not needed to run every login
if u use the original DNScrypt, it also run silent in background right ?

although i agree it would be nice if the UI or notification app let user know if DNScrypt run properly/have problem with connection/disabled
like internet-security style, that stay in taskbar and pop-up if it catch some issue

**Comment by bitbeans** [comment]
Simple DNSCrypt never starts on boot. Its just an UI for dnscrypt-proxy, which starts as windows service on boot.
