### ISSUE TITLE
About dependencies...

### ISSUE THREAD

**Issue by TA2DF** [bitbeans/SimpleDnsCrypt#404]
Does the SDC need to **_check and install_** its dependencies each time it runs?.. Moreover, even though a **newer and last** version of dependency (MS VC++ 2017 ReDist) is available on the computer than that?

**Comment by bitbeans** [comment]
@TA2DF MS VC++ 2017 ReDist is required for the update check. you can disable the check by setting `InstallRedistributablePackage ` to `False `in your `SimpleDnsCrypt.exe.config`
