### ISSUE TITLE
Unable to access translate.google.cn

### ISSUE THREAD

**Issue by happyangry** [bitbeans/SimpleDnsCrypt#406]
Hi.

I am from China and I have set the fallback resolver as `114.114.114.114:53`, but it seems that I can't access [translate.google.cn](url) sometimes. Yes, it's sometimes accessible and sometimes not. The error code in Chrome is `ERR_CONNECTION_TIMED_OUT`.

After removing the DNSCrypt Service, [translate.google.cn](url) can be accessed normally.

**Comment by bitbeans** [comment]
just try a other resolver
