### ISSUE TITLE
Support for .NET Core 3.0

### ISSUE THREAD

**Issue by rogersachan** [bitbeans/SimpleDnsCrypt#412]
Support for .NET Core 3 would prepare this software for the release of .NET 5. A guide on how to port to .NET Core 3 is available on Microsoft's documentation website https://docs.microsoft.com/en-us/dotnet/core/porting/winforms .

**Comment by Cologler** [comment]
a simplest net core program (compile to self-contained) size: 57MB
a simplest net program size: 20KB

**Comment by bitbeans** [comment]
not for now :)
