### ISSUE TITLE
Can't add custom DNSCrypt resolvers and resolvers missing from "dns.d0wn.biz"

### ISSUE THREAD

**Issue by junife** [bitbeans/SimpleDnsCrypt#42]
Hello, Thank you for give us the nice software. I know the SimpleDnsCrypt get resolvers from website https://dns.d0wn.biz/, but dnscrypt-resolvers.csv miss ns1.hk.dns.d0wn.biz(China Hong Kong), I don't know why. I get an idea add the resolver to dnscrypt-resolvers.csv, but it update each time after the software startup and the add custom added item missing. So please kindly check the issue.

Thank you!

**Comment by bitbeans** [comment]
It update from there: https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv
You need to send a pull request to dnscrypt-proxy.

It will be overwritten, because the minisig signaure will be invalid
