### ISSUE TITLE
Adding new options to let the public resolver list updated daily

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [bitbeans/SimpleDnsCrypt#43]
Seen from official DNSCrypt [download server](https://download.dnscrypt.org/dnscrypt-proxy/), the public resolver list is updated everyday, so Simple DNSCrypt should adding an new option in advanced settings to let users follow this change.

**Comment by bitbeans** [comment]
At the moment ther ist no background service or task for SimpleDnsCrypt. 
The application is only active, if the user starts it.

**Comment by bitbeans** [comment]
closed, dnscrypt-proxy 2.0
