### ISSUE TITLE
Problem with "Refresh public resolver list"

### ISSUE THREAD

**Issue by gnavascues** [bitbeans/SimpleDnsCrypt#44]
A message windows apppear: Warning Failed to refresh the public resolver list

**Comment by bitbeans** [comment]
still problems?
Can you download it manually: https://raw.githubusercontent.com/jedisct1/dnscrypt-proxy/master/dnscrypt-resolvers.csv

I can not reproduce the error.

**Comment by porkrinds** [comment]
I can confirm that this WAS an issue, but I just tried again today and there is no longer an error message. It was an issue for about 3-4 days. I just wanted to confirm that it wasn't just OP and that the list download DOES now work (or rather, it doesn't error anymore).

**Comment by bitbeans** [comment]
okay, thank you.

**Comment by Bodup** [comment]
I ran into the same problem today. No matter what I try it will not download the resolver list.
I tried downloading it manually along with the minisig file but that completely breaks the application.
