### ISSUE TITLE
Blacklist from external source strips wildcard rules

### ISSUE THREAD

**Issue by r-a-y** [bitbeans/SimpleDnsCrypt#442]
Hi bitbeans,

I noticed that when you add an external blacklist source that includes wildcard rules, either the asterik wildcards are stripped or they are omitted from the final `blacklist.txt` file.

You can try with this source:
`https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/dnscrypt/spy.txt`

If I manually add a single wildcard rule, the blocklist will accept that though.

**Comment by bitbeans** [comment]
@r-a-y 
Rules from external sources (http) are checked with the following rules:

https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/utils/generate-domains-blacklists/generate-domains-blacklist.py#L51

Rules containing * are not trusted (via http).

The rules from the original python script have been adopted for SimpleDNsCrypt: https://github.com/bitbeans/DnsCrypt.Toolbox/blob/master/DnsCrypt.Blacklist/DomainBlacklist.cs#L70

It's Not a Bug, It's a Feature :)
