### ISSUE TITLE
Fresh install hanging on startup

### ISSUE THREAD

**Issue by STaRDoGG** [bitbeans/SimpleDnsCrypt#444]
Brand new install on win 10 x64, using the latest SDNSC x64, it just hangs on the splash screen with an endless progress/working indicator showing the label "loading network cards".

**Comment by MuhGhifari** [comment]
I have a similar problem and this method works for me.
First, uninstall Simple DNSCrypt from Program and Features.
Then delete dnscrypt-proxy.toml.bak in "C:\Users\User\AppData\Local\Temp".
Reinstall DNSCrypt.

I don't know what's wrong but i suspect that when windows uninstall DNSCrypt, it doesn't completely uninstall

**Comment by bitbeans** [comment]
i think its a problem with the config file. are there any log entries?

**Comment by pluv242** [comment]
This doesn't answer the issue. What was the problem?

For me it worked for months and then fail to even load.

Using the 32 bytes version works though
