### ISSUE TITLE
Status on Update for Changes in upcoming DNScrypt 2.0.29?

### ISSUE THREAD

**Issue by rlesch** [bitbeans/SimpleDnsCrypt#448]
..like anonymous dns, logging improvements etc?

**Comment by bitbeans** [comment]
I will try to publish an update as soon as possible.

**Comment by user8446** [comment]
v0.6.6 doesn't seem pick up the update to 0.6.9 automatically?

**Comment by bitbeans** [comment]
@user8446 yes I have not updated the update.yml. I am working on 0.6.9.

**Comment by bitbeans** [comment]
Maybe someone wants to try 0.6.9 (preview with Anonymized DNS):

https://simplednscrypt.blob.core.windows.net/deploy/SimpleDnsCrypt/bin/x64/SimpleDNSCrypt_x64.zip

**Comment by user8446** [comment]
Ok now running 0.6.9 however I won't be able to test the Anonymized DNS since we need the logging and content filtering

**Comment by rlesch** [comment]
Thanks for updating!
