### ISSUE TITLE
Installer / Microsoft Store App

### ISSUE THREAD

**Issue by emilvandenberg** [bitbeans/SimpleDnsCrypt#450]
Is there a description of how to make the installer? And are there ideas what is needed to package it as an app for the Microsoft Store?

**Comment by bitbeans** [comment]
Simple DNSCrypt requires administrative rights to configure the network cards and the Windows service.

I don't know if Microsoft accepts this permission for Store Apps.

`<rescap:Capability Name="allowElevation" />`

No Windows Store app is planned with the current code.

**Comment by emilvandenberg** [comment]
Thanks for answering!
