### ISSUE TITLE
a creative new feature

### ISSUE THREAD

**Issue by wysnxzm** [bitbeans/SimpleDnsCrypt#453]
At the same time request multiple DNS and get ip, and finally use the lowest latency ip to achieve network acceleration!
Currently only the fastest dns will be used, and in many cases it will increase the delay.

**Comment by wysnxzm** [comment]
Someone has implemented this function using dns-proxy, called DNS Chooser.

**Comment by bitbeans** [comment]
@wysnxzm wrong project :) please fill an issue there: https://github.com/DNSCrypt/dnscrypt-proxy

**Comment by jedisct1** [comment]
Or not :)

This is a pretty bad idea.

First, sending the same information to many third-parties decreases privacy.. You want to reduce correlation features, not to increase them.

Next, this is very selfish, and such a feature would drastically increase the load on servers, for very little gain, if any. Increasing the load on servers can increase their own latency. So, at the end of the day, resolving queries would require more traffic and cost more, for no sensible improvements.

**Comment by wysnxzm** [comment]
> Or not :)
> 
> This is a pretty bad idea.
> 
> First, sending the same information to many third-parties decreases privacy.. You want to reduce correlation features, not to increase them.
> 
> Next, this is very selfish, and such a feature would drastically increase the load on servers, for very little gain, if any. Increasing the load on servers can increase their own latency. So, at the end of the day, resolving queries would require more traffic and cost more, for no sensible improvements.

Content sent using doh is encrypted and there is no leakage privacy
Requesting multiple DNS does not bring more load to the server, but instead helps to choose a quality DNS server. Now the server performance and network quality are enough to bear this negligible traffic.
