### ISSUE TITLE
Bluetooth PC / Android

### ISSUE THREAD

**Issue by sutex** [bitbeans/SimpleDnsCrypt#454]
In trying to send/or pair my Android Phone to my PC , both having Bluetooth no connection is possible, numerous searches was unable to find if this was related to SimpleDnsCrypt installed on the PC?

**Comment by bitbeans** [comment]
@sutex I don't think SimpleDnsCrypt has anything to do with this problem.

**Comment by sutex** [comment]
Ok just checking, thanks
