### ISSUE TITLE
No routes on any resolvers

### ISSUE THREAD

**Issue by willone2** [bitbeans/SimpleDnsCrypt#455]
Hello, I'm trying to setup the new Anonymized DNS feature, but can't seem to get any routes for any resolvers to show. There is no relays file to setup manually so i'm assuming the list should populate automatically? This is happening on all relays.

![image](https://user-images.githubusercontent.com/11077351/68994231-85ac9800-0878-11ea-953b-152de3ba560d.png)

**Comment by bitbeans** [comment]
@willone2 you need start the service one time. dnscrypt-proxy will download the relays.md file.

**Comment by willone2** [comment]
I've tried removing and re-enabling the service, restarting the program, restarting my computer, trying to run the dnscrypt-proxy in the root files of the program and still no routes. What do you mean by starting the service ? Do you mean the DNScrypt service under the service tab in the main menu - as I have already tried this to no result.

**Comment by bitbeans** [comment]
Damn, I'm guessing you did an update?

Is there an relay entry in your dnscrypt-proxy.toml?

`C:\Program Files\bitbeans\Simple DNSCrypt x64\dnscrypt-proxy\dnscrypt-proxy.toml`

like:

```
[sources]

  [sources.'public-resolvers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md']
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  prefix = ''

  [sources.'relays']
  urls = ['https://github.com/DNSCrypt/dnscrypt-resolvers/raw/master/v2/relays.md', 'https://download.dnscrypt.info/resolvers-list/v2/relays.md']
  cache_file = 'relays.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''
```
I suppose that the old dnscrypt-proxy.toml was used for the update (backup) and no entry was made for the relays. 

I haven't entered any relays here:
https://github.com/bitbeans/SimpleDnsCrypt/blob/master/SimpleDnsCrypt/Helper/PatchHelper.cs#L28

Sorry, my mistake. You fix this, just open the .toml file and copy paste the [sources.'relays'] entry (from above) at the end of your file.

**Comment by willone2** [comment]
You're correct, there was no [sources.'relays'] section ( only [sources.'public-resolvers']) but after manually adding the [sources.'relays'] all is working well. Fixed!
