### ISSUE TITLE
Windows - hosts file ignored

### ISSUE THREAD

**Issue by rhy-ama** [bitbeans/SimpleDnsCrypt#464]
Thats a no-go

**Comment by ben-page** [comment]
You know this is just a front end for [dnscrypt-proxy](https://github.com/DNSCrypt/dnscrypt-proxy), right? They've decided not to use the OS hosts file, but support the same functionality with via the `cloaking-rules.txt` file. 

Most DNS _servers_ don't use the hosts. Admittedly, some forwarding proxies do. But this is generally a feature of DNS _clients_. And nothing about using dnscrypt-proxy as your DNS server stops the Windows DNS client from using the hosts file. It still works.

**Comment by Dr-Flay** [comment]
DNSCrypt has its own HOSTS system wich is capable of much more, including the cloaking rules.
To add HOSTS style blocklists, use the info on this page
https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Public-blacklists

**Comment by lessload** [comment]
This is dnscrypt-proxy problem. Please go to https://github.com/DNSCrypt/dnscrypt-proxy/issues .
