### ISSUE TITLE
Windows doesn't resolve LAN hostnames

### ISSUE THREAD

**Issue by ghiki** [bitbeans/SimpleDnsCrypt#466]
With dnscrypt enabled, Windows can't goto LAN resources (local shared folders/files, my NAS..., error is "Windows cant access to %NETWORKNAME%"). I tried disabling dnscrypt-proxy and the resources are available at the moment.

![explorer_HK1VFWxyQH](https://user-images.githubusercontent.com/854302/70004431-89be0280-1566-11ea-918a-815f0e0cc00a.png)

Current forwarding rules are:
*.lan                192.168.1.1
*.local              192.168.1.1
10.in-addr.arpa      192.168.1.1
192.in-addr.arpa     192.168.1.1
254.169.in-addr.arpa 192.168.1.1
lan                  192.168.1.1
local                192.168.1.1

And of course, the network router is in 192.168.1.1

**Comment by ben-page** [comment]
I use forwarding rules for this exact purpose and it works for me. One thing that jumps out at me is that wildcard aren't supported by DNSCrypt (or necessary). 

https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Forwarding

**Comment by ghiki** [comment]
I know (I only tried with It for discarding all the options), anyway the same rule without wildcards are at the bottom. I also tried without It and in other PCs (Windows 10 x64) with same result. 
I noticed if I click in a network device, primarily the popup error appears, but if I click on It for 8-10 times, finally It founds and connects

**Comment by ghiki** [comment]
I tried now, and also, sometimes, my NAS doesn't appear in network shares if DNSCrypt is running (maybe due the other network share is resolved through WINS instead DNS)
![MRJNLgc9lO](https://user-images.githubusercontent.com/854302/70253763-201b3f80-1784-11ea-9f89-5b44a9cd881a.gif)

**Comment by ben-page** [comment]
But have you tried it without the wildcards? They may be causing dnscrypt-proxy to fail to parse the entire `forwarding-rules.txt`. 

Like I said, it works for me. Also, you may have more luck asking for help on the dnscrypt-proxy repo. This is just a front end. Here is my forwarding-rules.txt. Maybe that will be helpful to you. It forwards my local domains to my domain controllers/dns servers.

```
168.192.in-addr.arpa  192.168.1.7, 192.168.1.6
mydomain.com          192.168.1.7, 192.168.1.6
mydomain.local        192.168.1.7, 192.168.1.6
mydomain.net          192.168.1.7, 192.168.1.6
```

**Comment by ghiki** [comment]
Yep, now I tried like this:
![SimpleDnsCrypt_tn652lIpvh](https://user-images.githubusercontent.com/854302/70255491-3080e980-1787-11ea-93f9-d84424858b66.png)

**Comment by ghiki** [comment]
Really...very strange, if I disable DNSCrypt, my NAS appears in Network, if I enable, then, it disappears:
![rK8Z4t5rCy](https://user-images.githubusercontent.com/854302/70343365-64c3db00-1857-11ea-96d0-49078db51535.gif)

**Comment by ghiki** [comment]
Solved! It was because this option blocking IPv6
![SimpleDnsCrypt_ahYMeYde16](https://user-images.githubusercontent.com/854302/70347037-f5061e00-185f-11ea-8f60-b00c91e4ac01.png)
 I thought that blocking IPv6 would be resolved through IPv4
