### ISSUE TITLE
simplednscrypt.org DNS resolving issue (mega-irony)

### ISSUE THREAD

**Issue by useribs** [bitbeans/SimpleDnsCrypt#469]
Does not from from cloudflare or google dns from where i live

[chart.pdf](https://github.com/bitbeans/SimpleDnsCrypt/files/3950836/chart.pdf)
For instance comodo (8.26.56.26) fails as well

From Linux box:

```

]# dig -t A simplednscrypt.org

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.el7 <<>> -t A simplednscrypt.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 9816
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;simplednscrypt.org.            IN      A

;; Query time: 443 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Dec 11 09:37:12 EST 2019
;; MSG SIZE  rcvd: 47


```

**Comment by useribs** [comment]
![Capture](https://user-images.githubusercontent.com/16052461/70645698-80afee00-1c56-11ea-804f-23c3017babdc.PNG)

**Comment by jedisct1** [comment]
DNSSEC issue https://zonemaster.net/result/9cece9eb909e350f

**Comment by bitbeans** [comment]
I'm not in Germany right now. I'll sign it tomorrow. Thanks for the hint

**Comment by bitbeans** [comment]
fixed
