### ISSUE TITLE
Upgrade 0.3.1 to 0.3.2 results in crash at program startup

### ISSUE THREAD

**Issue by porkrinds** [bitbeans/SimpleDnsCrypt#47]
I started up SimpleDnsCrypt this morning and noticed there was an upgrade. I did the upgrade, had the installer close dnscrypt-proxy.exe and install. Now I am greeted with the following error, and clicking OK just gives me the standard Windows dialog that simplednscrypt has stopped working and will close.

I uninstalled the program and made sure the entire bitbeans folder was removed, and then reinstalled and the same issue occurs.

edit: Win 10 x64
edit2: reverting back to 0.3.1 works ok

![capture](https://cloud.githubusercontent.com/assets/3393074/15855199/344d4634-2c7c-11e6-9845-a6ffe733514d.PNG)

**Comment by bitbeans** [comment]
@porkrinds thank you for reporting this.
I have reverted the update and will check this on W10

**Comment by bitbeans** [comment]
Should be fixed now.
I missed the libsodium.dll`s in the installer package :/

Can you confirm?

**Comment by porkrinds** [comment]
sorry to reply late to a closed issue, but yes it is working now. thank you for your time!
