### ISSUE TITLE
Automatic mode sucks

### ISSUE THREAD

**Issue by ledlamp** [bitbeans/SimpleDnsCrypt#470]
I first tried using automatic mode as is default, which is supposed to automatically select the fastest resolvers. But it just picked two resolvers, doh-crypto-sx and qualitology.com, the former not being very good and the latter being SUPER slow taking at least 5 seconds to resolve (and the domain is "for sale" so I don't understand how it's even working), _and it used the slower one most of the time_!

![https://bqpj.qonq.gq](https://bqpj.qonq.gq)

So I manually selected only cloudflare and that is working fine.

**Comment by Dr-Flay** [comment]
Just select your favoured fast resolvers and it will just use a smaller list

**Comment by SanderBouwhuis** [comment]
Related to this problem, could we have an option so every DNS lookup is done by a RANDOM resolver? So, going to a website resulting in 100 lookups would choose a random resolver for each lookup.
Possibly combine this with disabling resolvers that are too slow.
