### ISSUE TITLE
Is it possible to use Automatic Mode while disabling certain resolvers?

### ISSUE THREAD

**Issue by Phate6660** [bitbeans/SimpleDnsCrypt#472]
I'm sorry if this has already been asked before, I've searched through the issues and couldn't find anything on it.

With `dnscrypt-proxy`, you have the ability to use Automatic Mode while still blocking the use of certain resolvers. (In my case Cloudflare, Google, and a couple others.)

Is that possible with Simple DNSCrypt? Because I can't seem to find any options for it.

Note: I have to use the portable version mentioned [here](https://github.com/bitbeans/SimpleDnsCrypt/issues/373#issuecomment-447745415), because for some odd reason UAC refuses to appear with the installer. I'll literally sit there for around half an hour and UAC simply refuses to appear for the installer.

**Comment by Mishasama** [comment]
Automatic Mode ×
All Resolvers Mode √
