### ISSUE TITLE
Is it possible to replace dnscrypt-proxy with latest version?

### ISSUE THREAD

**Issue by lucknaumann** [bitbeans/SimpleDnsCrypt#474]
The latest version of dnscrypt-proxy is [2.0.36](https://github.com/DNSCrypt/dnscrypt-proxy/releases/latest). I'm wondering if it's possible to replace the currently used dnscrypt-proxy.exe 2.0.33 with the latest version? Will this break Simple DNSCrypt?
Windows 10, if that matters.
Thanks for this great program!

**Comment by SanderBouwhuis** [comment]
I've been using the latest version for a while now. Every time there is an update to dnscrypt-proxy I update. So far, I've never had a problem, but your mileage may vary.

**Comment by lucknaumann** [comment]
Thanks! That's what I thought but wasn't sure. Seems to be working so far (in the last few minutes). =)

**Comment by graphixillusion** [comment]
I've update to the last 2.0.39 without problems too. According to this, i was wondering if it's possible to add some sort of update engine for the dnscrypt directly inside the app. Thank you!
