### ISSUE TITLE
Simple DNSCrypt but Menu not Simple!! please read.

### ISSUE THREAD

**Issue by lessload** [bitbeans/SimpleDnsCrypt#482]
In my opinion, 
- The main menu should have only Service switch & Network Config.
And the application should re-design to one click base to on/off service (one click for start service and config 127.0.0.1 to interface/one click for stop and remove 127.0.0.1 from interface) that make it more "simple". 
- You should move Configuration menu to Resolver because it relate to Available Resolver. 
- You may move "remove service" to Advance Setting because not everyone want to remove it every time.
- Available Resolver make menu have two scrollbar i recommend you move to new tab or new windows ,open it by click on button in Resolver tab.
- Where is a Netprobe IP config ? why force user to use 9.9.9.9
.
If you want more user to use this app please make it more "simple"
I'm not programmer sorry for helpless.

**Comment by Skcyte** [comment]
For me it **IS** a simple version of the actual dnscrypt. Simple doesn't mean it's a one click option. You have to look/read how the dnscrypt proxy is setup without the GUI in the dnscrypt repo. Sure the GUI is definitely need some work but there hasn't been any GUI update for a long time. Even some old GUI feature that have been removed that people requested to be in hasn't been implemented yet.

The 9.9.9.9 is the default from the dnscrypt config. Why? I don't know you should ask on the dnscrypt repo.

**Comment by lessload** [comment]
> 
> 
> For me it **IS** a simple version of the actual dnscrypt. Simple doesn't mean it's a one click option. You have to look/read how the dnscrypt proxy is setup without the GUI in the dnscrypt repo. Sure the GUI is definitely need some work but there hasn't been any GUI update for a long time. Even some old GUI feature that have been removed that people requested to be in hasn't been implemented yet.
> 
> The 9.9.9.9 is the default from the dnscrypt config. Why? I don't know you should ask on the dnscrypt repo.

- I think you not understand How user experience are. You answer sound like "This app really good don't improve it". 
- 9.9.9.9 is a default ,yes. you can config directly in .toml file. What i ask is "where is this setting in GUI".
-------------------
If you don't care about user experience just use my " Simple " script
https://github.com/lessload/LESSLOAD-DNSCrypt

**Comment by slyphnier** [comment]
@lessload 
some of what u asking basically is just about personal preference
not necessary it become simpler to other person 

and also consider that programing things to be exactly what u want sometimes not easy

also that 9.9.9.9 is default fallback-resolver in advanced settings right ?

**Comment by lessload** [comment]
> 
> 
> @lessload
> some of what u asking basically is just about personal preference
> not necessary it become simpler to other person
> 
> and also consider that programing things to be exactly what u want sometimes not easy
> 
> also that 9.9.9.9 is default fallback-resolver in advanced settings right ?

Right but. what i said is `netprobe_address` not `fallback_resolver` ,when you change `fallback_resolver` `netprobe_address` has not changed accordingly. maybe is a bug?

I know is not easy. it just my recommendation to make it better in real usage. Personally, I use my [script](https://github.com/lessload/LESSLOAD-DNSCrypt/blob/master/Reload-dnscrypt.bat) instead.

**Comment by Skcyte** [comment]
> I think you not understand How user experience are. You answer sound like "This app really good don't improve it".

When did I say that? Clearly I'm pointing out that the GUI really need some work but unfortunately there hasn't been an update to the GUI for a very long time. I'm personally hoping there's improvement to the GUI, bring back old feature etc.

> If you don't care about user experience just use my " Simple " script
https://github.com/lessload/LESSLOAD-DNSCrypt

Clearly you're not a programmer.
