### ISSUE TITLE
Option to open SimpleDNSCrypt on Windows startup?

### ISSUE THREAD

**Issue by KredesX** [bitbeans/SimpleDnsCrypt#486]
Pretty much title. why is there no option to automatically open the program when Windows start.

**Comment by pc-v2** [comment]
for what? you don't know how windows' service works? 
![image](https://user-images.githubusercontent.com/58063311/78136999-be779300-744e-11ea-80c6-d682236f9f8a.png)

**Comment by pc-v2** [comment]
![image](https://user-images.githubusercontent.com/58063311/78137114-ec5cd780-744e-11ea-81e5-8e6af1ba8117.png)

**Comment by KredesX** [comment]
I wasn't aware it was installed as a windows service no, now i do. i still have an issue where i have no access to the internet when windows start, i guess the service is slow at starting.
