### ISSUE TITLE
include Cloudflare for Families - 1.1.1.2 and 1.1.1.3

### ISSUE THREAD

**Issue by danselstory** [bitbeans/SimpleDnsCrypt#487]
https://blog.cloudflare.com/introducing-1-1-1-1-for-families/

It would be good to have this options in the resolvers part.

**Comment by jedisct1** [comment]
They are already there, as `cloudflare-family` and `cloudflare-security`.

**Comment by danselstory** [comment]
cant find it from resolver list. how can I update resolver list? thank you

**Comment by jedisct1** [comment]
You can delete the `public-resolvers.*` files, or just wait for them to be automatically updated.

**Comment by leninalbertolp** [comment]
> No puedo encontrarlo en la lista de resolución. ¿Cómo puedo actualizar la lista de resolución? gracias

In the main menu you must uncheck the box **Only servers without filters**, then go to resolvers and there they will be

**Comment by leninalbertolp** [comment]
> cant find it from resolver list. how can I update resolver list? thank you

@danselstory In the main menu you must uncheck the box Only servers without filters, then go to resolvers and there they will be

**Comment by poop-code** [comment]
@leninalbertolp Thank you!👍
