### ISSUE TITLE
Adding support for all parameters?

### ISSUE THREAD

**Issue by z-ph0ria** [bitbeans/SimpleDnsCrypt#498]
Is Simple DNSCrypt x64 for Win going to finally support all settings & parameters dnscrypt-proxy got? (at this point it's lacking support for setting's to dnscrypt-proxy.toml i.e keep-alive, lb_estimator, lb_strategy, and cert_refresh_delay plus the sets to tls_cipher_suite you want to use)
I'm a real follower of this project - great work guys!

Sincerely, 
z

**Comment by bitbeans** [comment]
@z-ph0ria yes in future versions. I`am working on this: https://github.com/bitbeans/DnsCrypt.Toolbox
