### ISSUE TITLE
how can i use the global resolver?

### ISSUE THREAD

**Issue by GDWGH** [bitbeans/SimpleDnsCrypt#518]
I try to set the mobile DNS but the system try use the gateway IPV6 address just like this 

![D8EF38555254F099682D2A37CFD9AA2B](https://user-images.githubusercontent.com/57795156/94923137-f474fd00-04ed-11eb-91a5-7b92f5477fb8.jpg)
but is dosen''t work
the 192.168.1.2 is my IP address
![The address is ture](https://user-images.githubusercontent.com/57795156/94923503-8c72e680-04ee-11eb-9777-801c3acea64a.png)

**Comment by GDWGH** [comment]
they just like this(i use oppo R9tm(India version is OPPO x900x) the coloros version is 3.0.0 the android version is 5.1 the mobile install Intra but i don't know how to set it to link my computer )
[I can't make the record from mp4 to gif so i make it in the zip.zip](https://github.com/bitbeans/SimpleDnsCrypt/files/5317976/I.can.t.make.the.record.from.mp4.to.gif.so.i.make.it.in.the.zip.zip)

**Comment by achintb2** [comment]
• Get your computer's local address, example = (192.168.1.101) [can find out by doing "ipconfig" in cmd]
• Go to your router settings and set FIXED local addresses for all your devices (better that way, easier to manage, or you'd have to change settings every time your local IP changes)

• Enter the same address in DNSCrypt > Advanced Settings > Global Resolver >  Manage Listen Addresses
• Global Resolver Addresses in your DNSCrypt settings should be:
    - 0.0.0.0:53
    - 127.0.0.1:53
    - 192.168.1.101:53

• On your phone, open wifi settings > advanced options
   - DNS 1 = 192.168.1.101
   - DNS 2 = 1.1.1.1
   ! Always keep an alternate DNS server (in case your computer is off for some reason) 

In SimpleDNSCrypt Log, all queries made by your phone will also show up in the log file, with the local IP of your phone.

Any domains for clock&forward or blacklist/whitelist will also affect websites on your phone. To test if it's actually working, enter "google.com" in blocked domains and try to load google.com from your phone and see if it works.

I've successfully set up an always-on small server which acts as a global DNS resolver for all devices on my local network. Easy to keep track of and backed up by a UPS so it stays on even during a power cut.

You should also be able to do this for multiple subnets (192.168.1.xxx / 192.168.2.xxx / 192.168.3.xxx) and it should theoretically act as the DNS resolver on those networks too (haven't tried that yet however)

Your Windows machine will now listen on port 53 on the local address for incoming DNS requests from other devices.
**Use IPv4 ONLY** as the global resolver. Much easier to implement.

[img]https://i.imgur.com/obn8NzC.png[/img]

**Comment by GDWGH** [comment]
> • Get your computer's local address, example = (192.168.1.101) [can find out by doing "ipconfig" in cmd]
> • Go to your router settings and set FIXED local addresses for all your devices (better that way, easier to manage, or you'd have to change settings every time your local IP changes)
> 
> • Enter the same address in DNSCrypt > Advanced Settings > Global Resolver > Manage Listen Addresses
> • Global Resolver Addresses in your DNSCrypt settings should be:
> - 0.0.0.0:53
> - 127.0.0.1:53
> - 192.168.1.101:53
> 
> • On your phone, open wifi settings > advanced options
> 
> * DNS 1 = 192.168.1.101
> * DNS 2 = 1.1.1.1
>   ! Always keep an alternate DNS server (in case your computer is off for some reason)
> 
> In SimpleDNSCrypt Log, all queries made by your phone will also show up in the log file, with the local IP of your phone.
> 
> Any domains for clock&forward or blacklist/whitelist will also affect websites on your phone. To test if it's actually working, enter "google.com" in blocked domains and try to load google.com from your phone and see if it works.
> 
> I've successfully set up an always-on small server which acts as a global DNS resolver for all devices on my local network. Easy to keep track of and backed up by a UPS so it stays on even during a power cut.
> 
> You should also be able to do this for multiple subnets (192.168.1.xxx / 192.168.2.xxx / 192.168.3.xxx) and it should theoretically act as the DNS resolver on those networks too (haven't tried that yet however)
> 
> Your Windows machine will now listen on port 53 on the local address for incoming DNS requests from other devices.
> **Use IPv4 ONLY** as the global resolver. Much easier to implement.
> 
> https://i.imgur.com/obn8NzC.png

i can't use imgur because my country lock it

**Comment by achintb2** [comment]
That's alright, the screenshot showed the global resolver settings only.
I've typed those settings in the initial message anyway.

• Global Resolver Addresses in your DNS Crypt settings should be:
- 0.0.0.0:53
- 127.0.0.1:53
- 192.168.x.x:53 (x = your computer's local network address : 53 = Port used for DNS)

**Comment by GDWGH** [comment]
> 没关系，屏幕截图只显示了全球解析器设置。
> 我已经在初始消息中键入了这些设置。
> 
> • DNS 加密设置中的全球解析器地址应该是：
> 
> * 0.0.0.0:53
> * 127.0.0.1:53
> * 192.168.x：53 （x = 计算机的本地网络地址 ： 53 = 用于 DNS 的端口）

my phone is look like locked the first dns 
it alway turn it back fe80::1
when i try type in the DNS slot 1 when it save 
the first slot address was move to the DNS slot 2 
then the dns slot 1 turn the address to fe80::1

**Comment by fusionneur** [comment]
I managed to make it work
1. remove dnscrypt service first (or else there's a bug that i could not add listening addresses)
2. dnscrypt > advanced settings > manage listen addresses > add hosts's IP provided in router besides 0.0.0.0 and 127.0.0.1

![image](https://user-images.githubusercontent.com/7840350/113416025-167e0800-93c9-11eb-934c-f3cb6fda84fd.png)

3. configure router to port forward the port in lan

source IP 192.168.x.y (the ip of the host where dnscrypt is running)
destination IP : the LAN range (to include the IPs that are offered by router DHCP or the IPs manually set as static. so that all devices can use the your dns server)

![image](https://user-images.githubusercontent.com/7840350/113415956-f4848580-93c8-11eb-99fa-cf6848b2558e.png)

4. install dnscrypt service

5. on another LAN device add dns server as "192.168.x.y" (the ip of the host where dnscrypt is running)
6. test : nslookup github.com

**Comment by GDWGH** [comment]
> 1. router


i m sorry because my router is bad it can't set the dns but thanks
