### ISSUE TITLE
Create 64bit branch

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [bitbeans/SimpleDnsCrypt#55]
Simple DNSCrypt should create 64bit version after [DNSCrypt 1.7.0](https://github.com/jedisct1/dnscrypt-proxy/releases/tag/1.7.0) released.

**Comment by dimqua** [comment]
Yes, the latest [64-bit dnscrypt-proxy build](https://download.dnscrypt.org/dnscrypt-proxy/LATEST-win64-full.zip) should be bundled instead.

**Comment by Rictusempra** [comment]
It is now 1.9.x, I think this can be fix together with #138

**Comment by bitbeans** [comment]
@KrasnayaPloshchad @dimqua @Rictusempra https://github.com/bitbeans/SimpleDnsCrypt/releases/tag/0.4.3
