### ISSUE TITLE
add Automatic startup

### ISSUE THREAD

**Issue by Pantyhose-X** [bitbeans/SimpleDnsCrypt#556]
Every time you restart your computer, you need to manually start SimpleDnscrypt or you won’t be able to connect to the Internet

# Solutions
add Automatic startup

**Comment by slyphnier** [comment]
it does automatic start-up

make sure DNScrypt service enable (if enabled, then try disable, then re-enable again)

to make sure it working : open windows services > look for DNSCrypt client proxy  > make sure Start-up type is "automatic"

if everything set like that, but still not starting, u can try change start-up type to "automatic delayed start" and see if this fix ur issue

**Comment by Pantyhose-X** [comment]
Tried to no avail must need to manually start SimpleDnscrypt Can link Internet

> it does automatic start-up
> 
> make sure DNScrypt service enable (if enabled, then try disable, then re-enable again)
> 
> to make sure it working : open windows services > look for DNSCrypt client proxy > make sure Start-up type is "automatic"
> 
> if everything set like that, but still not starting, u can try change start-up type to "automatic delayed start" and see if this fix ur issue

Tried to no avail must need to manually start SimpleDnscrypt Can link Internet

**Comment by slyphnier** [comment]
then something prevent it starting up, it can be various things, such windows privileges related or internet-security software

make sure dnscrypt-proxy.exe is allow to start
white list it on security software, and maybe also try, enable "run-as-administrator" dnscrypt-proxy.exe

you need to find what preventing it to start, and this is not simplednscrypt issue
