### ISSUE TITLE
dns queries leaked when ipv6 is used

### ISSUE THREAD

**Issue by rugk** [bitbeans/SimpleDnsCrypt#58]
I had an issue where no dns lookups were routed to dnscrypt. (tested with `nslookup`, whicuh always used an IPv6 resolver)

So I found out that Windows used the ipv6 dns servers to resolve the domain names. But putting `::1` into the nameserver config of the Ipv6 interface does not work. I assume "dnscrypt-proxy" does not support Ipv6.

**Comment by zymase** [comment]
I'm far from being an expert but seems to me DNSCrypt handles ipv6 if the encrypted DNS resolver handles it, i.e you have cisco and cisco-ipv6, dnscrypt.eu-dk and dnscrypt.eu-dk-ipv6, dnscrypt.eu-nl and dnscrypt.eu-nl-ipv6 (plus 3 other resolvers handling -ipv6 at this time according to the dnscrypt-resolvers.csv dated 05-Aug-2016 23:30)

Just my guess.

**Comment by rugk** [comment]
I tried it with the Cisco resolver and no, it is not working.

**Comment by zymase** [comment]
My ISP doesn't handle IPV6 yet so I have no means of testing for myself. I could have compared results when running here latest  DNSCrypt-Proxy 1.7.0 via command-line with your experience running I guess previous DNSCrypt engine if the front-end is SimpleDnsCrypt (not updated yet to use DNSCrypt-Proxy 1.7.0).

**Comment by bitbeans** [comment]
IPv6 see: #1
