### ISSUE TITLE
"Primary DNSCrypt Service" button stays grey"

### ISSUE THREAD

**Issue by FoLkjF** [bitbeans/SimpleDnsCrypt#61]
"Primary DNSCrypt Service" button stays grey, not green as shown on the download page.

Resolver is "DNSCrypt.eu Holland"

btw, i have this installed on a Win 2008 server, as all my local DNS resolving goes through there. 
does DNSCrypt work on a Win 2008 server?

**Comment by bitbeans** [comment]
Not tested with Win 2008 server.

Can you check the nameservers on your network card configuration?
It will be green if there is the correct nameserver ip eg: 127.0.0.1
