### ISSUE TITLE
LAN Connection Problem

### ISSUE THREAD

**Issue by zero77** [bitbeans/SimpleDnsCrypt#64]
Sometimes when connecting to open wifi, DnsCrypt blocks the connection to resolve it I disconnect and disable the connect again.

**Comment by bitbeans** [comment]
Don`t know if this i a SimpleDnsCrypt problem.

**Comment by zero77** [comment]
I could be wrong but I'm confident it is down to DNSCrypt. Because disconnecting from the network then disabling DNSCrypt then reconnecting to the network and then enabling DNSCrypt again, fixes the problem.
