### ISSUE TITLE
dns not working Version 0.3.6

### ISSUE THREAD

**Issue by robin98** [bitbeans/SimpleDnsCrypt#68]
Hi Guys;
In version 0.3.6 of simplednscrypt, after about 5 or 10 minutes, dns not working and not any hostnames will be resolved.
i had to open simplednscrypt and restart DNS service or change DNS resolver for several times to come back DNS resolvable.
and after 10 minutes.... again!
also i have this problem on all 3 windows 10 devices.

**Comment by zymase** [comment]
More of a _Windows 10_ problem (one more) then a _Simple DNSCrypt_ issue, IMO.
Running _Simple DNSCrypt 0.3.6_ flawlessly (blacklisted domains and addresses plug-in included) here on Windows 7 Home 64-BIT

**Comment by bitbeans** [comment]
Simple DNSCrypt only configures the dnscrypt-proxy service. After the configuration it will not change anything. You can test the service by hand: https://github.com/jedisct1/dnscrypt-proxy/blob/master/README-WINDOWS.markdown#quickstart
