### ISSUE TITLE
Problem with resolving

### ISSUE THREAD

**Issue by gingadriver** [bitbeans/SimpleDnsCrypt#69]
Hello, I have stumbled a problem where dnscrypt is stuck in resolving when a download/media streaming is going on, also happen when other devices on my network is downloading/media streaming, dnscrypt on my PC will stop resolving, it could be problem with my ISP, but I am not sure since it worked fine before, any solution would be appreciated, Thank you!

Version 0.3.6

**Comment by bitbeans** [comment]
Maybe try another resolver

**Comment by gingadriver** [comment]
I did, but it happen again after some time.
