### ISSUE TITLE
Update resolver list automatically

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [bitbeans/SimpleDnsCrypt#70]
This is useful. If dnscrypt-resolvers.csv has been [modified](https://github.com/jedisct1/dnscrypt-proxy/commits/master/dnscrypt-resolvers.csv), then SimpleDnsCrypt could synchronlize it by itself.

**Comment by bitbeans** [comment]
SimpleDnsCrypt updates the list on every start. Whitout a manual change the resolver will not change, so there is no need for a background service.
