### ISSUE TITLE
Allow to choose fastest Resolver server

### ISSUE THREAD

**Issue by MKaveh** [bitbeans/SimpleDnsCrypt#71]
By adding a button next to "Resolver" list. so that we can check all the working resovers for their speed. and choose the fastest server or lists and sorts servers by their speed (e.g. ping time).

**Comment by bitbeans** [comment]
Testproject for this option: https://github.com/bitbeans/dnscrypt-measurement

**Comment by bitbeans** [comment]
done

**Comment by MKaveh** [comment]
Thansk for implementing this feature;

2017-01-04 10:19 GMT+03:30 Christian Hermann <notifications@github.com>:
