### ISSUE TITLE
Combine addresses and IP lists for block plugin

### ISSUE THREAD

**Issue by Skrell** [bitbeans/SimpleDnsCrypt#72]
It would be great if we didn't have to supply 2 separate txt files when providing a list of domains/IPs we're looking to block.

**Comment by zymase** [comment]
Remember SimpleDnsCrypt is only a front-end application of DNSCrypt-Proxy. Combining domains and IPs blacklists concerns DNSCrypt, not SimpleDnsCrypt. This said I agree it would be welcomed even if I imagine that blocking a domain occurs before the DNS resolution and the IP after, hence a perhaps problematic situation to combine both in one list.
