### ISSUE TITLE
server DNS address could not be found

### ISSUE THREAD

**Issue by hitrust** [bitbeans/SimpleDnsCrypt#73]
the blocked website still not access. the unblocked webs
![dns](https://cloud.githubusercontent.com/assets/3360631/20302364/ecf1d3d0-ab61-11e6-8c9b-2355e83bbad7.PNG)
![dns1](https://cloud.githubusercontent.com/assets/3360631/20302475/6fb5c998-ab62-11e6-8e50-b9ccbd81e1a1.PNG)

ite accessed well

**Comment by HJLBX** [comment]
Windows 10 Home
Version 1607
OS Build 14393.447

I can confirm.  With Simple DNSCrypt installed on system, there are intermittent:

A.  Windows could not automatically detect the system proxy settings

http://i63.tinypic.com/2qnm8ef.png

B.  DNS Server could not be found

**Comment by bitbeans** [comment]
Please update to the latest version: 0.3.9

**Comment by tonytranupc** [comment]
Here are a few methods you can try. Check it out!

https://usefulpcguide.com/18596/server-dns-address-could-not-be-found/
