### ISSUE TITLE
WindowsXP and also portable versions - skipping to .Net Core (?)

### ISSUE THREAD

**Issue by DI555** [bitbeans/SimpleDnsCrypt#75]
Would be great to see WindowsXP versions (1) and also a portable versions (2) !!!
Does (1) take .Net 3.5 ?
and does (2) take including needed libs from MS .Net 4.5 ?

And as a suggestion of all - may be should to skip to .Net Core instead of .Net 4.5 ?

**Comment by bitbeans** [comment]
@DI555 Windows XP support, will never happen! :)

https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet
