### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by c0nfuci05** [bitbeans/SimpleDnsCrypt#76]
I had a quick question and wasn't sure who to contact from github pages so here it goes: is there a way to verify your system is using SimpleDNS? Also, do you need to change adapter settings within Windows manually or does the SimpleDNS client handle all of that?
Thanks

**Comment by bitbeans** [comment]
Hey, yes SimpleDNS should change the adapter settings automatically (after click on network adapter).

One way to check it: https://dnsleaktest.com
