### ISSUE TITLE
Save settings into dnscrypt-proxy.conf

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [bitbeans/SimpleDnsCrypt#77]
Recently DNSCrypt introduced a [configuration file](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy.conf) to save the settings. With this file we can get the better way to save & load the settings, so Simple DNSCrypt should allowing users to save settings into this file.

**Comment by HXmniDhWNevihHm7PwVyN4Knvt9yQrRt** [comment]
Hello,
it would be nice to be able to use it for the forwarding plugin as referenced in #121.
Regards
Andreas

**Comment by KrasnayaPloshchad** [comment]
Simple DNSCrypt can also add an option to import/expert the settings based on this support.

**Comment by chstdu** [comment]
Windows 10 tells me that I have no internet access although I am on GitHub now. I guess I can fix it if I bypass my primary DNS suffix (this internal site is the only one which I cannot access any more with simple DnsCrypt). How can I activate "forwarding" which was included in #152 and save the settings? Thank you in advance!
