### ISSUE TITLE
Cant install this MSI

### ISSUE THREAD

**Issue by bercel** [bitbeans/SimpleDnsCrypt#78]
its say like this & i cant install the software
![image](https://cloud.githubusercontent.com/assets/11014707/21332905/bf7a8f56-c686-11e6-9af4-92c19f8709a4.png)

**Comment by bitbeans** [comment]
Which OS? :)

**Comment by ellephantz** [comment]
win 7 32bit

screenshot:
![2017-01-07_132504](https://cloud.githubusercontent.com/assets/24971380/21740083/645eb350-d4e0-11e6-8d4f-56e648dd994d.png)

log file from installer error:

[MSI5d45f.zip](https://github.com/bitbeans/SimpleDnsCrypt/files/691324/MSI5d45f.zip)

**Comment by bitbeans** [comment]
@ellephantz do you have .NET 4.6 installed?

**Comment by ellephantz** [comment]
yes, i have it
.NET 4.6.2 already installed

**Comment by bitbeans** [comment]
Okay can you test the zip file: https://github.com/bitbeans/SimpleDnsCrypt/releases/download/0.4.0/SimpleDNSCrypt_0.4.0.zip

without the msi installer.

**Comment by ellephantz** [comment]
it run nicely with the zip file

but why i can't use the installer ?
hope you can tell me about it

**Comment by bitbeans** [comment]
i need to investigate this.
But i thought the installer want .NET 4.6 not 4.6.x.

**Comment by ellephantz** [comment]
Thank you sir
I'll wait for more info   :)

**Comment by bitbeans** [comment]
@ellephantz it`s sees to be the Uninstall.exe which fails during the installation.
Have you done a new installation or an upgrade?

**Comment by ellephantz** [comment]
i started using simplednscrypt from ver 0.3.3
there was no problem with new installation or upgrade before, 
start from version 0.3.8 installer release, i seeing error like that when running the installer
