### ISSUE TITLE
no network connection after Simple Dnscrypt 3.7

### ISSUE THREAD

**Issue by GRMansell** [bitbeans/SimpleDnsCrypt#82]
No problems with 3.6 
3.7 gui shows encryption to DNSCrypt.org France
Using Win10 pro 64 bit Intel Dell. 
I have that awful Google fiber router, wifi turned off. 
I don't use DHCP.
dns @ 127.0.0.1 
IPV4 only
Thanks

**Comment by zymase** [comment]
I've encountered the same problem with _**DNSCrypt.org France**_  (dnscrypt.org-fr) when called from _Simple DNScrypt 3.7_, and this, repeatedly: it seems '_DNSCrypt.org France_' is totally inaccessible. As well, this continuous impossibility to use '_DNSCrypt.org France_' didn't occur with _Simple DNScrypt 3.6_

No other resolver (haven't tested them all) presents the same blockage. I did encounter failures with _dnscrypt.eu-nl_ as well as with _dnscrypt.eu-dk_, but these resolvers are known for their regular disconnections. I have no idea of the specificity of the _dnscrypt.org-fr_ problem. I'm puzzled as well but I believe it would be rather related to _dnscrypt-proxy 1.8.1_ than to its front-end, _Simple DNScrypt_. If the issue appears with _Simple DNScrypt 3.7_ and didn't with _3.6_ it could be that only _Simple DNScrypt 3.7_ uses _dnscrypt-proxy 1.8.1_

**Comment by GRMansell** [comment]
Thanks. Other resolvers seem fine @ 3.7. Can I see what release of dnscrypt-proxy I have?

**Comment by zymase** [comment]
Simple DNSCrypt's release page mentions that the version of dnscrypt-proxy used for its version 0.3.7 is 1.8.1:

> https://github.com/bitbeans/SimpleDnsCrypt/releases

Installed dnscrypt-proxy.exe and dnscrypt-proxy-secondary.exe do not include their version number in their Proprieties page. I assume the version is 1.8.1
