### ISSUE TITLE
Problem with minisign signature on https://simplednscrypt.org/

### ISSUE THREAD

**Issue by cmschroeder91** [bitbeans/SimpleDnsCrypt#84]
If one downloads SimpleDNSCrypt.msi and the associated SimpleDNSCrypt.msi.minisig from links on the web site https://simplednscrypt.org/, the verification fails. If they are downloaded directly from github then the verification is successful. Presumably the .minisig is out of sync with the .msi on simplednscrypt.org.

**Comment by bitbeans** [comment]
Good catch! The signature target on the website is still on 0.3.6.
I will release 0.3.8 soon.
