### ISSUE TITLE
0ms latency

### ISSUE THREAD

**Issue by jedisct1** [bitbeans/SimpleDnsCrypt#87]
0ms of latency is super fast, but I don't think it's real :)

This is a realy nice feature, btw. Kudos!

![screen shot 2017-01-03 at 11 40 11 am](https://cloud.githubusercontent.com/assets/124872/21605428/83cd8458-d1a9-11e6-8e5c-457054f9c2ca.jpg)

**Comment by bitbeans** [comment]
Seem there are some errors :) I reverted 0.3.8

Thanks for reporting!!!
