### ISSUE TITLE
Some Cards Not Listed

### ISSUE THREAD

**Issue by christantoan** [bitbeans/SimpleDnsCrypt#9]
Some of my cards (especially "Ethernet", which I need) doesn't get listed even if I enable show hidden cards
![2015-10-14_05-00-31](https://cloud.githubusercontent.com/assets/7300310/10469599/bf21f978-7230-11e5-859f-668954754aa5.png)
Also, I can't scroll if the window size is too small (as in screenshot) so I need to enlarge manually, which is not good in design?

**Comment by bitbeans** [comment]
It`s not listed, because it`s not connected.

**Comment by christantoan** [comment]
Can it be fixed? I know I can just go to the network card properties manually but I prefer automated solution. 

Thanks

**Comment by bitbeans** [comment]
yes i will fix this
