### ISSUE TITLE
Update: Simplified Chinese

### ISSUE THREAD

**Issue by bitbeans** [bitbeans/SimpleDnsCrypt#90]
[Strings.zh.resx](https://github.com/bitbeans/SimpleDnsCrypt/blob/master/SimpleDnsCrypt/Resources/Strings.zh.resx ) needs to be updated.

@jerryhou85 maybe you can assist :)

**Comment by jerryhou85** [comment]
Oops, just saw this. OK, I'll update it soon. :)
