### ISSUE TITLE
Update: Danish

### ISSUE THREAD

**Issue by bitbeans** [bitbeans/SimpleDnsCrypt#91]
[Strings.da.resx](https://github.com/bitbeans/SimpleDnsCrypt/blob/master/SimpleDnsCrypt/Resources/Strings.da.resx ) needs to be updated.

@simonclausen maybe you can assist :)

**Comment by simonclausen** [comment]
I'm just running through my stack of GitHub notifications. Better late than never, I guess - sorry for not getting back on this!

I have not used POEditor before - it looks like Danish is not in there yet, correct?

**Comment by bitbeans** [comment]
@simonclausen you cann add **Danish** in poeditor :)
