### ISSUE TITLE
Update: Indonesian

### ISSUE THREAD

**Issue by bitbeans** [bitbeans/SimpleDnsCrypt#94]
[Strings.id.resx](https://github.com/bitbeans/SimpleDnsCrypt/blob/master/SimpleDnsCrypt/Resources/Strings.id.resx ) needs to be updated.

@christantoan maybe you can assist :)

**Comment by christantoan** [comment]
Done

**Comment by bitbeans** [comment]
Ok that was fast! Thank you very much!! 👍
