### ISSUE TITLE
Update: Persian

### ISSUE THREAD

**Issue by bitbeans** [bitbeans/SimpleDnsCrypt#96]
[Strings.fa.resx](https://github.com/bitbeans/SimpleDnsCrypt/blob/master/SimpleDnsCrypt/Resources/Strings.fa.resx ) needs to be updated.

@robin98 maybe you can assist :)

**Comment by robin98** [comment]
I take this.
it's done.

**Comment by bitbeans** [comment]
thank you very much!! :D
